### ISSUE TITLE
allow headerLeft on index 0

### ISSUE THREAD

**Issue by pvinis** [react-community/react-navigation#1015]
i see no reason why i shouldnt be able to put a left button on the screen at 0 index.
its currently hardcoded to return null. is there a good reason for that choice besides to hide an "easy" back button?

**Comment by dantman** [comment]
This is a really bad breakage, as it seems to break the ability to add a menu button for drawers.

**Comment by pvinis** [comment]
I made a private that allows is again.

**Comment by pvinis** [comment]
https://github.com/react-community/react-navigation/pull/1017

**Comment by grabbou** [comment]
It's a regression. Thanks @pvinis for sending over a PR! I decided to merge it into my #1027 that attempts to fix few more regressions.

**Comment by annelorraineuy** [comment]
`headerLeft` still doesn't work for me on `1.0.0-beta.9`, on a screen at index 0. 

I got around it by replicating the header component as a custom React element and set it as `header`. I was easily able to add my left and right components.

**Comment by rightaboveit** [comment]
I also have the same issue where `headerLeft` didn't work on `index 0` with `^1.0.0-beta.11` for testing which made me think that I had missed something until I put the screens back in order.

**Comment by spruce-bruce** [comment]
My experience with this is that if I set headerLeft to a react element it always shows, but if I use a component it won't show on index 0.

```
{
  // always shows
  headerLeft: <Text>override</Text>

  // does not show at index 0
  headerLeft: (props) => <Text>override</Text>
}
```

And then if you go dig through the code, you see of course that this isn't a bug, it's built specifically to do this:

```
    const { options } = props.scene.descriptor;
    if (
      React.isValidElement(options.headerLeft) ||
      options.headerLeft === null
    ) {
      return options.headerLeft;
    }

    if (props.scene.index === 0) {
      return;
    }

    ...dostuff
```

I'm running into a situation where I have a stack navigator nested inside another stack navigator. When my user is in the child stack, I hide the header from the parent stack and show the header from the nested stack.

When my user is viewing the child stack at index 0, I want to show `headerLeft` with a back button. I can accomplish this with `headerLeft: <MyOverride />` but I'd rather have access to the props that are normally passed in with `headerLeft: props => <MyOverride ...props />`.

Would it make sense to expose the "hide on index 0" behavior as a configuration option? Would it make sense to say "if the user provides a `headerLeft` value never hide on index 0"?

I can only think of one instance where I want to hide headerLeft on index 0 and that is when the stack navigator is the root navigator. Otherwise i'm either hiding the header all together, or showing headerLeft seems desirable. Am I being too narrow minded in my thinking?
