### ISSUE TITLE
First TextInput focus causes immediate blur on Android + TabNavigator

### ISSUE THREAD

**Issue by adamterlson** [react-community/react-navigation#1023]
If a TextInput is used on a TabNavigator, when the user clicks to focus the TextInput when the app first loads and the keyboard is raised then instantly lowered due to blur being fired on the TextInput.  It is then possible to re-focus the TextInput as normal.

![repro](https://cloud.githubusercontent.com/assets/2498418/25006814/a615cfb2-205e-11e7-8a65-ae87d2d25a6b.gif)

The code is quite simple:

```
import React from 'react'
import { TabNavigator } from 'react-navigation'
import { TextInput } from 'react-native'

const ScreenA = () => (
    <TextInput
        style={{ height: 50 }}
    />
)

const ScreenB = () => ( ... )

const Root = TabNavigator({
    ScreenA: { screen: ScreenA },
    ScreenB: { screen: ScreenB },
})
```

**Comment by xwjgo** [comment]
Do you have fixed this problem?

**Comment by adamterlson** [comment]
Nope. Open issue.

**Comment by xwjgo** [comment]
It's a bug of react-navigation. After I updated my package.json to include the following, everyting seems like normal:

```
"react-navigation": "git+https://github.com/react-community/react-navigation.git#ec74206"
```

**Comment by ferdicus** [comment]
Have the same issue and @xwjgo fix didn't do anything for me unfortunately...
Any updates on this?

**Comment by kelset** [comment]
Pinging OP @adamterlson since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by adamterlson** [comment]
@kelset Happy to say that after retesting on latest RN and React Navigation, this issue appears solved.

**Comment by nol13** [comment]
Still having same issue, react-native 0.50.4, react-navigation 1.0.0.0-beta.21. using TabNavigator as my root navigator.

Doesn't happen if I use StackNavigator as root, and goes away if I add a screen/tab beforehand and set lazy to true.

**Comment by nol13** [comment]
^i still need to have lazy=true set though even with the timeout, timeout just avoids needing an extra screen

**Comment by eli0shin** [comment]
The fact that the tab navigator keeps all it's 1st degree scenes mounted at all times has been the source of multiple bugs for me, this being one of them. One of my tabs is a search tab and he only way i can find to autofocus the TextInput is to make a messy .focus()) call using refs as `autoFocus` does not work because it is called in componentDidMount(). This works in IOS but in android the TextInput loses focus as soon as it get's it and I'm really at a loss at this point as to how I can remedy this situation.

**Comment by burakggs** [comment]
Hello @kelset 
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.9.4
  Yarn: Not Found
  npm: 4.6.1
  Watchman: Not Found
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4907809

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.2 => 0.52.2
"react-navigation": "^1.6.1",...

I use react-navigation last version, but seemed same error (keyboard will automatically)
I don't understand

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
