### ISSUE TITLE
Release Cycle Info?

### ISSUE THREAD

**Issue by f0rr0** [react-community/react-navigation#1061]
Currently using react-navigation for housing.com's new apps. The releases seemed to be fairly frequent initially. Is there an agreed upon release schedule from the core maintainers?

**Comment by m1ck2** [comment]
Hopefully this helps 
// Add the header at the top of the file:
#import <React/RCTLinkingManager.h>

// Add this above the `@end`:
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication annotation:(id)annotation
{
  return [RCTLinkingManager application:application openURL:url
                      sourceApplication:sourceApplication annotation:annotation];
}

**Comment by m1ck2** [comment]
The react-community/ react-navigation

**Comment by f0rr0** [comment]
@m1ck2 i think you commented on the wrong issue here

**Comment by mmazzarolo** [comment]
I'm interested in it too, do you have any scheduled release plan? Thanks!

**Comment by grabbou** [comment]
The release schedule is rather undefined. We release when we feel confident with the amount of changes. That release (v8) is special, because it contains few breaking changes. We are holding with it because we need to make sure upgrade path is smooth, docs are in place and no-one is going to end up with a broken app.

There's also F8 conf and React Amsterdam happening this week which reduces our time significantly.

The plan for next release is to land at the beginning of next week.

For the details, check #723

**Comment by mmazzarolo** [comment]
Thank you :)
