### ISSUE TITLE
Custom drawer overlay color

### ISSUE THREAD

**Issue by sergeylaptev** [react-community/react-navigation#1068]
Would be great to implement drawer styles customizations:)

**Comment by przemkow** [comment]
I haven't used it yet but does `contentComponent` option from `DrawerNavigatorConfig` wouldn't be enough to add custom styles?

**Comment by sergeylaptev** [comment]
contentComponent is about internal drawer styles, not container

**Comment by grabbou** [comment]
Also see https://reactnavigation.org/docs/navigators/drawer#contentOptions-for-DrawerView.Items. If none of these is enough, please let me know your use case and proposed solution to it.

**Comment by dantman** [comment]
@grabbou All those options are for customizing the red area, have you considered that @sergeylaptev may be talking about the opacity levels/color of the blue area that no react-navigation option covers?
![x](https://cloud.githubusercontent.com/assets/53399/25347112/aa833b66-28ce-11e7-8fa3-e0125c1cffde.png)

**Comment by sergeylaptev** [comment]
@dantman Exactly! I was asking about blue area on the screenshot above. Unfortunately, even [drawer library](https://github.com/react-native-community/react-native-drawer-layout-polyfill) which react-navigation use doesn't support this customisation (e.g. iOS version) and has predefined '#000' colour with opacity.

**Comment by mattfysh** [comment]
would also like to see this configurable, colour is okay just hoping to change the opacity from 0.7 to 0.5 ;)

**Comment by gourav-singhal** [comment]
Any update on this? I also want to set  the opacity to 1.

**Comment by luco** [comment]
+1 on this. Updates?

**Comment by RUIFERNANDE5** [comment]
+1

**Comment by barghi** [comment]
+1

**Comment by rformato** [comment]
+1

**Comment by Donhv** [comment]
+1. I want chang opacity

**Comment by brentvatne** [comment]
please submit a pr or open a feature request and upvote! :)

**Comment by JulianKingman** [comment]
Shouldn't this issue still be open?

I tracked this to the source, it's rather complicated...

`react-navigation` depends on [react-navigation-drawer](https://github.com/react-navigation/react-navigation-drawer)
`react-navigation-drawer` depends on [react-native-drawer-layout-polyfill](https://github.com/react-native-community/react-native-drawer-layout-polyfill)
`react-navigation-polyfill` exposes `DrawerLayoutAndroid` (RN core) for Android, and polyfills with [react-native-drawer-layout](https://github.com/react-native-community/react-native-drawer-layout) for iOS

For iOS (`react-native-drawer-layout`), it's possible to add a prop for changing the color (defined here: https://github.com/react-native-community/react-native-drawer-layout/blob/master/src/DrawerLayout.js#L424)

For android, however... There's a native function (in the root Android component) called `setScrimColor`, that will change the color of the overlay, however, it doesn't appear to be exposed ([relevant java file](https://github.com/facebook/react-native/blob/6e359c4589b0627de59332ce56fe28804425a609/ReactAndroid/src/main/java/com/facebook/react/views/drawer/ReactDrawerLayoutManager.java))

@brentvatne is there a way to call a function that's not explicitly exposed, using the RN api, using NativeModules or UIManager or something? It seems like it might be possible, since what's passed into android extends the native module, so the functions might still be available? Anyway, that would be cool, and allow a simple PR, otherwise a PR needs to be made to the RN core to allow this. Somebody posted an example of what it could look like [on SO](https://stackoverflow.com/questions/41058512/reactnative-remove-shadow-from-drawerlayoutandroid?noredirect=1&lq=1).

**Comment by brentvatne** [comment]
this is a feature request, feature requests belong on http://reactnavigation.canny.io/

this issue tracker is for bugs

**Comment by brentvatne** [comment]
sorry, the correct link is https://react-navigation.canny.io/

**Comment by Runtime007** [comment]
`drawerType: 'slide',
  overlayColor: '00FFFFF',
`
set `overlayColor` is useful for me. RN version 0.59.1

**Comment by karanpratapsingh** [comment]
@Runtime007 Thanks mate

**Comment by jordanpicaso** [comment]
@Runtime007 It's the real solution , thank you man

**Comment by sbearben** [comment]
@Runtime007 where is that config supposed to go in the context of `createDrawerNavigator`?

**Comment by RahulNainwal** [comment]
const DrawerNavigation = createDrawerNavigator({
  HomeTab: {
    screen: HomeTab
  },
},
  {
    initialRouteName: 'HomeTab',
    headerMode: 'none',
    drawerBackgroundColor: '#5A6B71',
    overlayColor: '#6b52ae',
    backBehavior: 'initialRoute',
    contentComponent: (props) => <CustomDrawerNavigation {...props} />,
    navigationOptions: {
      gesturesEnabled: true
    },
  },
)
Use overlayColor for this inside createDrawerNavigator like this.

**Comment by thewaver** [comment]
`overlayColor` is not declared inside `typescript/react-navigation.d.ts` and even though I am able to use it, I now have unsilenceable linter errors on my project, which I cannot afford.

**Comment by tripexito** [comment]
Solution posted [here](https://github.com/react-navigation/react-navigation/issues/6208#issuecomment-524091241) by @AGIsmail works fine for me, it let me change overlay color and opacity ;-) 
`const DrawerNavigatorExample = createDrawerNavigator({ ... }, { ... overlayColor: "rgba(0, 0, 0, 0.7)", ... }); `

**Comment by raphaelpinel** [comment]
It is now in the official docs here: [https://reactnavigation.org/docs/drawer-navigator/#options](url)
Search for overlayColor. They give this example
```
import { createDrawerNavigator } from '@react-navigation/drawer';

const Drawer = createDrawerNavigator();

function MyDrawer() {
  return (
    <Drawer.Navigator
      openByDefault
      overlayColor="transparent"
    >
      {/* Screens */}
    </Drawer.Navigator>
  );
}
```
