### ISSUE TITLE
Deep linking for nested navigators while using Redux

### ISSUE THREAD

**Issue by atshakil** [react-community/react-navigation#1106]
Deep linking is working fine for nested navigators when they are directly set as screens of a parent navigator.
```
const S1 = () => <View><Text>S1 text</Text></View>;
const S2 = () => <View><Text>S2 text</Text></View>;
const S3 = () => <View><Text>S3 text</Text></View>;

const S5 = () => <View><Text>S5 text</Text></View>;
const S6 = () => <View><Text>S6 text</Text></View>;

const Nav1 = StackNavigator(
  {
    S5: {screen: S5, path: 's5'},
    S6: {screen: S6, path: 's6'}
  }
);

const Nav2 = StackNavigator(
  {
    S1: {screen: S1},
    S2: {screen: S2, path: 's2'},
    S3: {screen: S3, path: 's3'},
    S4: {screen: Nav1, path: 's4'}
  },
  {
    containerOptions: {
      URIPrefix: Platform.OS == 'android' ? 'http://localhost/' : 'http://'
    }
  }
);

export default Nav2;
```
`Nav2` as a top level navigator, working properly and routing to routes like `/s4/s6` as expected.

But, if the child navigator is put in another component like `S4: {screen: props => <Nav1 {...props} />, path: 's4'}`, the route `/s4/s6` no longer works. What am I missing?

The use case for the above mentioned scenario could be the utilization of deep linking while using `redux` alongside. My perception of Redux integration with React Navigation is,

- A `navigation` prop should be passed to the top level navigator [[1](https://reactnavigation.org/docs/guides/redux#Redux-Integration)].
- On the other side, deep linking requires `containerOptions` (a navigator config) to be passed to the top level navigator in order to set `URIPrefix` [[2](https://reactnavigation.org/docs/guides/linking)].
- But, the [documentation](https://reactnavigation.org/docs/navigators/#containerOptions) also forbids to pass `navigation` prop to a navigator when it is already configured with `containerOptions`.

I'm really stuck at this point. Cause, according to my perception, if top level navigator is configured with `containerOptions`, `navigation` prop must be passed to a child navigator. But, this arises the very first issue that I mentioned.

Here is another [identical issue](http://stackoverflow.com/questions/43544589/react-navigation-utilizing-deep-linking-with-redux).

**Comment by lwansbrough** [comment]
This is a really important aspect of routing once you get out of the most common cases. You need to be able to define intermediary components for a wide range of tasks. The most obvious one I can think of (because it's what I'm struggling with) is the ability to define routes on the fly.

Consider that I have a TabNavigator, but in my case the routes are categories that are maintained server-side.

The most logical approach would be to create a component `<CategoryTabNav>` which fetches that data, and generates the TabNavigator inside its render method after the data has been returned.

Now, looking at the code for react-navigation, I can start to see why this would become an issue. In order to be able to correctly route to a page, you have to know what routes are available. If all of your routes are generated dynamically, you need to evaluate each component for its output before you know what routes it exposes. This is obviously a no-go for performance, and so react-navigation instead elects to make the router a static property on each navigator which is configured at runtime. But this is a pretty serious limitation.

If I'm understanding this code correctly, no routes can be generated dynamically, and as such any routing that depends on dynamic factors has to be done manually (thus breaking the chain of deep linking.)

In this case I'd like to propose a solution: allow for a standard component to handle routing at an arbitrary path depth, then return navigation control to a child navigator. Here's an example of what I mean:

```javascript
// If the deep link is <store/category/123/products/456> and
// it doesn't find any matches amongst the static routes, it should try incrementally removing
// pieces of the path. So it would start with <store/category/123/products>, and find nothing.
// Then it would try <store/category/123> and it would find a static route that matches. It checks a static property `router.hasDynamicRoutes`. If it does, it will navigate to that route.
// So now the router is at <store/category/:categoryId> but it has a final destination of
// <store/category/:categoryId/products/:productId> -- for now the router's job is done. Because of `router.hasDynamicRoutes` it can assume the component is doing work to provide the next action for the router. The component might have a lifecycle callback like this:

...
async componentWillMount() {
  const routeConfig = await someAsyncActionToFetchRouteConfig()
  const { matchingRoute, params } = await this.props.navigation.evalutateRoutes(routeConfig)
  // At this point the router's state still hasn't changed, but our component now understands where the navigation needs to be lead. So we can continue rendering...
  const Screen = await this.props.navigation.continueWithScreen(matchingRoute.screen)
  // continueWithScreen allows the router to continue routing using matchingRoute.screen.
  // That means if matchingRoute.screen is a TabNavigator itself, the router now has new routes to match against, and can restart its search with those newly added routes.
 // Of course this means that we know those new routes will be children of the current component, so we need to render the result of whatever recursion happens:
  this.setState({ Screen })
}
...
// Now we have a screen to render
...
render() {
  const { Screen } = this.state
  return (
    <View>
      <Screen />
    </View>
  )
}
```

It's not totally clean as an API, but I believe it would allow us to accomplish arbitrarily complex routing.

**Comment by cgadea** [comment]
I'm having the same issue. Here's my setup:

```
const TopLevelNav = TabNavigator({
  ...
  Profile: {
    screen: ProfileContainer,
    path: 'profile',
  },
  S2: {...},
  S3: {...},
});
...

ProfileNavigator = StackNavigator({
  Foo: {
    screen: FooView,
    path: 'foo',
  },
});

class ProfileContainer extends Component {
  render() {
    return <ProfileNavigator screenProps={...} />;
  }
}
```

Opening `myapp://profile` takes me to the Profile screen, but `myapp://profile/foo` does not take me to the Foo screen, it just stops at the Profile screen.

The use-case here is two-part:
1) I have state and helper functions that I need to pass to the screens within the Profile tab 
2) I don't want to pass that state and helper functions to all of the screens in my app.

**Comment by onlydave** [comment]
@cgadea add change ProfileContainer to

```
class ProfileContainer extends Component {
  static router = StackRouter({
    Foo: {
      screen: FooView,
      path: 'foo',
    },
  })

  render() {
    return <ProfileNavigator screenProps={...} />;
  }
}
```

My new problem is how to get it working where the path for profile is something like `path: 'profile:userId'`. In that case `myapp://profile/123/foo` will work, but `myapp://profile/123` wont anymore

**Comment by cgadea** [comment]
@onlydave Thanks for the suggestion! I'm sorry if I'm missing here, but where/how is `ProfileNavigator` defined in this case?

**Comment by onlydave** [comment]
sorry @cgadea , as you had it before. You're just passing the router through as a static value so the parent navigator knows about it

```
const TopLevelNav = TabNavigator({
  ...
  Profile: {
    screen: ProfileContainer,
    path: 'profile',
  },
  S2: {...},
  S3: {...},
});
...

ProfileNavigator = StackNavigator({
  Foo: {
    screen: FooView,
    path: 'foo',
  },
});

class ProfileContainer extends Component {
  static router = StackRouter({
    Foo: {
      screen: FooView,
      path: 'foo',
    },
  })

  render() {
    return <ProfileNavigator screenProps={...} />;
  }
}
```

**Comment by onlydave** [comment]
sorry, also forgot to add ProfileNavigator will need `navigation={this.props.navigation}` too

**Comment by cgadea** [comment]
@onlydave Aha, thanks so much, that last part seems to have fixed it for me. :D 

Two questions:
1) Is there a preferred way to avoid having my screens defined in two places (both in the router and in the navigator)? I'm not sure what the repercussions would be if those two definitions every got out of sync.
2) Were you able to figure all of this out from the documentation? I read through it but it wasn't clear to me how to make a really basic custom router.

**Comment by onlydave** [comment]
@cgadea mix of documentation and source code.

I've just saved my routes in a variable that's imported. In another place I've created a componenet that returns TabView instead of a full navigator. This way you're not doubling up on routers, not sure it makes much of a difference though

**Comment by phamtn8** [comment]
This seems like a short-coming. Can we have event listener like below

`componentDidMount(){
    if (Platform.OS === 'android') {
      Linking.getInitialURL().then(url => {
        this.navigate(url);
      });
    } else {
      Linking.addEventListener('url', this.handleOpenURL);
    }
  }
  handleOpenURL = (event) => {
    this.navigate(event.url);
  }
  navigate(url){
      if(logic to parse url){
          navigate("SomeWhere")
      }
  }
`
This is a cleaner solutions

**Comment by kelset** [comment]
Pinging OP @atshakil since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @atshakil ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.
