### ISSUE TITLE
Expect nav state to have routes and index, {"key":"InitB","routeName":"Main"}  

### ISSUE THREAD

**Issue by guoliang1206** [react-community/react-navigation#1111]
I want custom the navigator with redux, and I imitate the ReduxExample,

this is navigatorConfig:

```
import LoginScreen from './Login';
import Map from './Maps';

const MainScreen = TabNavigator({
    Maps:{ screen: Map},
});

export const AppNavigator = StackNavigator(
    {
        Login: { screen: LoginScreen },
        Main: { screen: MainScreen },
    },
    {
        headerMode:'screen',
    }
);
```

This is reducer config ,
```
const initialNavState = {
    index: 0,
    routes: [
        { key: 'InitA', routeName: 'Login' },
        { key: 'InitB', routeName: 'Main' },
    ],
};

const initialAuthState = { isLoggedIn: false };

function nav(state = initialNavState, action) {
    switch (action.type) {
        case LOGIN:{
            console.log('excute login operator');
            return AppNavigator.router.getStateForAction(NavigationActions.navigate({ routeName: 'Main' }), state);
        }
        case LOGOUT:
            return initialNavState;
        default:
            return initialNavState;
    }
}
```
and then run it, show the error "Expect nav state to have routes and index, {"key":"InitB","routeName":"Main"}",
 
Is it exist some problem in nested navigator?

**Comment by guoliang1206** [comment]
and if I changed  like this `Main: { screen: Map },` it don't show the error message.

**Comment by jcaspian** [comment]
I think you should generate the initialState instead of writing it manually.
`const initialState = AppNavigator.router.getStateForAction(AppNavigator.router.getActionForPathAndParams('Main'))`

**Comment by guoliang1206** [comment]
@jcaspian Thanks for your help. It is a clearly answer.

**Comment by skiral** [comment]
@jcaspian do you know what is the solution to do it programmatically.
I am having the same problem.
the below code just return the state for Main, how can we add the state for Maps in it?

```
const initialState = AppNavigator.router.getStateForAction(AppNavigator.router.getActionForPathAndParams('Main'))
```

**Comment by jcaspian** [comment]
What do you mean by programmatically?

You should be able to generate the `initialState` with that line of code.
If your Maps component state is not generated, it could be due to the middle wrapping component.

Assuming that you have the components nesting as follows:

    AppNavigator
      + Home Screen // normal stateless component
      + Maps Screen // normal stateless component, also the "wrapper" component
        - MapsNavigator
          + Maps View Screen // normal stateless component
          + Saved Location Screen // normal stateless component

You'll need to write the code as follows:

    const HomeScreen = ({ navigation }) => (
      <View>
        <Text>Welcome to Home Screen</Text>
        <Button
          onPress={() => navigation.navigate('Maps')}
        >
          Open the Map
        </Button>
      </View>
    )

    const MapsScreen = ({ navigation }) => (
      <View>
        <Text>Maps Screen</Text>
        <MapsNavigator navigation={navigation} />
      </View>
    )

    const MapsViewScreen = () => (
      <View>
        <Text>Render the map here</Text>
      </View>
    )

    const SavedLocationsScreen = () => (
      <View>
        <Text>List of saved locations</Text>
      </View>
    )

    const MapsNavigator = TabNavigator({
      MapsView: { screen: MapsViewScreen },
      SavedLocations: { screen: SavedLocationsScreen },
    })
    
    MapsScreen.router = MapsNavigator.router

    const AppNavigator = StackNavigator({
      Home: { screen: HomeScreen },
      Maps: { screen: MapsScreen },
    })

We have a wrapper component called `MapsScreen` between the StackNavigator and TabNavigator.

Notice the line `<MapsNavigator navigation={navigation} />`.
This is telling the TabNavigator to inherit the `navigation` prop from StackNavigator.

As for the line `MapsScreen.router = MapsNavigator.router`, we are passing the MapsNavigator's routes (`MapsView` and `SavedLocations`) to the parent navigator `AppNavigator`, so that it can recognize & initialize the navigation state etc.

If we don't really need the `MapsScreen` wrapper component, we can write a much simple code.

    AppNavigator
      + Home Screen // normal stateless component
      - MapsNavigator
        + Maps View Screen // normal stateless component
        + Saved Location Screen // normal stateless component

Our new code will be much shorter, and looks almost identical to the documentation from react-navigation.

    const HomeScreen = ({ navigation }) => (
      <View>
        <Text>Welcome to Home Screen</Text>
        <Button
          onPress={() => navigation.navigate('Maps')}
        >
          Open the Map
        </Button>
      </View>
    )

    const MapsViewScreen = () => (
      <View>
        <Text>Render the map here</Text>
      </View>
    )

    const SavedLocationsScreen = () => (
      <View>
        <Text>List of saved locations</Text>
      </View>
    )

    const MapsNavigator = TabNavigator({
      MapsView: { screen: MapsViewScreen },
      SavedLocations: { screen: SavedLocationsScreen },
    })

    const AppNavigator = StackNavigator({
      Home: { screen: HomeScreen },
      Maps: { screen: MapsNavigator },
    })

With this code, react-navigation can automatically pass the MapsNavigator's router to AppNavigator, and also AppNavigator will automatically set the navigation state of MapsNavigator.

* Please note that the codes above are not tested. They are based on my previous experience with an older version of react-navigation. Do try and see if it solves your problem as currently I am not using the "wrapping component" for the navigators.

**Comment by Fsarmento** [comment]
I had the same problem and it only worked for me after initializing the appNavigator as shown in [ssue 1919](https://github.com/react-navigation/react-navigation/issues/1919)


```

import { NavigationActions } from "react-navigation";
import AppNavigator from "../AppNavigator";

//Force a Init of the main router
let initialNavState = AppNavigator.router.getStateForAction(
  NavigationActions.init()
);

const firstAction = AppNavigator.router.getActionForPathAndParams("Main");

//Then calculate the state with a navigate action to the first route, sending the previous initialized state as argument
initialNavState = AppNavigator.router.getStateForAction(
  firstAction,
  initialNavState
);
```

However, dispatch is not passed down to the sub-routes components (the equivalent to MapsViewScreen and SavedLocationsScreen on the example above). The navigation object has the state, the navigation functions (navigate, goBack) but dispatch is undefined. Therefore, if I try to navigate using navigation.navigate('Maps')}, I get an error because it uses dispatch and dispatch is undefined. Any clue?
