### ISSUE TITLE
Overlapped stacked scenes when using Transitioner too quickly

### ISSUE THREAD

**Issue by sreucherand** [react-community/react-navigation#1162]
Hi,

I'm experiencing an issue when doing a custom animation using `Transitioner`. Let's take the following example:

Consider 3 screens, A, B and C. A has pushed B. So the current stack contains 2 screens. If I go back to A and instantly, push C, then it appears that because B is not removed yet, B shows up quickly behind C before being removed.

Here is a video of the effect: https://youtu.be/13-TbPga5iA.
Here is the code: https://gist.github.com/sreucherand/28481b8f7f9db6483cca3b561e3d8126

Does anyone know how to solve that?

Thx! 🙂

**Comment by santiagopoli** [comment]
You can debounce the navigate method with lodash:

```javascript
import { debounce } from 'lodash';

...

this.props.navigation.navigate = debounce(
    this.props.navigation.navigate, 1000, { trailing: false, leading: true }
);
```

**Comment by ericvicenti** [comment]
I think this is a real issue. It would be great to make sure `Transitioner` knows how to queue up transitions, which is something CardStack is getting better at

**Comment by kelset** [comment]
Pinging OP @sreucherand since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @sreucherand,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
