### ISSUE TITLE
Back image blocked when other images are loading

### ISSUE THREAD

**Issue by jaygarcia** [react-community/react-navigation#1164]
I was looking at the source and found that HeaderBackButton.js leverages an Image for the left chevron, which causes a blocking effect when images are loading while a transition request occurs.

Block in question
```
<Image
            style={[
              styles.icon,
              title && styles.iconWithTitle,
              { tintColor },
            ]}
            source={require('./assets/back-icon.png')}
          />
```
Demo: Notice the delay
![as image](https://cloud.githubusercontent.com/assets/180031/25290518/6f1da9a0-269c-11e7-89a2-41ac8ac31759.gif)

Quick experiment (not as flexible, but shows how much improved the interaction is with using a font.
```
          <Ionicons name='ios-arrow-back' size={32} style={{width:16, color:'#777', paddingTop:10}}/>
```
Demo: We can see that blocking is not an issue anymore
![as font](https://cloud.githubusercontent.com/assets/180031/25290514/6a554c3e-269c-11e7-8380-cc6ea14e24ef.gif)

**Comment by grabbou** [comment]
Nice! We probably don't want to use vector-icons for the button itself, but I guess moving `require` out of `render` to happen on first run would help?

**Comment by ms88privat** [comment]
@grabbou Why do we prefer an Image over an icon? Just asking.

**Comment by grabbou** [comment]
I don't think there's any preference here. In context of React Native, I believe `image` is easier to use than loading a fully-fledged library for handling icons. 

Having `svg` in a separate file would be loaded in the same way.

**Comment by gregblass** [comment]
I'm experiencing this with no other images on the screen at all.

**Comment by gregblass** [comment]
Any suggested workaround or solution here? Is it because the other images are loading first, before the back button?

I wonder if there was a way to specify the loading order of the images. You'd think that because the image is cached/already loaded that it would show up immediately.

Or is there a way to override the back button to use an icon for the entire stacknavigator options?

**Comment by gregblass** [comment]
Or, is there any place you'd recommend moving the image require to? Could we cache it somewhere globally?

**Comment by Elijen** [comment]
This is kind of ruining the native experience. Is there a known workaround for this issue?

**Comment by kelset** [comment]
Pinging OP @jaygarcia since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

Btw, may be related to https://github.com/react-community/react-navigation/pull/2520 ?

**Comment by kelset** [comment]
Hi there @jaygarcia  , 

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.

**Comment by yatessss** [comment]
not only back image, if first page loading image timeout, can block second page load image
