### ISSUE TITLE
How to config custom DrawerNavigator DrawerItems with ScrollView

### ISSUE THREAD

**Issue by zhenliliu** [react-community/react-navigation#1166]

**Comment by nico1510** [comment]
```javascript
import { DrawerNavigator, DrawerView } from 'react-navigation';

const contentComponent = (props) => (
    <ScrollView>
        <DrawerView.Items {...props} />
    </ScrollView>
);

const navigator = DrawerNavigator(routeConfig, {
    ...
    contentComponent,
    ...
});
```

Please close don't forget to close this issue if this solution solves your problem.

**Comment by jdeniau** [comment]
Had the same problem, and your proposition fixed the issue.

The fact is the https://reactnavigation.org website is based upon the master branch, thus said to use `DrawerItems`, but this is due to #1219 which append after the latest beta release (beta.8).

Maybe it is just a matter of days before the 1.0 stable is released, but if not, and if it's easy to do, the website should use the latest release tag.

**Comment by nico1510** [comment]
Yes this is being discussed already https://github.com/react-community/react-navigation/issues/1060

**Comment by zhenliliu** [comment]
Ok,thanks

**Comment by kakulgupta** [comment]
Check out https://medium.com/@kakul.gupta009/custom-drawer-using-react-navigation-80abbab489f7. Hoping it helps in figuring out how to customise the drawer navigator.
