### ISSUE TITLE
static navigationOptions header called around 50 times

### ISSUE THREAD

**Issue by RWOverdijk** [react-community/react-navigation#1182]
I'm on the latest version, and I have a boilerplate (from the docs) redux implementation Stack navigator set up.

I have a simple component:

```jsx
class ActivityFilter extends React.Component {

  static navigationOptions = {
    title : I18n.t('activity.Activities'),
    header: (navigation, header) => {
      console.log(navigation);
      return {
        ...header,
        title: I18n.t('Filters'),
        right: <Icon name="check" iconStyle={styles.checkIcon}/>,
        left : null
      };
    }
  };

  /* rest ... */
}
```

`navigation` gets logged around 40 - 50 times upon navigating to it. Perhaps relevant to mention, is that the source screen also has an icon on the right. When I add the `onPress` attribute, it doesn't navigate at all. Something with these options is going wrong (or, more likely, I'm doing something wrong).

**Comment by grabbou** [comment]
This is a normal behaviour - we do not perform any caching here - we call `getDetails` as many times as we need. 

With `latest` version (marked as v8, but a bit unstable for now), we have flat options, that is, instead of `header.title`, you declare `headerTitle` which should reduce the amount of calls.

Changelog is coming soon.

I believe if that becomes a performance bottleneck in the future, we would be up to accepting a PR that works on that.

**Comment by RWOverdijk** [comment]
Oh, alright. Thanks.
