### ISSUE TITLE
StackNavigator iOS animates opacity; iOS default does not

### ISSUE THREAD

**Issue by pietropizzi** [react-community/react-navigation#1256]
### Current Behavior

When going back on the StackNavigator the bottom screen's opacity fades in.

### Expected Behavior

Native iOS apps do not fade in opacity, they only translate the bottom screen. I would expect the default implementation to do the same.

I realize that you can override the `transitionConfig` but it seems off to me that I would have to override it to get platform default. Overriding it is also not exactly trivial.

**Comment by systemride** [comment]
I was able to resolve this by setting the cardStyle opacity like so:
```
const navigatorConfig = {
  cardStyle: { opacity: 1 },
}
const Navigator = StackNavigator(routes, navigatorConfig);
```

**Comment by kelset** [comment]
Pinging OP @pietropizzi since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @pietropizzi , 

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.
