### ISSUE TITLE
Deep links with params do not resolve

### ISSUE THREAD

**Issue by imranolas** [react-community/react-navigation#1284]
### Current Behavior
When setting deep links that should resolve with params, the path does not match and params are not identified.

### Expected Behavior
As per the docs. I would expect `mychat://chat/Taylor` to trigger the Chat route.
```js
const SimpleApp = StackNavigator({
  Home: { screen: HomeScreen },
  Chat: {
    screen: ChatScreen,
    path: 'chat/:user',
  },
});

const prefix = Platform.OS == 'android' ? 'mychat://mychat/' : 'mychat://';

const MainApp = () => <SimpleApp uriPrefix={prefix} />;
```

The issue exists due to params not being handled here. https://github.com/react-community/react-navigation/blob/a14ac29c303094eddedc809a351ea421fdde993e/src/createNavigationContainer.js#L96
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.7
| react-native     |  0.43
| node             | 7.9.0
| npm or yarn      | yarn

**Comment by spencercarli** [comment]
@imranolas sorry for the delay - do you know if this is still an issue with a current version of the package?

**Comment by kelset** [comment]
Hi there @imranolas ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.
