### ISSUE TITLE
redux: Nested navigation back button

### ISSUE THREAD

**Issue by RWOverdijk** [react-community/react-navigation#1349]
On Android, it's possible to capture the (physical) back button. What I did with the StackNavigator, was get the index. If the index was 0, I'd return false, to tell android it's okay to suspend the app and otherwise navigate (goBack).

Now, I have a drawerNavigator, with two nested StackNavigators. The index no longer changes (it caches the pages now it seems). How should I decide if I should go back? How does react navigation do it? I want the same behavior as the "back" button in the navbar. When it's visible I want to call goBack, otherwise I want the app to suspend.

**Update** To make it even more interesting (but perhaps this deserves its own ticket) when I trigger a Navigate back, _all_ routers seem to handle it. So it navigates to the wrong screen.

**Comment by chpill** [comment]
I have the exact same question. 

To know if a `back` action would change the navigation state, I tried to do something like `myNavigator.router.getStateForAction(NavigationActions.back())` and then do a deep equal with the current navigation state but it does not work as there are keys with value `null` in the current state (like `type: null`)... I guess one could recursively compare the `routeName` and `index` values of the 2 trees, but surely, it is something react-navigation already does and could expose in some way?

**Comment by RWOverdijk** [comment]
@chpill I was thinking about the same approach, but it seems a bit hacky. So 👍

**Comment by RUIFERNANDE5** [comment]
Well, I've tried the simple aproach of checking the nav index in Multiple scenes, however if I go to a nested route and go back to the first scene the eventListener gets overwritten by the nested eventListener since the back action does not Unmount the scene. 

If you find any good implementation to check when to exit the app that works with deep nested give me a hint.

**Comment by kelset** [comment]
Hi guys, 
Starting from the point made by @RWOverdijk when he says
> To make it even more interesting (but perhaps this deserves its own ticket) when I trigger a Navigate back, all routers seem to handle it. So it navigates to the wrong screen.

(which I can confirm, happens to me too)
I tried to go for an approach which I think may provide you guys with a "possible solution", or at least something to start from to implement your own :)

What I did was actually "hijack" the "reaction" to the `Navigate/Back` action. It's probably not the best way, but hey it works - let's consider a situation with `Nav1` containing `Nav2`:

1. In the component 'root', I have the handler set up this way:

```
    BackAndroid.addEventListener('backPress', () => {
      const { navigationState, navigation } = this.props;
      if (navigationState.index === 0) return false;
      navigation.dispatch({ ...NavigationActions.back(), physical: true });
      return true;
    });
```

2. I defined the reducer for `Nav1` in order to change the behaviour when the physical back is received:

```
export const Nav1Reducer = (state, action) => {
  if (action.type === 'Navigation/BACK'
      && action.physical) {
    return state;
  }
  return Nav1.router.getStateForAction(action, state) || state;
};

```

So I can "prevent" `Nav1` from reacting to the physical back, while instead `Nav2` will do the standard back action.

Hope it helps!

**Comment by RWOverdijk** [comment]
@kelset This is the issue! I couldn't find it to report back, my bad.

The issue was that I needed to handle only one router. The drawer handled navigation for all routers inside of it. The fix is as easy as removing all other routers handlers (reducers), and only keeping the top one.

Long story short, the single, top-most reducer handles all routing.

**Comment by raphaelvigee** [comment]
For all the people who where wondering how to make the back hardware button to act properly, here is my implementation, (**I'm open to enhancements :)**):

```
  handleBackPress() {
    if(this.isRootScreen(this.state.nav)) return false;

    this.props.dispatch(NavigationActions.back());

    return true;
  };

  isRootScreen(navigator) {
    if(typeof navigator.index == 'undefined') return true;

    let isCurrentRoot = navigator.index == 0;

    if(navigator.routes && !_.isEmpty(navigator.routes)) {
      let allChildAreRoots = true;

      navigator.routes.map((r) => {
        if(allChildAreRoots) {
          if(!this.isRootScreen(r)) {
            allChildAreRoots = false;
          }
        }
      });

      return allChildAreRoots && isCurrentRoot;
    }

    return isCurrentRoot;
  }

  componentDidMount() {
    this.backAndroid = BackAndroid.addEventListener('hardwareBackPress', this.handleBackPress);
  }

  componentWillUnmount() {
    this.backAndroid && this.backAndroid.remove();
  }
```

**Comment by RWOverdijk** [comment]
@raphaelvigee Thanks for the workaround. It feels a bit much for the feature, so I hope we'll get a better solution soon. If I have time later this week I'll try and dig for a solution.

**Comment by RUIFERNANDE5** [comment]
@raphaelvigee I'm getting a `subscriptions[i] is not a function` error. Any clue?

**Comment by raphaelvigee** [comment]
@RWOverdijk Yeah I know, but it's the _simplest_ way I've found, feel free to enhance it ! I think this feature should be included in the core

@RUIFERNANDE5 No clue, seems related to RN since the `BackAndroid.android.js` is part of the RN core.

**Comment by RWOverdijk** [comment]
FYI BackAndroid has been deprecated.

**Comment by raphaelvigee** [comment]
Oh yes, but my project is still on 0.43, so no problem for now. But my workaround still works, just replace `BackAndroid` with `BackHandler`

**Comment by raphaelvigee** [comment]
I managed to shorten it using _magic_ lodash:

```
  isRootScreen(navigator) {
    if (typeof navigator.index == 'undefined') return true;

    let isCurrentRoot = navigator.index == 0;

    if (navigator.routes && !_.isEmpty(navigator.routes)) {
      return _.every(navigator.routes, (r) => this.isRootScreen(r)) && isCurrentRoot;
    }

    return isCurrentRoot;
  }
```

**Comment by oallouch** [comment]
or with vanilla JavaScript:
```
function isRootScreen(navigator) {
	if (navigator.index == null) {
		return true;
	}

	if (navigator.index > 0) {
		return false;
	}

	return !navigator.routes || !navigator.routes.find(route => !isRootScreen(route));
}
```

**Comment by lxcid** [comment]
Many of the solution here and in #117 didn't help me. I was digging the codebase and figured out that when you provides your own `navigation` to the Navigator, [the Navigator will no longer subscribe to back button because it is no longer stateful](https://github.com/react-community/react-navigation/blob/99cd4604b402852765592aa52b00e4d4933518e0/src/createNavigationContainer.js#L150-L152).

My solution is to extends the DrawerNavigator and subscribe it manually, then dispatch the action through redux.

```js
class RootNavigator extends DrawerNavigator(
  {
    AppScreen: { screen: AppNavigator },
  },
  {
    contentComponent: DrawerContent,
  },
) {
  static propTypes = {
    navigation: PropTypes.shape({
      dispatch: PropTypes.func.isRequired,
    }).isRequired,
  };

  componentDidMount() {
    super.componentDidMount();

    this.subs = BackHandler.addEventListener('hardwareBackPress', () =>
      this.props.navigation.dispatch(NavigationActions.back()),
    );
  }
}
```

Hopefully this will help you solve your issue.

**Comment by puguhsudarma** [comment]
@raphaelvigee @oallouch thank you for solution, it work on my project.

**Comment by kelset** [comment]
I think the solutions provided solve the issue - since they were submitted in May and OP didn't write back ;)

Thanks for the suggestion, I'm not sure how a PR could inject this behaviour into the lib (prob easiest way would be an option when you set up the navigator to "mute" the hardware back button behaviour) but yeah feel free to send them over :)

**Comment by chpill** [comment]
@kelset the snippets provided in this thread kind of solve the issue indeed. I am using @oallouch solution (thanks!) and it works fine. But it feels like we are relying on some implementation details that could change (code like `if (navigator.index == null) { return true; }` make me uneasy.

React-navigation already has a way to determine if it should exit the app in this particular case when not using redux. Can't this be exposed to be reused by redux user?

**Comment by kelset** [comment]
I understand your feeling, the lib is currently in a [phase of transition](https://github.com/react-community/react-navigation/issues/2476#issuecomment-325235503) and I'll try to have this method exposed for future releases ;)

**Comment by Morriz** [comment]
yeah, please do, as we are reinventing this wheel...

also, the root's `navigator.index === 0` is always true for those of use using one root navigator. How do we know when to exit the app?

**Comment by mannol** [comment]
@lxcid Thanks mate, that worked for me

**Comment by ckeeney** [comment]
My solution is a little process intensive, but it is reliable and clear.  I prefer this workaround until `redux-navigation` exposes a better API.
I created a redux selector `canGoBack`:

```js
export const canGoBack = (state) => {
  // use the getStateForAction reducer exposed by the root Navigator to get the new state after a back action.
  const stateAfterBack = AppNavigation.router.getStateForAction(NavigationActions.back(), state.nav)
  // I'm using Ramda.equals, any deep equals implementation will probably do.
  return !R.equals(stateAfterBack, state)
}
```

Then from a redux-connected component, `canGoBack` is added as a `prop`:

```js
class Header extends React.Component {
  render () {
   /* 
   ... 
   */
  }

const mapStateToProps = (state) => {
  return {
    canGoBack: canGoBack(state)
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(Header)

```

**Comment by hoscarcito** [comment]
Here's my two cents..
If you have a root navigation and then a drawer, you should have a landing screen where you may want to exit the app. So the function "shouldExit()" must be something like this:

```js
// Routes: RootStack(Authorized) -> AuthorizedDrawer(DrawerClose) -> Profile (Screen)
shouldCloseApp = () => this.props.nav.routes[0].routes[0].index === 0;
```

My navigation configuration is something like this:
RootStack:
-UnauthorizedLogin (screen)
-AuthorizedDrawer

AuthorizedDrawer:
-Profile (screen)
-ChatStack

ChatStack:
-Contacts (screen)
-Conversation (screen)

So if you want to be the contacts (ChatStack) the screen where your app closes, then the shouldClose function should be:

```js
// Routes: RootStack(Authorized) -> AuthorizedDrawer(DrawerClose) -> ChatStack -> Contact(screen)
shouldCloseApp = () => this.props.nav.routes[0].routes[0].routes[0].index === 0;
```

Hope this helps!!!

P.S. I've used nav.routes[0] for the RootStack because I reset the nav after Auth

**Comment by mbret** [comment]
The only real way to check if you can go back is by actually calculate the next state and compare to the current one. The problem is you cannot shallow compare the two state as it may have some difference that are not relevant for the result. We can call it "noise".

So the solution is to deeply compare the index by going through the routes of routes until you reach the end. @oallouch had a good idea but you cannot always compare index to 0 because 0 is not necessarily the last route. If you set the routes at index 3 to be the default route then you have to check against 3 and not 0.  This is a case which appears with tabs and drawer. you can go to route default (3) and then open drawer and go to route (4). You should be able to go back from 4 to 3. 3 being the last route you do not have 0 here! That being said, compare both state only. 

Check this out:

```
const equal = (route, nextRoute) => {
  // not same index ? no need to go further, not equal
  if (route.index !== nextRoute.index) return false
  // no routes ? this is not a navigator, just ignore it. Equal!
  if (!route.routes) return true
  // Loop over each routes and try to find one which is not equal
  return !route.routes.some((r, i) => {
    return !equal(r, nextRoute.routes[i])
  })
}

class BackHandlerContainer extends React.Component {

  onBackPress = () => {
    const currentState = this.props.nav
    const nextState = AppNavigator.router.getStateForAction(NavigationActions.back(), this.props.nav)

    if (equal(currentState, nextState)) {
      return false
    }

    this.props.dispatch(NavigationActions.back())

    return true
  }

  componentDidMount () {
    BackHandler.addEventListener('hardwareBackPress', this.onBackPress)
  }

  componentWillUnmount () {
    BackHandler.removeEventListener('hardwareBackPress', this.onBackPress)
  }

  render () {
    return this.props.children
  }
}
```

**Comment by assafb81** [comment]
@mbret ,
Hi I tried your solution but I encounter a problem.
My main stack looks like this:
```
const mainState = stackNavigator({
  SplshScreen: {screen: splash},
  StackA: {screen: StackAContainer},
  StackB: {screen: StackBContainer},
});
```
When I in my first screen of StackA, clicking on back button:
A. Will navigate back instead of closing the app (no need to go back to splashScreen).
B. The app is stack in a white screen, not even showing the splash screen.

**Comment by assafb81** [comment]
@mbret ,
Hi I tried your solution but I encounter a problem.
My main stack looks like this:
```
const mainState = stackNavigator({
  SplshScreen: {screen: splash},
  StackA: {screen: StackAContainer},
  StackB: {screen: StackBContainer},
});
```
When I am the first screen of **stackA** or **stackB**, clicking on back button:
A. Will navigate back instead of closing the app (no need to go back to splashScreen).
B. The app is stack in a white screen, not even showing the splash screen.

**Comment by mbret** [comment]
Hi @assafb81 

A. What do you mean by no need to ? If SplashScreen is in the stack this is completely normal that pressing back will move you on that screen.
B. This may be related to a bug with your code and the fact hat you are not supposed to go back on splash.

Can you give me more information about how your stack (state) looks like when you want to go back and it should exit the app ?

If you check my code comments there are three different case possible.

Note that your splash screen will always be in your stack if used as first screen (when opening the app). unless you reset the navigation when going to stackA or stackB.

Using:
```if (nextRoute.routes.length === 1) return false; ```
on first line will not works as nextRoute.routes may not exist. Also there is no need to check nextRoute.routes.length as you already check "routes" from "route". If nextRoute is different from route then they are not equals and that's all.

It just looks like you are missing a piece of business logic that should be outside of the scope of my answer.

**Comment by assafb81** [comment]
hi @mbret,
thanks for the quick reply.

my main stack looks like this: 
```
const mainState = stackNavigator({
  SplashScreen: {screen: splash},
  StackA: {screen: StackAContainer}, // stacknavigator with 2 screens
  StackB: {screen: StackBContainer}, // stacknavigator with 3 screens
  StackC: {screen: StackCContainer}, // tabnavigator with 4 tabs
});
```
in my splash screen container I have the following code:
```
componentDidMount() {
  this.props.initializeApp();
}

componentDidUpdate() {
  if (this.props.initialRouteName) {
    this.props.navigation.navigate(this.props.initialRouteName);
  }
  SplashScreen.hide();
}
```
which basically, get the initial route name (if its the 1st screen of stackA or 1st screen of stackB or 1st screen of stackC).

My goal is to close the app when ever I am clicking on the back button of the device when I am one of the 1st screens (of stackA, stackB or stackC).
I want to see my splash screen **only** when the user open the application.

**Comment by mbret** [comment]
I think the white screen comes from the line
```SplashScreen.hide();```

The redirection to SplashCreen comes from the line
```this.props.navigation.navigate(this.props.initialRouteName);```

As I said the problem is that your are not resetting the state.

Considering your code the SplashCreen is the first route in the router stack. You never get rid of this route which means that at some point you will be redirected to this route. So my code is not the problem, if you want to avoid goind back to splash screen and instead exit the app you have two possibilities.

The clean / simplest solution is to reset the state here
```
if (this.props.initialRouteName) {
    this.props.navigation.reset( ... )
}
```

The other solution which I do not recommend is to use specific logic on your ```getStateForAction``` or your ```onBackPress``` functions

**Comment by assafb81** [comment]
I tried your approach: 
```
componentDidMount() {
  this.props.initializeApp();
}

componentDidUpdate() {
  if (this.props.initialRouteName) {
    // this.props.navigation.navigate(this.props.initialRouteName);
    const resetAction = NavigationActions.reset({
      index: 0,
      actions: [
        NavigationActions.navigate({ routeName: this.props.initialRouteName }),
      ],
    });  
    this.props.navigation.dispatch(resetAction);
  }
  SplashScreen.hide();
}
```

the application closes/exist, but when trying to re-open (when application is in the background and not closed) the `componentDidMount` is never called.

**Comment by mbret** [comment]
@assafb81 I'm pretty sure you issue is outside of this scope and belongs to your own business logic.

However I guess we can still help you here :)

When you exit the app with back press the app is not really shut down, it's only closed. It means that when you first opened the app and navigated with reset, the splash creen is not in your stack anymore. Later if you exit the app with back press and you go back the splashcreen will never be called again as it does not exist in your stack at all. This is the last component your were on which is mounted.

Some example:

open ->  splash -- (reset) -> route A (compA) --> route B (compB)
A & B are on your state only. compA is mounted, compB is mounted

route B -- (navigate) -> route A
A is on your state only, compB is unmounted, compA is displayed (wa already mounted, nothing happens)

route A -- (back press) -> app exit
A is still on your state, compA is unmounted, app is closed

go back to app
A is on the state, compA is mounted, app is shown.

I hope this is more clear for you :)

**Comment by assafb81** [comment]
@mbret Thanks for the inputs.
I see now that I am actually rendering screenA, as you described in the scenario above.

If I understand correctly screenA should be responsible to hide the splash screen that the application is displaying after the application is re- launch?

**Comment by mbret** [comment]
@assafb81 If you remove the splash from your state with a reset() you do not have splash screen when application relaunch anymore. 
ScreenA should not be responsible of something outside of this scope. Splash creen is hidden when you leave it the first time and reset the nav to screenWhatever

**Comment by assafb81** [comment]
@mbret 

my scenario is as follows:
open -> splash -> (reset in `splashContainer`) -> routeA (compA) -> (back press) -> app exit.

open -> I see splash screen **BUT** splash I don't reach `splashContainer` instead I reach compA:
two options:
1. if I don't use splash.hide() than the app is stack in the splash screen.
2. if use splash.hide() the app continue as plan

**Comment by seahorsepip** [comment]
Sorry for reopening this but I thought I would share the following snippet for people that have multiple nested navigators and want to close the screen on back button on specific screens:

```
    onBackPress() {
        console.warn(this.getCurrentRoute(this.props.navigation));

        //Get current route as url and check if it's one of the routes that should close the app
        switch (this.getCurrentRoute(this.props.navigation)) {
            case 'Close/When/On/This/Route':
            case 'Also/This/Route':
                return false;
        }

        this.props.dispatch(NavigationActions.back());

        return true;
    };

    getCurrentRoute = (navigation) => {
        const route = (name, state) => {
            if (state.index !== undefined) return route(state.routeName, state.routes[state.index]);
            return `${name}/${state.routeName}`;
        };
        return route('', navigation)
    };

    componentDidMount() {
        BackHandler.addEventListener("hardwareBackPress", this.onBackPress.bind(this));
    }

    componentWillUnmount() {
        BackHandler.removeEventListener("hardwareBackPress", this.onBackPress.bind(this));
    }
```

Original (Modified) route code from: https://github.com/react-navigation/react-navigation/issues/962#issuecomment-321761053

**Comment by brentvatne** [comment]
anyone here want to open a rfc to discuss solutions to this problem? https://github.com/react-navigation/rfcs
