### ISSUE TITLE
Show Stateless DrawerNavigator as 'Open'

### ISSUE THREAD

**Issue by frankiesardo** [react-community/react-navigation#1350]
### Current Behavior

The state managed by a `DrawerNavigator` looks more o less like the following:
```javascript
{ index: 0,
  routes: [
    { index: 0,
      key: "DrawerClose",
      routeName: "DrawerClose",
      routes: [
        { key: "Home",
          routeName: "Home" },
        { key: "Notifications",
          routeName: "Notifications" } ] },
    { key: "DrawerOpen",
      routeName: "DrawerOpen" } ] }
```
If I set `index: 1`(pointing to the "DrawerOpen" route) I expect the drawer to be displayed as open. Instead it remains closed. This also happens if I swap the order "DrawerClose" and "DrawerOpen" in the array. 

Note that the events generated by the navigation are correct (if the index is set to "DrawerClose" it will fire "DrawerOpen" when open accordingly, and vice versa), this is just a matter of not being able to open the drawer by setting its managed state.

Example: https://snack.expo.io/BkBQqWPJb

### Expected Behavior

Setting the index to point to "DrawerOpen" should display the drawer in an open state.

### Links

Issues that might look like related but didn't help me solve this problem #1041
Relevant part of the codebase https://github.com/react-community/react-navigation/blob/c39dd9d45f60ceebe369750eba0e265aed7290f0/src/views/Drawer/DrawerView.js#L50-L62

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  15

Tested on expo, simulator, and device.

**Comment by frankiesardo** [comment]
To be clear, this behaviour is necessary to implement a stateless DrawerNavigator.

Whenever I receive an event of the type `navigate DrawerOpen` I would like to change the state representation so that the DrawerNavigator renders correctly. Passing new props with the index set to point to DrawerOpen should be enough to trigger the change in display in the navigator (similarly to what happens when you change the index of the screen)

In this example I created a managed state DrawerNavigator. The state of the screen gets updated correctly but there's no way to manage the state of the drawer itself: https://snack.expo.io/SysvOpkxb

**Comment by kelset** [comment]
Pinging OP @frankiesardo since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

Moreover, a lot has been added to Drawer in the latest releases and more will be added in next release (`beta.16`) (you can try some of them now by pointing your project to master).

**Comment by kelset** [comment]
Hi there @frankiesardo,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.
