### ISSUE TITLE
Confusing docs: back()

### ISSUE THREAD

**Issue by npomfret** [react-community/react-navigation#1355]
Could we get some clarification on https://reactnavigation.org/docs/navigators/navigation-actions#Back ?

> key - string or null - optional - If set, navigation will go back from the given key. If null, navigation will go back anywhere.

What does it mean to "go back from the given key"?  I was under the impression you "go back" from your current screen? 

Also, what does "go back anywhere" mean?

**Comment by zhaiyjgithub** [comment]
same issue.

**Comment by kelset** [comment]
Pinging OP @npomfret since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

Moreover, PR #2834 should solve this.

**Comment by kelset** [comment]
Hi there @npomfret,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.
