### ISSUE TITLE
How can change header content dynamically?

### ISSUE THREAD

**Issue by MrErHu** [react-community/react-navigation#1403]
The content of Header (eg.title) is assigned by like:
```js
static navigationOptions = (navigation) => {
        return {
            title: '首页'
            />
        }
    }
```
if the content of the title comes from redux, how I can achieve this?
Sorry for my poor english

**Comment by FullstackJack** [comment]
Use `navigation.setParams()` from the component lifecycle methods or an event callback. This may trigger a re-render. Set your title in the `navigationOptions` to `navigation.state.params.title`. Unfortunately if this title change is as a result of an API call, it will be slow to update, would be better if you knew the title ahead of time.

**Comment by koenpunt** [comment]
You can set params in the `navigate()` call, which then can be used in the header. An example of this can be found here: https://reactnavigation.org/docs/navigators/stack#RouteConfigs

**Comment by MrErHu** [comment]
@koenpunt if first screen is Container Component and it‘s title comes from redux, Does it mean I must use `navigation.setParams()` in lifecycle method and may trigger re-render.

**Comment by FullstackJack** [comment]
Since you can't add the title in the `navigate()` call, I might suggest adding a new screen called LoadingScreen. This could display a loading status, infinite spinner, logo, etc until the Redux store updates. Upon componentWillReceiveProps() with your hydrated store, you could `navigate()` to your next screen with title param and populate the page with the loaded state.

**Comment by FullstackJack** [comment]
I was thinking about how to handle this myself since my first screen has a few fetches and lots of images to load. I think a loading screen or splash logo is an acceptable solution for a first screen. Doesn't have to be fancy. Perhaps a color background with the App name in big bold text. Your total number of API calls and data will dictate the type ofbloading screen you can show.

**Comment by MrErHu** [comment]
@FullstackJack The answer is useful in most of scene and can solve my solution thought it bypass the core of problem.I don’t know why react-navigation designed the navigationOptions as a static function.In my view, if in lifecycle method react-navigation provide us interface(or callback),we may not face this problem

**Comment by bodhi** [comment]
I have a similar problem with i18n of titles. We are using [yahoo/react-intl](https://github.com/yahoo/react-intl) which passes the i18n machinery via React's context. They provide components that abstract this away.

But there's no way to access the context from `navigationOptions`, so I can't get at the `intl` object to set the title as a string. I've got most of the way there with this:

```
navigationOptions: () => ({
  headerTitle: <FormattedMessage id="title" />
})
```

But then I lose out on all the features that the default header provides, like the default text styling and the width adjustment: https://github.com/react-community/react-navigation/blob/ff99d6ec0a2d7a62adfd8d1e6a3c906fcedf294a/src/views/Header.js#L87-L113:

![screen shot 2017-05-11 at 5 50 03 pm](https://cloud.githubusercontent.com/assets/28731/25938377/4d59802e-3672-11e7-9225-b314b8e258f4.png)


I have the same problem with tab labels too. The assumption in `Header._renderTitleComponent` – that if `headerTitle` is anything other than a string, then use it instead of `<HeaderTitle>` – is what causes the difficulty. I can remove that check and set `titleString = headerTitle` and my translated text is rendered fine, with all the default styling:

![screen shot 2017-05-11 at 5 49 22 pm](https://cloud.githubusercontent.com/assets/28731/25938382/5308a25c-3672-11e7-8425-fdf298b43900.png)

**Comment by bodhi** [comment]
Ok, so I solved my problem by wrapping the top level navigator in `injectIntl`, and then passing the `intl` object via `screenProps`:

```
const App = injectIntl(({ intl }) => <TopNavigator screenProps={{intl}} />
```

Then `intl` becomes available in `navigationOptions`:

```
class Screen extends Component {
    static navigationOptions = ({ screenProps: { intl }}) => ({
      title: intl.formatMessage({ id: "title" })
  });
  ...
}
```

`screenProps` seem to get passed all the way down through child navigators too.

**Comment by mkozhukharenko** [comment]
@bodhi thanks, that helped!

**Comment by efkan** [comment]
Thanks to **bodhi**'s idea, I use the code following:

```
class AppWithNavigationState extends Component {

    static contextTypes = {
	intl: intlShape
    }

    static propTypes = {
	dispatch: PropTypes.any.isRequired,
	nav: PropTypes.any.isRequired,
    }

    render() {
	let { intl } = this.context
	return (
	    <AppNavigator
		navigation={addNavigationHelpers({
		    dispatch: this.props.dispatch,
		    state: this.props.nav,
                })}
		screenProps={{intl}} 
	    />
	)
    }
}
```

```

const homeScreenStack = StackNavigator(
    {
	home: {
	    screen: Screens.Home,
	},
    },
    {
	navigationOptions: ({ navigation, screenProps }) => {
	    const { intl } = screenProps
            ...
            return { /* navigationOptions object */ 
                title: title: intl.formatMessage(homeScreen.headerTitle)
                ...
            }        
	}
    }
)
```
