### ISSUE TITLE
Conflict with collectionsjs and StackNavigator

### ISSUE THREAD

**Issue by ruqqq** [react-community/react-navigation#1408]
### Current Behavior
If `collectionsjs` is imported, and `StackNavigator` is used, there will be an error stating that `undefined is not an object (evaluation '_ref.routes')`.

Code:
`import SortedArray from 'collections/sorted-array'`

### Expected Behavior
There should be no error and `StackNavigator` should work as per normal.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  0.44.0
| node             |  4.1.2
| yarn      | 0.18.1
| collections | 5.0.6

**Comment by spencercarli** [comment]
Can you provide a reproduction of this?

**Comment by kelset** [comment]
Hi there @ruqqq , 

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.
