### ISSUE TITLE
upgrade to RN 0.44.0 react-navigation Incompatible

### ISSUE THREAD

**Issue by 759325100** [react-community/react-navigation#1413]
I use react-native-git-upgrade to RN 0.44.0.
After the upgrade is complete,run app error
Error infomation:
Objects are not valid as a React child(found:object with keys {visible}).If you meant to render a collection of chhildren,use an array instead.
Check the render method of View

I try to keep track of this problem and find it in react-navigation  

I need wait react-navigation upgrade too?

Hope to get a reply as soon as possible.  
Thank you very much.

**Comment by 759325100** [comment]
@gabriel

**Comment by 759325100** [comment]
@ grabbou

**Comment by 759325100** [comment]
@grabbou

**Comment by snksergio** [comment]
Oops, mine gave this same problem if I upgrade, and on another pc is not happening the same problem being the same files. I totally do not understand. I do not know if it will help, but I removed the properties of the header, and some options of title, right, left, etc ... and rewrote them using the RN's suggestions and funciounou. Example: tabBar {label: "hi"} for tabBarLabel: "hi" ...

**Comment by 759325100** [comment]
thank you @snksergio 
I hope the official can be compatible with RN0.44.0 as soon as possible.
I have rolled the RN version to 0.43.3.

**Comment by Transmuist** [comment]
Hi,
I think this caused by some changes in react-navigation. See the docs here: 
https://github.com/react-community/react-navigation/releases/tag/v1.0.0-beta.9

Here's an example that caused the same issue as yours:
Before:
{
  header: {
    visible: false,
  },
}

Now:
{
   header: null,
}


Hope this helps!

**Comment by Transmuist** [comment]
Hi,
I think this is caused by some changes in react-navigation. See the docs here:
https://github.com/react-community/react-navigation/releases/tag/v1.0.0-beta.9

Here's an example that caused the same issue as yours:
Before:
{
header: {
visible: false,
},
}

Now:
{
header: null,
}

Hope this helps!

**Comment by theohdv** [comment]
Official doc is up to date: https://reactnavigation.org/docs/navigators/navigation-options#Screen-Navigation-Options

```
class ProfileScreen extends React.Component {
  static navigationOptions = ({ navigation, screenProps }) => ({
    title: navigation.state.params.name + "'s Profile!",
    headerRight: <Button color={screenProps.tintColor} {...} />,
  });
  ...
```

**Comment by vahuja13** [comment]
shouldn't a breaking change be a major version upgrade? I'm new to using npm, but my understanding was that a breaking change should be signified via a major version upgrade. The reason I mention this is because I spent the better part of 8 hours trying to figure out what went wrong. 
What's the protocol for introducing breaking changes and/or a way to avoid picking up breaking changes (but at the same time picking up non-breaking updates/upgrades).
