### ISSUE TITLE
[New Feature] Local alert

### ISSUE THREAD

**Issue by Andreyco** [react-community/react-navigation#1453]
`react-navigation` is said to be successor to `ex-navigation`, which offered "local alert" featue. 

Do you plan to support this in `react-navigation` as well?

**Comment by kelset** [comment]
Pinging OP @Andreyco since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

That said, can you describe more/add more details related to this feature you'd like to have?

**Comment by kelset** [comment]
Hi there @Andreyco,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
