### ISSUE TITLE
Navigate event could be fired before DrawerOpen event

### ISSUE THREAD

**Issue by frankiesardo** [react-community/react-navigation#1488]
### Current Behavior

The DrawerOpen event is fired at the end of the animation, when the drawer is fully opened.
If one is quick to click while the drawer is opening it could trigger a navigate event and a DrawerClose event before the DrawerOpen event is fired. This leads to inconsistent behaviours if you're developing a DrawerNavigator with managed state (e.g. Redux)

### Expected Behavior

Possible solutions:
- Fire the DrawerOpen event before the drawer finish the open animation
- Disable the firing of navigate events until DrawerOpen is fired
- Or do nothing and rely on the end user of the library to disable touch input until the drawer is fully open

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  15

### Example

https://snack.expo.io/SysvOpkxb

**Comment by kelset** [comment]
Pinging OP @frankiesardo since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @frankiesardo ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
