### ISSUE TITLE
Parent Navigator of Nested loses path params

### ISSUE THREAD

**Issue by onlydave** [react-community/react-navigation#1489]
Off the back of #1232

### Simplified Example
```
const AppStackNavigation = StackNavigator({
  Profile: {
    path: 'profile/:profileId',
    screen: TabNavigator({
      overview: {
        path: 'overview',
        screen: () => <View/>,
      },
      activity: {
        path: 'activity',
        screen: () => <View/>,
      },
    },
  },
}
```

### Paths and their results

Using AppStackNavigation.router.getActionForPathAndParams :
* `profile/123` => `{routeName: 'Profile', params: {profileId :undefined}}` ❌ 
* `profile/123/` => `{routeName: 'Profile', params: {profileId :undefined}}`❌ 
* `profile/123/anything` => `{routeName: 'Profile', params: {profileId :123}}` 👍 
* `profile/123/activity` => `{routeName: 'Profile', params: {profileId :123}, action: {routeName:'activity'}}` 👍 

Simplified the results a bit to make it easier to understand. But basically I would have thought that `stackitem/someparam` as a path would still work if the stackitem is a navigator

**Comment by eduardoleal** [comment]
any update?

**Comment by kelset** [comment]
Hi there @onlydave ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
