### ISSUE TITLE
RTL view on LTR/RTL devices

### ISSUE THREAD

**Issue by 2rajpx** [react-community/react-navigation#1518]
Header works correctly in bellow scenarios:

- LTR view on LTR/RTL devices
- LTR/RTL view on LTR/RTL devices

I'm developing an application that must be RTL on LTR/RTL devices. I had to change Header and HeaderBackButton directly for my purpose. It's a bad idea but now it's working.
Is it possible to add this feature?

**Comment by kelset** [comment]
Pinging OP @2rajpx since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @2rajpx,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
