### ISSUE TITLE
SetParams headerRight does not render a new button

### ISSUE THREAD

**Issue by abettadapur** [react-community/react-navigation#1529]
### Current Behavior

I cannot change the headerRight content using the setParams method. Here is my code:

```
this.props.navigation.setParams({
    headerRight: <TouchableOpacity>...</TouchableOpacity>
    title: "Selecting"
});
```
The header title changes to "Selecting" as expected, but no new content is rendered on the right side of the header. If I add the same headerRight item to the static navigationOptions object, content is rendered on the right as expected

### Expected Behavior

I should be able to dynamically set the content on the right of the header
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta9
| react-native     |  43
| node             | 7
| npm or yarn      | 4.*

**Comment by tulin745** [comment]
I met the same problem.

**Comment by BenBach** [comment]
I have the same problem. Any workaround?

**Comment by tjeffree** [comment]
I'm using something like this as a workaround, but there probably is a nicer way:

```javascript
class SomeComponent extends Component {

  static navigationOptions = ({ navigation, screenProps }) => {

    const { state } = navigation
    const { signOutButton } = "params" in state && state.params

    return {
      headerRight: signOutButton && signOutButton()
    }
  }

  componentWillMount() {

    const signOutButton = (
      <Button onPress={() => { this.doSignOut() }} title="Sign Out"></Button>
    )

    this.props.navigation.setParams({ signOutButton: () => signOutButton })
  }
}
```

**Comment by BenBach** [comment]
Thanks works great!

**Comment by yidc** [comment]
This just solve my problem! Thanks!

**Comment by efkan** [comment]
There might be 2 reasons that prevent the changes from being shown:

1. Using PureComponents

An explanation is placed on [VirtualizedList](https://facebook.github.io/react-native/docs/virtualizedlist.html#virtualizedlist) page.

> This is a PureComponent which means that it will not re-render if props remain shallow- equal. Make sure that everything your renderItem function depends on is passed as a prop (e.g. extraData) that is not === after updates, otherwise your UI may not update on changes. This includes the data prop and parent component state.

2. Parameters changes doesn't detect by React-Native because of nested objects
So if the params object is not being changed, React-Native doesn't render the changes.
The same issue valids for [Redux store](http://redux.js.org/docs/recipes/reducers/ImmutableUpdatePatterns.html#updating-nested-objects).

I think that one of or both of these two reasons might cause the rendering problem.

Most likely if you try to change something or pressing on another button at run-time causes render your new button in your app. I had encountered with the same problem months ago.

If community developers can clarify the problem and offer a solution, that would be great!

**Comment by kelset** [comment]
Pinging OP @abettadapur since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @abettadapur,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by DogsForArms** [comment]
Hey!  Not to reopen this topic, but it feel strange to me that we are doing all of this component state -> navigation state linking via a static variable.  Is there another way to be doing this?  I used the solution above and it works fine btw.

**Comment by garfieldnate** [comment]
I have to agree with DogsForArms, I would much rather this ticket be reopened and solved properly. At the least, there could be a documentation fix to make it clear which parameters are actually settable.

**Comment by TimJung** [comment]
Still having this problem in 2020. 

Something like: 
`  useEffect(() => {
    navigation.setParams({
      title: "NEW TITLE",
      headerRight: <Text>NEW TEXT</Text>
    })
  }, []);`

This will actually update the title but the headerRight will not update along with it.

**Comment by kesha-antonov** [comment]
Same problem with RN 4

**Comment by kesha-antonov** [comment]
This works

```
let EditProfile = function EditProfile (props) {
  useEffect(() => {
    props.navigation.setParams({
      headerRight: () => (
        <Button
          onPress={...}
        >
          ...
        </Button>
      ),
    })
  }, [])

  ...
}

EditProfile.navigationOptions = ({ navigation }) => {
  const headerRight = navigation.getParam('headerRight')

  return ({
    headerRight,
  })
}
```
