### ISSUE TITLE
Navigating from redux-saga, thunk or in reducer

### ISSUE THREAD

**Issue by michaelduminy** [react-community/react-navigation#153]
When using react-native-router-flux we could call `Actions.pop()` from within a saga. Is there a way to achieve the same using this using this library?

**Comment by sibelius** [comment]
u can dispatch an action

check the code here: https://github.com/react-community/react-navigation/blob/2e6f7a015f7a033603eb938a83e3a828305c13e3/src/addNavigationHelpers.js#L18

```jsx
goBack: (key): boolean => {
    return navigation.dispatch(NavigationActions.back({
      key: key === undefined ? navigation.state.key : key,
    }));
  },
```

**Comment by hilkeheremans** [comment]
What @sibelius said, but please keep in mind PR #120 -- there are now dedicated action creators, but the action names have also changed. It is backwards compatible, FOR NOW. I'd recommend you run `react-navigation` off of a specific commit at `master` here and use the new API.

**Comment by michaelduminy** [comment]
Thanks very much, just in case someone comes looking here I solved this without integrating it into redux by looking at PR https://github.com/react-community/react-navigation/pull/122. How's how I did it.

Since services function as singletons you can use them to store a reference to your app's root navigator. 

```javascript
const MainNavigator = StackNavigator(configRoutes);

class AppNavigator extends Component {

  componentDidMount() {
    NavigationService.setNavigator(this.navigator);
  }

  render() {
    return (
      <MainNavigator ref={nav => { this.navigator = nav; }} />
    );
  }
}
```

NavigationService.js

```javascript
import { NavigationActions } from 'react-navigation';

const config = {};

export function setNavigator(nav) {
  if (nav) {
    config.navigator = nav;
  }
}

export function navigate(routeName, params) {
  if (config.navigator && routeName) {
    let action = NavigationActions.navigate({ routeName, params });
    config.navigator.dispatch(action);
  }
}

export function goBack() {
  if (config.navigator) {
    let action = NavigationActions.back({});
    config.navigator.dispatch(action);
  }
}
```

Then at any point in your app you can simply use the service to emit navigation actions.

```javascript
import * as NavigationService from 'path/to/service'

class InnerComponent extends Component {
  render() {
    <View>
      <Button
        title="Open notifications screen"
        onPress={() => { NavigationService.navigate('Notifications'); }}
      />
    </View>
  }
}
```

**Comment by junshengpierre** [comment]
Does anyone have an example on how to perform navigation action is a saga?

**Comment by junshengpierre** [comment]
I managed to do it with:

```javascript
yield put(NavigationActions.navigate({routeName: 'SomeRoute'})
```

**Comment by RobertSheaO** [comment]
Normally with react-router and redux-saga, I'd just use push from react-router-redux and call it a day. This solution seems very convoluted. Using the exact NavigationService.js provided by @michaelduminy above, I got this working with redux implemented.

###### root navigator
```JS
...
import { setNavigator } from '../../Services/NavigationService';
...
class App extends PureComponent {
  componentDidMount() {
    setNavigator(this.navigator);
  }
  render() {
    const { navigationState, dispatch } = this.props;
    return (
      <AppRoutes
        ref={nav => { this.navigator = (nav ? nav.props.navigation : nav); }}
        navigation={
          addNavigationHelpers({
            dispatch,
            state: navigationState,
          })
        }
      />
    );
  }
}
```

###### some random file, testing
```JS
import * as NavigationService  from '../../Services/NavigationService';
class SomeOtherScreen extends PureComponent {
  render() {
    return (
      <View>
        <Button
           title="Go to Wallet"
           onPress={() => NavigationService.navigate('OtherScreen')}
         />
      </View>
    );
  }
}
```

**Comment by daose** [comment]
For anybody coming here from searching `sagas` in issues, I found this to be the simplest and most similar to `react-native-router-flux`

```javascript
import { NavigationActions } from 'react-navigation';
import { put } from 'redux-saga/effects';

function* login(action) {
  // if login succeeds 
  yield put(NavigationActions.navigate({ routeName: 'Dashboard' }));
}

// more code
```
There are other actions you can dispatch too, they are listed in [NavigationActions.js](https://github.com/react-community/react-navigation/blob/master/src/NavigationActions.js)

**Comment by braco** [comment]
Another option:

https://github.com/react-community/react-navigation/issues/1439#issuecomment-303661539

**Comment by tmaly1980** [comment]
@daose , I've tried your solution with redux integration and it goes to the route, but adds to the stack rather than using an existing screen already on the stack. For example, I have:

TabNavigator: ProductStack, BusinessStack, CartStack
in ProductStack: ProductList, ProductItem
in CartStack: CartList

When I am in my app and on my ProductItem page, I call my saga that runs:

yield push(NavigationActions.navigate({ routeName: 'CartList', params: {} }))

Unfortunately, I end up on CardStack->CartList->CartList

Honestly I don't understand why something as essential as a navigation system is so complicated. I should be able to have something path-oriented, like "/CartStack/CartList", and not have to fuss about resetting, popping, or explaining where I want to go via a nested data structure. It should interpret a string (possibly with some parameters as a hashed 2nd parameter) and just know what I mean. I suppose I could create some helpers to convert a string path such as the one above to a proper data structure. But it shouldn't be that hard. People have been asking about how to use this and not a lot of easy answers that don't involve code I can't understand easily. Development shouldn't be complicated or frustrating.

I've read something about assigning paths to my routes, but not sure if it can be used internally or just for deep linking from another app on my phone. I will have to experiment.

**Comment by daose** [comment]
@tmaly1980 redux integration requires that you relinquish all the state management that the navigators automatically do for you in favour of handling your own (ex. back button functionality in android).

I don't know if this will fix your issue, but you could try the "Service" solution suggested above https://github.com/react-community/react-navigation/issues/1439#issuecomment-303661539. This way, no redux integration is needed, and you'll still be able to call them in the sagas (or anywhere really)

**Comment by tmaly1980** [comment]
@daose , What do you mean by relinquish automatic state management? I need to see some example code to better understand. In my case, it moves to the new screen properly, so it's in redux and saga as far as I can tell.... But it adds to the inner stack rather than going to the screen that's already on the other tabs stack. Something like this:

From my ProductStack screen: 

yield put(NavigationActions.navigate({routeName: "CartList"}))

Turns the redux stack into:
```
routes: {
    index: 1,
   { index: 0, routes: [], key: ProductStack, routeName: ProductStack },
   { index: 1, routes: [
          { routeName: "CartList", key: "init-id1111111111111" },
          { routeName: "CartList", key: "init-id9999999999" }
       ]
    }
}
```

The question is, why does it append to the stack instead of reusing the screen with the same name? And why is the key randomized for CartList but not ProductStack?

**Comment by adrienjt** [comment]
My [comment](https://github.com/react-community/react-navigation/issues/1439#issuecomment-340293063) in issue #1439 offers a simple solution in case react-navigation is NOT integrated with Redux (trading abstraction for simplicity and flexibility, compared to the service solution).

**Comment by pedrogoes** [comment]
I made this solution: https://www.npmjs.com/package/react-native-navigation-actions

**Comment by obendevski** [comment]
@daose Do I need to setup something extra? Action is firing - yes, but it doesnt change the route.
