### ISSUE TITLE
react Life cycle does not work?

### ISSUE THREAD

**Issue by lucasleelz** [react-community/react-navigation#1554]
### Current Behavior
If I use `this.props.navigation.navigate()`  jump to the next screen, The `componentWillUnmount` method of the previous screen will not be called。

### Expected Behavior
I would like to know react life cycle also useful?

### Your Environment
| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  0.44.0
| node             | 7.5.0
| npm       | 4.1.2

**Comment by gezichenshan** [comment]
stuck with same situation.

**Comment by MrHubble** [comment]
Looking into how to deal with this myself right now. Found some info from another issue that may explain the situation:

>I might be wrong but my understanding is that Components are not unmounting when switching to another screen instead you push screens in a router stack as you are dispatching actions to navigate.
In fact back button pops an element from the stack and that behavior will never be possible if the component has been unmounted.
https://github.com/react-community/react-navigation/issues/298#issuecomment-279132024

**Comment by mmarvick** [comment]
It looks like components never get unmounted. We're running into another issue because of this: Components that are further down the stack can receive calls to methods like `componentWillReceiveProps` and `render` even when they're not showing. We use redux, so if the component is connected to some part of the state and that state gets updated, the method will get called.

This bit us because we were doing a navigation on a particular state change and assumed that it could only happen once. So we need to rethink where we make our navigation call.

**Comment by inlightmedia** [comment]
I read that tabs are all rendered together by default to make it a faster experience and that you have to specify lazy: true or all you tabs will render in the background.

**Comment by timLoewel** [comment]
This also happens in the StackNavigator.

And there the componentWillMount is called when you pop the Views on top of a hidden screen and it comes back into view. 

We have a camera view (react-native-camera) inside a screen that gets pushed to the "background". As soon as it comes back into view, a new camera-view gets instantiated. And as there was never an unmount, the old camera lives on as a zombie.
That is a memory leak.
And as soon as I close the App the view gets cleaned up, and all the camera views also get cleaned up but only the first camera cleanup succeeds and the rest crash (on android at least), as the camera was already closed.

**Comment by kelset** [comment]
Pinging OP @lucasleelz since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

Moreover, it's really hard to pinpoint this as a bug, since you don't specify what kind of navigator you have been using. As pointed out by @MrHubble, in a StackNavigator scenario when you add a screen the previous doesn't get destroyed. But it's "a feature": the previous screen needs to survive for you to navigate back to it.

Or am I missing the point?

**Comment by mmarvick** [comment]
@kelset, I think your point that the screens surviving being a feature is a very valid one. The bigger issue though is that it's hard to tell when a user has navigated to or from a component. If we can't figure that out from the React lifecycle, then there should be some other way to do it.

That said, there's a long discussion about that very issue on https://github.com/react-community/react-navigation/issues/51, so I'd be tempted to call this issue a dupe.

**Comment by kelset** [comment]
Exactly; that's why I'd like to close this.

**Comment by vonovak** [comment]
I'm closing this for the above stated reasons. I'd also like to mention https://reactnavigation.org/docs/guides/screen-tracking ; in particular `onNavigationStateChange`

**Comment by kodayashi** [comment]
Hi @vonovak, @mmarvick or others. This is also an issue with me using redux. I want to navigate in a StackNavigator based on state change. So I tried using the componentWillReceiveProps lifecycle method and that works, but since that component never umounts this lifecycle method is constantly being triggered for this view even though it's not visible.

How are people solving this? Navigating when a component's state changes (i.e. receives new state that's mapped to props via redux) seems critical, I'm just not sure how best to handle this outside of the react native lifecycle methods since the life of them is indefinite.

Any help would be much appreciated!

**Comment by mmarvick** [comment]
@kodayashi I'm keeping track of what the route key is on the navigation reducer. So the navigation reducer that is provided by react-navigation lives at `state.navigation.navigationState`, and the current route key lives at `state.navigation.currentRouteKey`. I'm using TypeScript, so you can get rid of the typing, but the original reference I saw was here: https://github.com/react-navigation/react-navigation/issues/51#issuecomment-279885514.

Then in the lifecycle methods, I can check that `props.currentNavigationKey === 'ComponentNavigationKey'`.

```
export interface INavigationState {
  currentRouteKey: string;
  navigationState: NavigationState;
}

const getCurrentRoute = (state: NavigationState): any => {
  if (state.routes) {
    return getCurrentRoute(state.routes[state.index]);
  }
  return state;
};

const getCurrentRouteKey = (state: NavigationState): string => {
  let currentRoute: any = getCurrentRoute(state);
  return currentRoute.key;
};

// This is the navigation reducer
export default (state: INavigationState, action: any): INavigationState => {
  // Handle the initial state
  if (!state) {
    let initialNavigationState = RootNavigation.router.getStateForAction(action, undefined);
    return {
      currentRouteKey: getCurrentRouteKey(initialNavigationState),
      navigationState: initialNavigationState
    };
  }

  let navigationState = RootNavigation.router.getStateForAction(action, state.navigationState);
  return {
    navigationState,
    currentRouteKey: getCurrentRouteKey(navigationState)
  };
};
```

**Comment by ShaikhKabeer** [comment]
Guys, I'm also facing the same issue. I have used 'react-navigation' and redux.
 I have one SelectCompany screen and from there I'm navigating to AddProfile screen like this.props.navigation.navigate('AddProfile'). So SelectCompany's unmount is not calling. Also when I add data to profile then instead of AddProfile's componentWillReceiveProps it is calling SelectCompany's componentWillReceiveProps. So I think this is happening as SelectCompany's  unmount is not calling.

Any solution for this ?

**Comment by jitenderchand1** [comment]
I am facing same issue

**Comment by sebringj** [comment]
Why is this closed? I've worked around this like so...

```
  static loaded = false
  componentDidMount() {
    if (MyView.loaded)
      console.warn('subsequent loads')
    else
      console.warn('first load')
    MyView.loaded = true
  }
```
but that's pretty crappy.

**Comment by vonovak** [comment]
This is closed because it's considered a non-issue. Please see https://reactnavigation.org/docs/en/navigation-lifecycle.html

**Comment by onitzschke** [comment]
I have a simliar issue.
I'm not able to remove the Backhandler listener with react-navigation lifecycles as in the [docs](https://reactnavigation.org/docs/en/custom-android-back-button-handling.html) describes.

`Can\'t perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s', 'the componentWillUnmount method', '\n  `

**Comment by popstheman** [comment]
I'm having the same issue. I followed the react-navigation docs and implemented the react-navigation life cycle methods. I'm getting the same error as @onitzschke 

`Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s', 'the componentWillUnmount method'`

Any solutions yet?
