### ISSUE TITLE
reset seems to load unwanted initialRouteName 

### ISSUE THREAD

**Issue by npomfret** [react-community/react-navigation#1555]
I'm trying to implement the equivalent of `immediatelyResetRouteStack` by using the `reset` function.  Something like:

```
function _immediatelyResetRouteStack(routes) {
  const actions = routes.map((route) => NavigationActions.navigate(
    {routeName: routeNames[route.name], params: route.passProps}));

  this.navigation.dispatch(NavigationActions.reset({
    index: actions.length - 1,
    actions: actions
  }));
} 
```

However, it looks like the view specified by `initialRouteName` in my `StackNavigator` is being loaded, which I really don't want (that view definitely isn't in the array of routes that's being passed).  Why is the `initialrouteName` being loaded?

**Comment by spencercarli** [comment]
A small demo of this issue would be helpful in debugging this.

**Comment by kelset** [comment]
Pinging OP @npomfret since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @npomfret ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
