### ISSUE TITLE
Global router?

### ISSUE THREAD

**Issue by dejakob** [react-community/react-navigation#1601]
Hey guys,

We're using push notifications and all kinds of other behaviour that route the app to a certain route. Is there a way to trigger a navigate globally, so without using the this.props.navigation? In my opinion, it would be much easier for navigating from a service that is not related to any component. I couldn't really find an example of this in the documentation.

Kind regards,
dejakob

**Comment by augustoabreu** [comment]
Hi, i've not tested this but since you're using redux, can't you call `store.dispatch(action)` from anywhere?

**Comment by abe-winter** [comment]
It looks like [createNavigationContainer](https://github.com/react-community/react-navigation/blob/30ca3c1/src/createNavigationContainer.js) sets up the `dispatch()` function on the `React.Component`, not on the router.

I'm not that familiar with this codebase but I'm 30% sure that to get global `dispatch()`, you'd need to modify createNavigationContainer so that it set up a react ref on the Component.

Someone who knows more about this library should probably weigh in.

**Comment by kelset** [comment]
Pinging OP @dejakob since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @dejakob ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by hellogerard** [comment]
In case anyone finds this via Google, this is more or less the same as #1439. #1439 has some good workarounds, until react-navigation supports this internally.

**Comment by pedrogoes** [comment]
I made this solution: https://www.npmjs.com/package/react-native-navigation-actions
