### ISSUE TITLE
StackNavigator's header title gets overlayed with previous route's title

### ISSUE THREAD

**Issue by fhad-getmaple** [react-community/react-navigation#1611]
Header titles get jumbled up. Steps to reproduce:

1. From a page that has more than one link, tap any link that opens a new route
2. In the newly opened page, click < Back
3. Immediately, tap on another link

<img width="320" alt="screen shot 2017-05-19 at 3 34 47 pm" src="https://cloud.githubusercontent.com/assets/22453066/26263935/ba2cc7d8-3ca8-11e7-8244-7167568215a0.png">

Is anyone else experiencing this issue?

**Comment by koenpunt** [comment]
I've seen this happening, but always only momentarily.

**Comment by timothylui** [comment]
Yup happens for us

**Comment by spencercarli** [comment]
Is this still an issue for anyone in the latest version?

**Comment by beeant** [comment]
happens to me too...

**Comment by binchik** [comment]
I also saw this issue in my app. The header content would be overlayed by the content of the previous screen header for a second. It was happening when I called `LayoutAnimation.configureNext` before calling going back.

**Comment by kelset** [comment]
This should be fixed via #2520, that has been already merged. It will be available with the new `beta.16`; in the meantime you can point to master to check if it fixes it for you.

**Comment by kelset** [comment]
Pinging OP @fhad-getmaple since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open, because if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @fhad-getmaple ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
