### ISSUE TITLE
Gestures does not works when the Navigator size is small

### ISSUE THREAD

**Issue by AdriaRios** [react-community/react-navigation#1654]
Dear All,

The gestures in modal mode does not works if the size of the Navigator is small (less than a half of the screen aprox):

```sh
<View style={{flex:1, backgroundColor: 'blue'}}>
          <View style={{flex:1, backgroundColor: 'red'}}>
          </View>
          <View style={{flex:1, backgroundColor: 'red'}}>
            <MyNavigator />
          </View>
        </View>
class HomeScreen extends Component {
  static navigationOptions = {
    title: 'Welcome',
    gesturesEnabled: true
  };
  render() {
    const { navigate } = this.props.navigation;
    return (
      <View>
        <Text>Hello, Chat App!</Text>
        <Button
          onPress={() => navigate('Chat')}
          title="Chat with Lucy"
        />
      </View>
    );
  }
}
```
```sh
class ChatScreen extends React.Component {
  static navigationOptions = {
    title: 'Chat with Lucy',
    gesturesEnabled: true
  };
  render() {
    return (
      <View>
        <Text>Chat with Lucy</Text>
      </View>
    );
  }
}

export default  MatchesNavigation = StackNavigator({
  Home: { screen: HomeScreen },
  Chat: { screen: ChatScreen }
},{
    mode: 'modal',
    headerMode: 'none'
  });
```

**Comment by kelset** [comment]
Pinging OP @AdriaRios  since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @AdriaRios ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
