### ISSUE TITLE
Can you add a back button in the tab bar header?

### ISSUE THREAD

**Issue by hzyIO** [react-community/react-navigation#1657]
Hey guys,

Really like the library, we are trying to move to this for better performance. For our navigation we basically have a stack navigator that contains two levels of tab views.

I want to be able to add a back button (in the header of the tab bar, not on the screen) on the left, so the first icon / label would be a left arrow < which pops back to the first tab view. I understand that I can create a custom tab header, but it seems like this functionality may be out of the box with some slight tweaks. Anyone tried this or could point me in the right direction?

**Comment by faceyspacey** [comment]
I dont understand. That is the default behavior for the StackNavigator--it automatically gives you back buttons in the top left of the "Nav Bar"--you want a back button on the "Tab Bar"? Currently there is no way to create buttons for other things on a Tab Bar. You can make your own, and then dispatch--if ur using Redux, which u should--an action like this: `dispatch(NavigationActions.back())`.

My overall suggestion is to study the documentation inside and out before asking these kind of questions (look how many issues this Repo has--they got their work cut out for themselves, and need to focus on fixing things, not answering questions you can figure out on your own with a little bit more time investment). Then analyze the code for these files:

-`src/routers/StackRouter` 
- `src/navigators/StackNavigator`
- `src/navigators/createNavigator`
- `src/createNavigationContainer`
- `src/addNavigationHelpers`

**Comment by faceyspacey** [comment]
I haven't done this myself, but probably the best way is to use the TabNavigatorConfig option, `tabBarComponent`, where you will get passed a bunch of props needed to create children tab buttons, and then you find a way to inject your custom button that dispatches a BACk onPress.

**Comment by hzyIO** [comment]
Yeah @faceyspacey your second comment is the direction I'm heading. I'm hoping that I could solve this issue and someone else looking for my use case could find this implementation in the future.T navigation library seems powerful and extensible, however the documentation is lacking in how you can customize it to your needs. Here is a screen shot of the effect I'm looking for, which currently exists in our apps.

Here is the main navigation, which is a stack navigation, with the first view being a TabView.
![img_2049](https://cloud.githubusercontent.com/assets/192363/26377318/a442737c-3fc4-11e7-8145-d45ba1d51f53.PNG)

When you click on a panel, it pushes another TabView here as shown here. This also illustrates the back button that I would like to get to return to the main navigation.
![img_2048](https://cloud.githubusercontent.com/assets/192363/26377385/e676aac4-3fc4-11e7-9e92-d7eaa8985060.PNG)

I'm planning to dive into TabBarTop, my initial findings is that it is super simple but depends on about 4 or 5 different other files. I'm trying to see if there is another way.

**Comment by faceyspacey** [comment]
That app looks sick? What is that an iPad app?

...I've found that it's basically not even that the documentation is missing--it's that the features are missing! Essentially the current Navigator API is very high level and automatically does lots of stuff for you, but without enough customization. You're basically limited to styling designated elements.  In this precise case, what's needed is a way to specify a Tab component, not just the entire TabBar! ..But still that wouldn't solve your use case. Your use case may in fact never have any other option than rewriting the Tab Bar itself. The only thing I could think of is if there were options to provide Views for different buttons as well as what index you want to inject them at (or perhaps u can just choose far left or far right). But there certainly isn't anything like that.

Another thing: you may find that as you look into their TabBar components it uses things (like various transitioners) which aren't exported directly. In that case you need to import if from `src/foo/bar.js`. But you should be able to get access to everything they are using to remake the tab bar how you want. You could also just skip it and make the tab bar from scratch and grab the `index` from state (presuming you're using redux), and boom, there's your selected tab. All u gotta do is dispatch an action onPress for each tab after that. You may end up with a TabBar in half a day rather than multiple days. If you don't want fancy things like animating line under the tabs, or scrollable tabs, there's likely no reason to try to use their stuff. It's just a row of buttons.

**Comment by faceyspacey** [comment]
Make sure ur using redux and the redux devtools and u got a good grasp of the state in ur reducers. U'll realize it's all just redux state as normal. U could go far without even using their navigators, and just using their highly specialized routers, which through their `getStateForAction` method are primarily drop-ins for your reducers.

**Comment by faceyspacey** [comment]
Basically, forget a tab bar and a drawer--for advanced users, this library is all about the Stack. Drawers and Tab bars can easily be built on your own. But stacks have a lot of complex behavior (and animations) u definitely rather not deal with.

**Comment by hzyIO** [comment]
@faceyspacey Thanks again for your help. The app is a baseball game - we have a good designer 💯 We are actually still using flux since we started at around RN v0.14, so we haven't moved over to a redux implementation yet, still working on that :) Anyway, appreciate your input here and will close this, and hopefully update if we find a solution. But I will definitely look into the approaches you describe above. Thanks!
