### ISSUE TITLE
How can I make goToTop functionality in tabNavigator

### ISSUE THREAD

**Issue by mnkang89** [react-community/react-navigation#1662]
Many sns app like Instagram have scrollsToTop functionality when user press tabButton.
though I know that there is a way we could make some hook in tabbutton press.(like below code) I can not figure out how to implement it. 

Are there any way to scroll up when user tap tabbutton? I cannot see any information about it in doc

```
<TabBarBottom
          {...props}
          jumpToIndex={index => {
            const { dispatch, state } = props.navigation

            if (index === 2) {
              navigation.navigate('Camera')
              return
            }
            if (state.index === index) {
              if (state.routes[index].index === 0) {
                // dispatch(NavigationActions.setParams({
                //   params: { scroll: state.routes[index].key },
                //   key: 'Init'
                // }))
              } else {
                const stackRouteName = ['Feed', 'Noti', '', 'Explore', 'Profile'][index]

                dispatch(NavigationActions.reset({
                  index: 0,
                  actions: [NavigationActions.navigate({ routeName: stackRouteName })]
                }))
              }
            } else {
              jumpToIndex(index)
            }
          }} />
```

**Comment by kelset** [comment]
Hi @mnkang89 ! It looks like this is not a bug of the library nor a feature request, so I'll close it: I suggest next time you use [Stack Overflow](https://stackoverflow.com/search?q=react-navigation) which is better suited for answering these types of questions. I also encourage you to join the [Reactiflux](https://www.reactiflux.com/) community on Discord. There are React Native and React Navigation channels with helpful people who might be able to answer your question. I would also like to mention that there is a collection of helpful links and tutorials for React Navigation in the [README](https://github.com/react-community/react-navigation#community-contributions) which might be helpful for you.

That said, scroll to top isn't related to the lib itself since what you are trying to achieve is related to a ScrollView/FlatList/SectionList. If you check the docs for those components you'll see that is possible to move the list back to top, and to achieve it via the tab press you simply need to customize the header element with a custom TouchableOpacity.

If you believe that you are experiencing a bug or have a feature request, please open a new Issue following the dedicated template or submit a PR.
