### ISSUE TITLE
tabBarOptions redux connection

### ISSUE THREAD

**Issue by bahadircivelek** [react-community/react-navigation#1668]
Hi,  how can i update  tabBarOptions on runtime with my redux store ?

```
{
        tabBarOptions: {
            activeTintColor:  this.props.mainColor,
            inactiveTintColor: '#c62d2d',
            indicatorStyle: {
                backgroundColor: theme.mainColor
            },
            style: {
                backgroundColor: 'white'
            }
        }
    }`
```

This is my main AppNavigator

```
export const AppNavigator = StackNavigator(
    {
        Login: { screen: Login },
        Main: { screen: TabsNavigator },
        Profile: { screen: ModuleList },
    }, {
        headerMode: 'none'
    }
);
```

i want to take activeTintColor from reducer and update tabBarOption ?

**Comment by faceyspacey** [comment]
You can't without using a custom `tabBarComponent`. These are the only options screens have:

https://reactnavigation.org/docs/navigators/tab#Screen-Navigation-Options

For those options you can use a function for `navigationOptions` on the given screen and set those dynamically from redux state (at "runtime"). 

To do what you're asking requires writing your own `tabBarComponent`. And that's something custom/pro apps will often end up doing. The way you do it is you copy one of the built in components (`TabBarBottom` or `TabBarTop`) and use redux-connected components to get any state you need. If you need to rebuild those components and since most of the modules used to build such things as the TabBar are not directly exported, just import the files you need from `src/views/SomeView.js` for example.

**Comment by jbrodriguez** [comment]
@bahadircivelek take a look at some options discussed in https://github.com/react-community/react-navigation/issues/1565.

Not exactly about TabBar, but it's related.

**Comment by bahadircivelek** [comment]
@jbrodriguez Actually we can change Header Style from navigationOptions easly :) but thank you for your interest.. i created custom tabbar component like @faceyspacey said.

**Comment by WebStew** [comment]
Hi @faceyspacey @bahadircivelek 

Is there an example of these customised tabbars around? I can't seem to find one anywhere.

**Comment by bahadircivelek** [comment]
i also didnt find but i solve my problem with tabBarComponent option.

`const TabsNavigator = TabNavigator(
    {
        Dashboard: {
            screen: DashboardStack,
        },
        Modules: {
            screen: ModuleStack,
        },
        Tasks: {
            screen: TaskStack,
        },
        Settings: {
            screen: SettingStack,
        }
    },
    {
        tabBarPosition: 'bottom',
        tabBarComponent: ({ navigation, ...options }) => {
            return (
                <FooterTabs
                    {...options}
                    screenProps={footerScreenProps}
                    navigation={navigation}
                />
            );
        }
    }
);`

**Comment by WebStew** [comment]
Okay great thanks @bahadircivelek. and then FooterTabs can be hooked up to your store. I might copy paste the react-navigation one and tweak to my needs like @faceyspacey describes.

**Comment by bahadircivelek** [comment]
@WebStew  yes 👍

**Comment by kelset** [comment]
Pinging OP @bahadircivelek since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by waqarmobi** [comment]
@MrBrownser I tried using your solution but I'm unable to access customColor prop in tabBarComponent props.
do you have any working example which I can refer to ?
