### ISSUE TITLE
is this Syntax possible?

### ISSUE THREAD

**Issue by nsisodiya** [react-community/react-navigation#1685]
following code is taken from docs
```
const MyApp = StackNavigator({
  Home: { screen: HomeScreen },
  Profile: { screen: ProfileScreen },
}, {
  initialRouteName: 'Home',
})
```

I went to docs and I see there are large number of options are possible to configure and use navigation. This is Good and needed for success of any project. `Ability to configure in desire way.`

I am not asking to change any syntax or modify current implementation. I am just asking that 
would it possible to support following syntax too. This will help to improve readability.

```
const MyApp = StackNavigator({
  Home: HomeScreen,
  Profile: ProfileScreen,
}, {
  initialRouteName: 'Home',
})
```

IMO- `react-navigation` can support both syntax.

**Comment by faceyspacey** [comment]
it could and should since that's very common (and since there are so few other options for each route), but I'd close this issue because--look at how many issues this repo has. they have a lot of other things to deal with, whereas your request doesn't actually fix anything truly broken.

**Comment by faceyspacey** [comment]
...ps, make a PR to `src/routers/TabRouter.js` and `src/routers/StackRouter.js` and `validateRouteConfigMap.js` to change this.

**Comment by nsisodiya** [comment]
Sure. I will make a PR.

**Comment by kelset** [comment]
Pinging OP @nsisodiya since this issue is quite old and related to an old version of the lib (and I can't see the mentioed PR anywhere). If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @nsisodiya ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
