### ISSUE TITLE
How to overlay view to cover screen over tabbar?

### ISSUE THREAD

**Issue by MovingGifts** [react-community/react-navigation#1734]
I have a screen with tabbar enabled. Within the screen's component, I have a blue overlay component, which when visible, should cover the entire device screen with blue, including the tabbar.

The issue is the tabbar is **always** above the overlay component. How can I have the overlay cover the entire device screen OVER the tabbar too, so it is always over the tabbar? I could not find anyway to do that, as the tabbar is always over the overlay. Any ideas?

**Comment by zachgibson** [comment]
What you’re explaining is expected behavior. You’re trying to have a child tab view go on top of the parent tab bar without using a navigator. Have a look at [StacksOverTabs.js](https://github.com/react-community/react-navigation/blob/master/examples/NavigationPlayground/js/StacksOverTabs.js). You could do something similar like create a StackNavigator that has a TabNavigator along with your overlay component. Then you could navigate to your overlay using modal mode or write your own custom transition.

**Comment by MovingGifts** [comment]
@zachgibson Thanks for the info; I found a solution in [this thread](https://github.com/react-community/react-navigation/issues/363) which works :)
