### ISSUE TITLE
tabStyle not taken into account

### ISSUE THREAD

**Issue by Kernael** [react-community/react-navigation#1739]
### Current Behavior

Given the following code :

```
TabNavigator({
  ...
}, {
  tabBarComponent: TabBarBottom,
  tabBarPosition: 'top',
  tabBarOptions: {
    tabStyle: {
      justifyContent: 'center',
    },
  },
})  
```
The tab content remains justified at the defaults `flex-end` (as defined in TabBarBottom.js line 186)

### Expected Behavior

I would expect the tab content to be justified at `center`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.44.2
| node             |  7.10.0
| npm or yarn      | 0.24.5

P.S : thank you for your awesome work !

**Comment by LAITONEN** [comment]
The author of this post did not find it useful to help others who might encounter the same problem, so in case somebody wonders why some of your styles do not affect your TabBarBottom component, the reason is that not all the styles are available for TabBarBottom, use TabBarTop instead and set 'tabBarPosition' prop to 'bottom' or otherwise since there is no universal component (at least I have not found yet) that have all the possible properties (all from TabBarTop and TabBarBottom) together.
