### ISSUE TITLE
goBack doesn't trigger TextInput autofocus

### ISSUE THREAD

**Issue by basudz365** [react-community/react-navigation#1752]
I have a simple StackNavigator with 2 screens.  Each screen has 1 TextInput with autofocus={true} and a submit button to advance.  

Autofocus works correctly for the 1st screen and the keyboard pops up.  Going to the 2nd screen, autofocus also works correctly and the keyboard pops up.
If I hit the back button in the header, the screen navigates back to the 1st screen correctly, however..the autofocus does not happen, therefore my keyboard does not pop up automatically.

Is this a bug or is there a way to tap into the navigation lifecycle so I can manually set the focus to pop the keyboard?

"react-navigation": "^1.0.0-beta.9",
"react-native": "0.44.2",

**Comment by robinheinze** [comment]
Experiencing this issue as well. 

1.0.0-beta.7
react-native 0.45.1

**Comment by derekgreenberg** [comment]
Here is one way you can detect when a screen appears after another screen was popped off the stack. It involves passing your own reducer to the StackNavigator.

Scenario: You have a StackNavigator with two screens, one named 'ScreenOne' and the other named 'ScreenTwo'. Both screens have a TextInput with autofocus. On ScreenOne, there is a button that, when tapped, takes the user to ScreenTwo. On ScreenTwo, there is a button (and possibly an Android hardware back button configuration!) that invokes this.props.navigation.goBack() when tapped.

When ScreenOne appears after the back button was tapped from ScreenTwo, you need a way to know this occurred in order to set focus on the TextInput. If you are using your own reducer to handle navigation, and have passed it to the StackNavigator via its `navigation` prop, you can listen for changes to navigation state via the navigation reducer in ScreenOne and determine when to invoke setFocus() on the TextInput.

Here's an example of accessing the navigation state via via mapStateToProps in ScreenOne:

```
const mapStateToProps = (state) => {
  return {
    nav: state.navigation
  }
}
export default connect(mapStateToProps, null)(ScreenOne)
```
Here you can see that `navigation` is my own reducer that is hooked up to the StackNavigator, accessible from the store. The prop is named 'nav' - because 'navigation' is already set as a prop in the screen by react navigation.

The next step is detecting when the navigation state is appropriate for invoking setFocus() on the TextInput. You can do that in ComponentWillReceiveProps() - and that is how you can tap into the screen's lifecycle. Here's an example of that:

```
   componentWillReceiveProps (newProps) {
    if (this.props.nav !== newProps.nav) {
      const currentRoute = pathOr(null, ['routes'], newProps.nav)
      if (currentRoute && equals(currentRoute[0].index, 0)) {
        this.textInput.setFocus()
      }
    }
  }
```
Of course, your route detection code may be different. The interesting thing is that you can use this technique to dispatch an action that reloads data from an API, or whatever you want to do whenever this screen appears.

**Comment by basudz365** [comment]
@derekgreenberg Thanks for the suggestion, I'll give it a shot!

**Comment by kelset** [comment]
Pinging OP @basudz365 since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by basudz365** [comment]
@kelset I wasn't able to find a good solution for my needs at the time but my requirements have changed and I no longer have this issue to solve.

**Comment by craigcoles** [comment]
Is there a chance this issue could get reopened? I am experiencing this issue in:

```json
"react-native": "0.53.0",
"react-navigation": "^1.0.3",
```

### Example
![](https://user-images.githubusercontent.com/996430/36438383-b1720c8c-1661-11e8-9e4a-56140db477cd.gif)

The TextInput is essentially invisible and the result is being rendered. The Input has `AutoFocus` set to `true`, but does not AutoFocus when using the default back button.

**Comment by brentvatne** [comment]
autofocus only fires on mount. it is not mounted again when you return to the screen. you need to subscribe to focus events.

```
componentDidMount() {
  this.focusListener = this.props.navigation.addListener('didFocus', () => this._textInput.focus());
}

componentWillUnmount() {
  this.focusListener.remove();
}
```

https://reactnavigation.org/docs/navigation-prop.html#addlistener-subscribe-to-updates-to-navigation-lifecycle

**Comment by craigcoles** [comment]
@brentvatne Apologies! Thanks!

**Comment by satya164** [comment]
@brentvatne even better, create a `TextInput` component which does it internally and use it everywhere 🎉

**Comment by brentvatne** [comment]
indeed @satya164! you could use `withNavigationFocus` for that 👌

**Comment by Albert-Gao** [comment]
That `focusListener` method works pretty well, but not the `withNavigationFocus`, `withNavigationFocus` only works for the 1st time, then it won't be triggered when leave the tab and back to it. I use bottom tab navigator

**Comment by brentvatne** [comment]
@Albert-Gao - please post a new issue where you reproduce this problem with a [mcve]( https://stackoverflow.com/help/mcve) that we can run on https://snack.expo.io or in a github repo.
