### ISSUE TITLE
Theme: changing header background colors across app

### ISSUE THREAD

**Issue by mmahalwy** [react-community/react-navigation#1762]
Is there a way to theme all the prebuilt components/views for navigation? I am finding myself having to change the header background color for each view, which might make it easier with a theme.

Thanks

**Comment by fmoessle** [comment]
Sadly there is no option for styling your headers background. But you can build your own custom header or use another navigation-library for react-native. This project only provides basic functionality. 

Please check this project: [https://github.com/wix/react-native-navigation](url). These guys are already working on v2 of wix-react-native-navigation!

**Comment by mmahalwy** [comment]
@fmatoss I been wanting to use the wix navigation. It looks wonderful!

**Comment by vonovak** [comment]
@fmoessle just so you know, they have been working on v2 for the past 6 months or maybe more

**Comment by kelset** [comment]
Pinging OP @mmahalwy since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @mmahalwy ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
