### ISSUE TITLE
Documentation Improvement Request: Navigation Containers in Navigators.md

### ISSUE THREAD

**Issue by gsklee** [react-community/react-navigation#1779]
That section is a mess. I don't really understand anything it tries to convey at all after reading it 3 times back and forth. A few issues:

* How could the navigation props be missing??? Does the "navigation props" means [_this_ navigation props](https://reactnavigation.org/docs/navigators/navigation-prop) or something else?

* What is this "transparent navigation container"? Is it some implementation detail that end users really need to know?

* "When rendering one of the included navigators, the navigation prop is optional" - what is this supposed to mean!? The "navigation props" are always there, `this.props.navigation.navigate` etc. etc. There seems to be a terminology issue going on here.

* Can we have an example please?

**Comment by gsklee** [comment]
Again, in https://reactnavigation.org/docs/navigators/navigation-prop:

> For navigators that are nested inside of your main navigator, you always want to pass the screen's navigation prop down. This allows your top-level navigator to communicate and provide state for all the children navigators. Only your top-level router needs to be integrated with redux, because all the other routers are inside it.

Can we clarify what this means with an example code of how to exactly pass the screen's navigation prop down?

**Comment by ErikaDeveloper** [comment]
I look at the the document of navigation and copy the code of document,but i got error. That section is really a mess!!

**Comment by KevKo1990** [comment]
I do not understand it either how I achieve to create a custom navigation container...

**Comment by kelset** [comment]
Pinging OP @gsklee since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

Moreover, if you think the wording in the docs is not good feel free to open PRs to improve them! We are working hard to improve them ourselves but any help is surely welcome!

**Comment by kelset** [comment]
Hi there @gsklee ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
