### ISSUE TITLE
NavigationActions.init ?

### ISSUE THREAD

**Issue by gsklee** [react-community/react-navigation#1791]
https://github.com/react-community/react-navigation/blob/master/docs/guides/Navigation-Actions.md

Says there should be an `Init` action "used to initialize first state if state is undefined"; however the docs only mentioned it without a dedicated section.

**Comment by Cygnus2112** [comment]
From what I can tell it works pretty much the same as NavigationActions.reset. Which is to say, not very well.

**Comment by kelset** [comment]
Pinging OP @gsklee since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open, because if I get no answer in the next 7 days I will close it.

That said, it's not like there's much to say about `Init`, as pointed out by @Cygnus2112 - anyway a PR to add a couple lines would surely be welcome.

**Comment by kelset** [comment]
Hi there @gsklee ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
