### ISSUE TITLE
StackNavigation transition with height custom header

### ISSUE THREAD

**Issue by mickaelw** [react-community/react-navigation#1842]
When we have a custom header which is heigher than the default header there is a weird behavior:

the start page with a big header:
![image](https://user-images.githubusercontent.com/23268376/27043173-877c80fe-4f99-11e7-99b8-f42573155b26.png)

the next page with the default header height:
![image](https://user-images.githubusercontent.com/23268376/27043151-7c1cbe68-4f99-11e7-9b27-b519b249321b.png)

### Current Behavior
When I start the transition the next header is pre displaying. So the page with the big header has a strange behavior

### Expected Behavior
Don't pre render or keep the place of the default header during transitions and have a push transition 

| software              | version
| ------------------ | -------
| react-navigation |  latest
| react-native        |  latest
| node                   |  latest
| npm or yarn       | latest

**Comment by spencercarli** [comment]
Can you try changing the [headerMode](https://reactnavigation.org/docs/navigators/stack#StackNavigatorConfig) and see if that helps?

**Comment by spencercarli** [comment]
Also a demo of this issue would be very helpful. Thanks!

**Comment by kelset** [comment]
Pinging OP @mickaelw  since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open, because if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @mickaelw ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
