### ISSUE TITLE
componetWillReceiveProps and shouldComponentUpdate is not executed

### ISSUE THREAD

**Issue by zhenliliu** [react-community/react-navigation#1859]
class Home extends Component {
    componentWillReceiveProps(nextProps){
        console.log('nextProps',nextProps);
    };
    render(){
        return(
            <View></View>
        )
    }
}

const Tab = TabNavigator({
    home: {screen: Home}
});
export default StackNavigator({
    tab: {screen: Tab}
})

// when I use navigate to jump to a new page and goBack this page the componentWillReceiveProps method and shouldComponentUpdate method was not executed.

**Comment by jamesone** [comment]
@zhenliliu Did you figure out a workaround?

**Comment by schneck** [comment]
+1

**Comment by bennygenel** [comment]
I had a similar problem and how I figure it out was sending a function as a parameter to the navigated screen and then run it on componentWillUnmount.
Its not the same thing but maybe it could help.

**Comment by MrHubble** [comment]
@bennygenel would you please be able to provide some sample code of your solution?

**Comment by shangxinbo** [comment]
I have the same problem

**Comment by galhardi** [comment]
+1

**Comment by TrustTheBoy** [comment]
+1

**Comment by TrustTheBoy** [comment]
@galhardi @shangxinbo @MrHubble @schneck @zhenliliu Is that settled?

**Comment by alexey-belous** [comment]
Have the same problem.

**Comment by JulianKingman** [comment]
@zhenliliu in your case, this is because the screen in question has already mounted, and no new props are being passed to it. One way you could do this (if you use redux for navigation) is to connect the component to nav state, then anytime you navigate it will receive the updated nav state, and `shouldComponentUpdate` and `componentWillReceiveProps` will fire.

I'm having a problem where componentWillMount and shouldComponentUpdate are not firing when I navigate to the screen in the first place, but that's a different issue.

**Comment by kelset** [comment]
Pinging OP @zhenliliu  since this issue has not been active for a while, and it's related to an old version of the lib. (and it doesn't adhere to any kind of issue template, which makes it basically impossible to investigate)

Please let me know if you want this to remain open, because if I get no answer in the next 7 days I will close it.

**Comment by bennygenel** [comment]
For future people who visits this thread here is a sample implementation that I have talked about before;

```javascript
export default class SomeComp extends Component {
onGoBack = (someDataFromModal) => {
  console.log(someDataFromModal);
}

render() {
    const { navigate } = this.props;
    return (
        <TouchableOpacity
          onPress={navigate("Modal", { onGoBack: this.onGoBack })}
        />
       )
    }
}
```
```javascript
export default class Modal extends Component {
componentWillUnmount() {
  if(this.props.navigation.state.params.onGoBack) {
    this.props.navigation.state.params.onGoBack('I\'m fired from Modal!');
  } 
}

render() {
    const { data, ... } = this.props.navigation.state.params;
    const { goBack } = this.props.navigation;
    return (
        <View>
            <TouchableOpacity
              onPress={goBack()}
            />
            <Text>
               {'Some Text'}
            </Text>
        </View>
       )
    }
}
```

**Comment by kelset** [comment]
Hi there @zhenliliu,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it. Btw thanks @bennygenel for the snippet, it will surely help.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
