### ISSUE TITLE
understanding AppState with react-navigation

### ISSUE THREAD

**Issue by samartha-kar23** [react-community/react-navigation#1934]
# **Hurdle**
Storing the present navigation stack trace and retrieving it when necessary.
# **Docs**
AppState can tell you if the app is in the foreground or background, and notify you when the state 
As we all know it has three states:
- **active** - The app is running in the foreground
- **background** - The app is running in the background. The user is either in another app or on the home screen.
- **inactive** - This is a state that occurs when transitioning between foreground & background, and during periods of inactivity such as entering the Multitasking view or in the event of an incoming call.

[Docs.](https://facebook.github.io/react-native/docs/appstate.html)

# **Thought**
Unlike other redux-persists which allow us to store and retrieve nav state easily, I'm unable to find related docs necessary to implement similar with react-navigation. 
Apologies if my efforts felt short to convince you.

**Comment by matthamil** [comment]
Are you using Redux in your app? If you have integrated Redux with React Navigation, and if you're using redux-persist, you should be able to persist your navigation stack trace. You might need to create a splash screen component that waits for rehydration to complete, then you re-render your root navigator.

**Comment by kwnccc** [comment]
@samartha-kar23 @matthamil I'm facing a relative problem. I'm not yet integrated with redux in my react native application. What I need is a container component (probably custom navigator?) which will handle the addition/removal of an event listener on AppState change. This event listener is needed in order to trigger specific actions when user come back from inactive/background state and don't really want to have it implemented in each screen separately. Though I'm not quite sure which is the best way to implement it with react-navigation. Any ideas?

**Comment by wkoutre** [comment]
This took me a couple days to finally get right with react-navigation and redux in my RN app.

Here's a snippet from my Root.js:

`persistStore(
      store,
      {
        // blacklist: ["logs", "statusMessages", "env"],
        blacklist: ["logs", "statusMessages", "env", "nav"],
        storage: AsyncStorage,
        debounce: 50
      },
      () => {
        this.setState({ rehydrated: true });
      }
    );`

I have a setTimeout on that for 4 seconds, during which I play a splash screen (if app is loaded fof the first time).

My NavReducer looks like this:

`const initialState = AppNavigator.router.getStateForAction(
  AppNavigator.router.getActionForPathAndParams("Login")
);

const NavReducer = (state = initialState, action) => {
  let nextState = AppNavigator.router.getStateForAction(action, state);

  // Return the original `state` if `nextState` is null or undefined.
  return nextState || state;
};`

It takes a split second (during the splash screen) to asynchronously rehydrate the store. My Login component returns null if the user is logged in, with login in componentWIllMount() to navigate appropriately:

`if (loggedIn) {
      if (verified && onboarded) {
        navigation.navigate("Home");
      } else if (verified) {
        navigation.navigate("Onboarding");
      } else {
        navigation.navigate("Verification");
      }
    }
  }`

I DO have `redux-enhancer-react-native-appstate` installed, but haven't yet explicitly used it for any actions just yet.

**Comment by dtyrrell** [comment]
Does anyone have a working example of react-navigation with redux-persist?

What I have now doesn't work when deployed to a real device, debugging this hasn't proved helpful so far.

Symptoms: the buttons/list views are not responding to taps anymore (swipes work)

Same code works on emulator in both debug and release builds.

**Comment by kelset** [comment]
Pinging OP @samartha-kar23 since this issue has not been active for a while, and it's related to an old version of the lib. Moreover, we added a section of the README with guides, articles and examples to fill the need of complex scenarios.

Please let me know if you want this to remain open, because if I get no answer in the next 7 days I will close it.

**Comment by wkoutre** [comment]
@dtyrrell I know this is late, but do you still need an example of react-navigation working with redux-persist?

**Comment by dtyrrell** [comment]
@wkoutre Not anymore I fixed my issue thanks 👍

**Comment by kelset** [comment]
Hi there @samartha-kar23 ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by sagomezza** [comment]
@leimonio Did you find a solution to that case? I'm facing the same issue right now.

**Comment by matthamil** [comment]
@sagomezza this issue was opened 17 months ago and the library has had many changes since then. Please open a new issue if you are wanting to report a bug.
