### ISSUE TITLE
iOS nesting DrawerNavigator inside StackNavigator creates anomaly when popped

### ISSUE THREAD

**Issue by Jasbir23** [react-community/react-navigation#1944]
In my app i have three components inside my main stack navigator, something like this.
```javascript
export default (StackNav = StackNavigator({
  Login: { screen: Login },
  Home: { screen: Home },
  BlankPage: { screen: BlankPage }
}));
```
Now, my **Home** screen is in turn a DrawerNavigator object. When i go-back to previous screen from home screen, the **Sidebar Drawer** component also pops from the stack and looks something like the GIF below. This is not desirable in my app.
I also tried to reset the router when going back from **Home** screen something like this
```javascript
DrawerNav.dispatch(
                  NavigationActions.reset({
                    index: 0,
                    actions: [NavigationActions.navigate({ routeName: "Home" })]
                  })
                );
```
However the same problem persists. Is there a way to get this working?
Thanks in advance :)

![rndrawer](https://user-images.githubusercontent.com/22442136/27321553-417f258c-55b8-11e7-8904-563629689307.gif)

**Comment by morgerardo** [comment]
Hi, i struggled with this as well, this set up did the trick for me

first in you StackNavigator set:

 navigationOptions: {
    gesturesEnabled: false
  }

then in your HomeScreen set: 

const Drawer = DrawerNavigator({
  Home: {
    screen: MyHomeScreen,
  },
  Notifications: {
    screen: MyNotificationsScreen,
  },
});

export default class MyDrawer extends React.Component {
  render () {
    return (
      <Drawer />
    )
  }
}

you may configure you drawer as you desire but export it as part of another class,

**Comment by shivrajkumar** [comment]
@morgerardo That doesn't work.
Here's the example app https://github.com/start-react/native-starter-kit with this issue.

**Comment by SupriyaKalghatgi** [comment]
Any update on this?
I have been waiting for this fix

**Comment by kelset** [comment]
Pinging OP @Jasbir23 since this issue has not been active for a while, and it's related to an old version of the lib. Moreover I think this got fixed via https://github.com/react-community/react-navigation/commit/e6505054bd765f0771aec8c328238b0b4d8ddab9

Please let me know if you want this to remain open, because if I get no answer in the next 7 days I will close it.

**Comment by SupriyaKalghatgi** [comment]
@kelset i will check with latest release
but since it has dependency over RN version, i need to think

**Comment by kelset** [comment]
Hi there @Jasbir23,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
