### ISSUE TITLE
CardStack docs or examples

### ISSUE THREAD

**Issue by JulianKingman** [react-community/react-navigation#1946]
I searched through the examples and documentation, and can't find any examples of CardStack usage. I'm trying to upgrade the `@shoutem/ui` library to pull the CardStack and Card components from this library, since they were deprecated and moved from NavigationExperimental, but can't find any documentation or examples on which to base it on (which would be OK if the API hadn't changed). Could someone point me to a working example of CardStack?

Thanks!

**Comment by kelset** [comment]
Pinging OP @JulianKingman since this issue has not been active for a while, and it's related to an old version of the lib. That said I'm kinda confused; CardStack? You mean a standard Stack or am I missing out on something? 🤔
Moreover, we added a section in the README with links & examples.

Please let me know if you want this to remain open, because if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @JulianKingman ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by JulianKingman** [comment]
Thanks, this can stay closed as the issue was dealt with a different way. My question had to do with using the Card and CardStack views (e.g. here: https://github.com/react-community/react-navigation/blob/master/src/views/CardStack/CardStack.js). Navigation Experimental was absorbed by React Navigation, and Card/CardStack along with it, but with a new API, so I was trying to find examples of their usage.
