### ISSUE TITLE
Question:Any state change refreshes the complete screen

### ISSUE THREAD

**Issue by shashuec** [react-community/react-navigation#1963]
Hi,

I am testing the app on android simulator.Problem I am facing is on each state change it refreshes the complete screen.Is that the intended behaviour or I can disable that?

>     "react-navigation": "^1.0.0-beta.11"
>     "react-native": "0.44.2",

Here is the StackNavigator code I am using.
I have the following code:

```
const Route = StackNavigator({
  Login: { screen: Login ,
    navigationOptions: {
      header: null,
    }
  },
  NewUserScreen: {
    screen: NewUserScreen,
    navigationOptions: {
      title: 'New User Details'
    }
  },
  EditProfile: {
    screen: EditProfile,
    navigationOptions: {
      title: 'Edit Profile',
    }
  }
  }, {
  // Default config for all screens
  //headerMode: 'screen',
  initialRouteName: 'Login',
  navigationOptions: {
    headerStyle: styles.header,
    headerTitleStyle: styles.title,
    headerLeft: null

  }
});
```

**Comment by kelset** [comment]
Pinging OP @shashuec  since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @shashuec ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
