### ISSUE TITLE
Can't Avoid one frame delay using TabNavigator

### ISSUE THREAD

**Issue by jasan-s** [react-community/react-navigation#1967]
In react-native-tab-view you can pass in a initialLayout prop to avoid the single frame delay in rendering. 
Passing in a initialLayout  prop does not work. 

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.45.1

**Comment by seantimm** [comment]
We were experiencing an offset, duplicate render (like seeing double) due to this same issue.  As soon as we specified an initialLayout with an actual width, the problem went away.

Also see https://github.com/react-native-community/react-native-tab-view/issues/297

**Comment by kelset** [comment]
Pinging OP @jasan-s since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @jasan-s ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
