### ISSUE TITLE
TabBarComponent lifecycle function is not called

### ISSUE THREAD

**Issue by danqing-jin** [react-community/react-navigation#1977]
### Current Behavior

'use strict';

import {TabBarBottom} from 'react-navigation';

export default class HomeTab extends TabBarBottom {
  constructor(props) {
    super(props);
  }

  componentWillMount() {
    console.log("in tab bar will mount");
  }
};

tabBarOptions: {
    tabBarComponent: HomeTab,
}

### Expected Behavior

I am expecting componentWillMount for my HomeTab is called. But in reality, it is not called.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  0.42.3
| node             | 8.1.0
| npm or yarn      | 5.0.3

**Comment by spencercarli** [comment]
Can you provide a running example of your issue?

**Comment by kelset** [comment]
Hi there @danqing-jin,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
