### ISSUE TITLE
How To Stop The Drawer View From Closing When The View Behind Drawer Re-Renders

### ISSUE THREAD

**Issue by Mimble-Wimble** [react-community/react-navigation#2016]
### Current Behavior
As of right now I have a view that is refreshing/re-rendering every 10 seconds. If however the drawer is toggled open it is immediately closed when the view refreshes/re-renders.

### Expected Behavior
Is there a way to allow the view to continue to re-render without closing the Drawer menu when it is open?

**Comment by spencercarli** [comment]
Please provide an example of this issue so we can help. Thanks!

**Comment by kelset** [comment]
Hi there @Mimble-Wimble,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
