### ISSUE TITLE
How I can access screen propery passed by screen wrap container in navigationOptions create function

### ISSUE THREAD

**Issue by oxape** [react-community/react-navigation#2025]
How I can access component property logout in navigationOptions create function. Can't access instance “this” in static variable.

```
const mapStateToProps = (state, ownProps) => {
    return state;
};

const mapDispatchToProps = (dispatch, ownProps) => {
    return {
        logout: () => {
            dispatch(logoutAction());
        },
        navigateInput: () => {
            dispatch(NavigationActions.navigate({ routeName: 'Input' }));
        },
    }
};

const ScanContainer = connect(
    mapStateToProps,
    mapDispatchToProps
)(ScanPage);

export default ScanContainer
```
Component
```
class ScanPage extends Component {

    static navigationOptions = (props) => {
        console.log(props);
        console.log(this.props);
        return {
            title: 'Scan',
            headerRight: (
                <Button title='logout' onPress={() => {console.log(props); console.log(this.props);}}/>
            ),
        }
    }
}
```
this.props is undefined.
My Navigator
```
const HomeNavigator = StackNavigator({
    Scan: { screen: ScanContainer },
    Input: { screen: InputContainer },
});
```
Although I can use the following method. But I think it is not enough elegant.Exposed the actions to the component.
```
    static navigationOptions = ({ navigation }) => {
        return {
            title: 'scan',
            headerRight: (
                <Button title='logout' onPress={() => {navigation.dispatch(logoutAction());}}/>
            ),
        }
    }
```

Similar, How do I access this.state in navigationOptions.

| software         | version
| ---------------- | -------
| react-navigation |  ^1.0.0-beta.11
| react-native     |  0.44.2
| node             |  6.2.0
| npm or yarn      | npm 3.8.9 yarn 0.24.5

**Comment by iridiumsoft** [comment]
In ScanPage component you need to add constructor with props, like this
`constructor(props){
   super(props);
}`

That will do ths job

**Comment by valetarton** [comment]
@oxape 
In programming when a property or a method is defined in a class as "static" it has no concept of "this", because it can be accessed publicly without being instantiated.

That being said, I have needed this solution as well for my own project.
The WORK AROUND I used is thus
in componentDidMount() 
`this.props.navigation.setParams({what_you_need: this.function_name})`
at this point this. will have access to all your functions defined
after which the static navigationOptions will be called again, you would then check for your params and set whatever callbacks you'd need for a button.

If there is a better way of doing this I'd absolutely would love to know, but for my needs this sufficed, even though it wastes a cycle.

Good luck!
