### ISSUE TITLE
Calling setState() on a screen does not appear to work after closing and reopening it

### ISSUE THREAD

**Issue by tenal** [react-community/react-navigation#2040]
### Current Behavior
I have a screen that is opened via StackNavigation and utilizes setState() throughout the code. When I open this screen for the first time, it works fine and the respective components update seamlessly. However, all of this stops working when I close this screen and reopen it on the screen prior.

### Expected Behavior
Instead of proceeding to behave like it did the first time, setState() is not called, and subsequently the components attributed to the state variables are not updated. It should work every single time based on how it did the first time.

### Your Environment
| software         | version
| ---------------- | -------
| react-navigation |  latest
| react-native     |  0.44.0
| node             | 7.10.0
| npm or yarn      | npm@4.2.0

**Comment by dunhuang** [comment]
where did you write the setState() code?

**Comment by spencercarli** [comment]
Please provide an example of this issue. Thanks!

**Comment by kelset** [comment]
Hi there @tenal,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
