### ISSUE TITLE
png to svg

### ISSUE THREAD

**Issue by shashkovdanil** [react-community/react-navigation#2077]
I would like to replace the icons in the assets from png to svg (react-native-svg). What do you think about it?

**Comment by matthamil** [comment]
I don't think this would be a good change since this requires an added dependency to the library. If using react-native-svg with .svgs suits your use case, you should use a forked version of react navigation. I'm not a fan of adding react-native-svg as a dependency for a few reasons:

1. Doesn't improve the navigation experience for a significant amount of use cases

1. Requires linking or manual installation

1. Differences in minor updates to react-native-svg [only support specific RN versions](https://github.com/react-native-community/react-native-svg#notice).

If you do think this would be a good change, you're welcome to open a PR with the change and include a write up about your motivation behind the change.
