### ISSUE TITLE
TabNavigator tabs disappear from view 

### ISSUE THREAD

**Issue by AlmogRnD** [react-community/react-navigation#2089]
I'm using TabNavigator and I have one view which should be part of the home view, i.e. team view and when a load that view I would still like to keep the tabs showing on that view however they disappear. 

Home view 
<img width="382" alt="screen shot 2017-07-07 at 5 37 41 am" src="https://user-images.githubusercontent.com/169507/27958113-71467dee-62d6-11e7-8bf8-ae53ccd39dd1.png">

Selecting an item from the list loads the team view this is where I lose the tabs 
<img width="396" alt="screen shot 2017-07-07 at 5 38 33 am" src="https://user-images.githubusercontent.com/169507/27958142-8a9e61bc-62d6-11e7-8feb-2b5b2cd9a438.png">

Here is my router code 
```
// Drawer Navigation
export const MainDrawerNavigator = DrawerNavigator({
    Home: {
        screen: Home,
        navigationOptions: {
            drawer:{
                label: "Home",
            }
        },
    },
    Logout: {
        screen: Logout,
        navigationOptions: {
            drawer:{
                label: "Logout",
            }
        },
    }
});

// Native tab navigation
export const TabsNavigation = TabNavigator({
    Home: {
        screen: Home,
        navigationOptions: ({ navigation }) => ({
            tabBarLabel: 'Home',
            title: "Home",
            //TODO: work in progress
            //headerLeft : <DrawerIcon navigation={navigation} />,
            tabBarIcon: ({ tintColor }) => <Icon name="home" size={28} color={tintColor} type={"font-awesome"} />
        }),
    },
    Photos: {
        screen: Photos,
        navigationOptions: {
            tabBarLabel: 'Photos',
            title: "Photos",
            tabBarIcon: ({ tintColor }) => <Icon name="camera" size={28} color={tintColor} type={"font-awesome"} />
        },
    },
    SiteDiary: {
        screen: SiteDiary,
        navigationOptions: {
            tabBarLabel: 'Site Diary',
            title: "Site Diary",
            tabBarIcon: ({ tintColor }) => <Icon name="cog" size={28} color={tintColor} type={"font-awesome"} />
        },
    },
});

// Main navigation StackNavigator
export const MainScreenNavigator = StackNavigator({
    Home: {
        screen: TabsNavigation
    },
    Teams: {
        screen: Teams,
    },
    Drawer: {
        screen: MainDrawerNavigator
    }
});


// Main public nav
export const AppNavigator = StackNavigator({
    Login: {
        screen: Login,
        navigationOptions: {
            title: "Login",
            headerLeft: null,
        },
    },
    ResetPassword: {
        screen: ResetPassword,
        navigationOptions: {
            title: "Reset Password",
            headerLeft: null
        },
    },
    Main: {
        screen: MainScreenNavigator,
        navigationOptions: {
            header:null,
            gesturesEnabled: false,
        }
    }
});
```

**Comment by townmulti** [comment]
Similar issue here also. When using TabNavigator in root component, no tabs appear.

```
class App extends React.Component {
  render() {
    const MainNavigator = TabNavigator({
      welcome: { screen: WelcomeScreen },
      auth: { screen: AuthScreen }
    });  
    return (
      <View style={styles.container}>
        <MainNavigator />
      </View>
    );
  }
} 
```

**Comment by matthamil** [comment]
The reason your tabs disappear is because you are navigating away from your TabNavigator to another screen on `MainScreenNavigator`. If you want the tabs to remain on the screen, you will need that tab screen to be a StackNavigator with a route to the new screen. 

I'm going to use an example to illustrate what's happening with your approach:

Scenario A (similar to your setup)
```
 StackNavigator
    - TabNavigator
        - Home
        - Friends
    - InviteAFriend
```

In Scenario A, if I was on `Home` and navigated (`this.props.navigation.navigate('InviteAFriend')`) to `InviteAFriend`, the StackNavigator would push `InviteAFriend` onto the stack. Since the TabNavigator and the InviteAFriend screens are on the same level in the navigation hierarchy (both being routes for StackNavigator), the InviteAFriend screen will *not* render with tabs.

Scenario B
```
TabNavigator
    - HomeStack
    - FriendsStack
        - Invite a Friend
```

In Scenario B, if I was on `Friends` and navigated to `InviteAFriend`, the FriendsStack would push the InviteAFriend screen onto its navigation stack. Since FriendsStack is inside the TabNavigator, the tabs from the TabNavigator will remain on the screen. This will achieve the affect you are looking for.

**Comment by AlmogRnD** [comment]
I'm closing this, I'm moving onto react-native-router-flux it's much better and uses the react navigation API 

- Based on latest React Navigation API
- Separate navigation logic from presentation. You may change now navigation state directly from your business logic code - stores/reducers/etc. navigationStore
- Built-in state machine (former Switch replacement) - each ‘scene’ could have onEnter/onExit handlers. onEnter handler could be async. For successful termination of onEnter, success handler (if defined) will be executed (if success is string then router will navigation to that Scene), in case of handler's failure failure (if defined) will be run. It will allow to build authentication, data validation and conditional transitions in very easy way.
- MobX-powered, all used scenes are wrapped as 'observer' automatically. You may subscribe to navigationStore (former Actions), observe current navigation state, etc. If you are using Redux, skip this.
- Flexible nav bar customization, that is not allowed by react navigation right now: https://github.com/react-community/react-navigation/issues/779
- Drawer support (provided by reactnavigation)
- 'Lightbox' support (used by popups like Error alert within Example project)

**Comment by preyesm** [comment]
@matthamil 
My issue is 
StackNavigator
    - TabNavigator
        - Home
             -StackNavigator
                 ----Screen A
                 ----Screen B
        - Friends

In this setup, Screen A is  is default on when the home tab is loaded which has the tabs  visible, but when i click on the screen B my tabs disappear any help on this kind?

**Comment by joncursi** [comment]
@matthamil the other big problem here is that what if you want `InviteAFriend` to be accessible from any tab? This doesn't seem to be possible today with react navigation, because you can only define that screen underneath a specific tab :/

**Comment by barathkb** [comment]
The Tab navigator is not visible when I come back to the Same Screen... 
I am in Screen A which has the TabNavigator i got to Screen B which is not within the scope of Tab Navigator and when i come back to Screen A from Screen B Tab Navigator is not visible or not being shown.

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
