### ISSUE TITLE
fixed fontsize and header text

### ISSUE THREAD

**Issue by saeropark** [react-community/react-navigation#2102]
Hi I am wondering is there a way to fix font size. 

This is because during testing, those users that i have who increased text size on their iphone cannot see the full header text and tab text as it gets cut off. 

I have specifically stated fontsize:16 on my navigationOptions but it seems the phone text size will override the app. 

is anyone able to help?

**Comment by spencercarli** [comment]
Reproduction steps would help in this! No doubt this is an issue but step-by-step instructions on how to reproduce would be very helpful

**Comment by saeropark** [comment]
i forgot i had created this issue, but i sort of found the way #2377 however, it still requires to touch the source code. Will be great if it is a future feature.

**Comment by kelset** [comment]
Pinging OP @saeropark since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @saeropark ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
