### ISSUE TITLE
React native navigation class function in header with nested tabs

### ISSUE THREAD

**Issue by poptocrack** [react-community/react-navigation#2108]
I've got a problem with react native navigation and nested navigators.

### Current Behavior
in the Players tab:
onPress the save Button, it throws me a undefined isn't a function (params.handleSave)
in the Teams tab:
onPress write on the console output and everything is fine

### Expected Behavior
On both tabs:
onPress write on the console output and everything is fine

### Your Environment
Working with Expo, android 6+ Galaxy S7

| software         | version
| ---------------- | -------
| react-navigation |  ^1.0.0-beta.11
| Expo     | SDK 18 
```
class HomeScreen extends React.Component {
  static navigationOptions = ({ navigation }) => {
    const { params = {} } = navigation.state;
    return {
        headerRight: <Button title="Save" onPress={() => 
        params.handleSave()} />
    };
  };

  _saveDetails() {
    console.log('clicked save');
  }

 componentDidMount() {
   this.props.navigation.setParams({ handleSave: this._saveDetails });
 }

 render() {
    return (
        <View />
    );
  }
}

const MainScreenNavigator = TabNavigator({
  Players: { screen: HomeScreen},
  Teams: { screen: HomeScreen},
});

const SimpleApp = StackNavigator({
  Home: { screen: MainScreenNavigator },
  Player: { screen: PlayerPage },
});
```

**Comment by chintochau** [comment]
I've got the same problem, setParams of the second tab will wipe params of the first tab.

**Comment by valeriaabo** [comment]
How can I solve this? Same issue.

**Comment by darulAbror** [comment]
try this one...

https://stackoverflow.com/questions/44999498/react-native-navigation-class-function-in-header/46610050#46610050

may help you

**Comment by kelset** [comment]
Pinging OP @poptocrack since this issue has not been active for a while, and it's related to an old version of the lib. If you have issues related to setParams I suggest you read in the docs how to handle the [SaveButton](https://reactnavigation.org/docs/intro/headers#Header-interaction-with-screen-component) or refer to this issue https://github.com/react-community/react-navigation/issues/2931

Please let me know if you want this to remain open, because if I get no answer in the next 7 days I will close it.

**Comment by poptocrack** [comment]
Feel free to close it, I've done things differently. Thanks.

**Comment by fuxianwei** [comment]
+1
