### ISSUE TITLE
How to make tab header labels that flex and don't wrap?

### ISSUE THREAD

**Issue by stevengoldberg** [react-community/react-navigation#2112]
I'm trying to use `TabNavigator` to create tab labels of different widths. I don't want the label text to wrap onto more than one line, and I don't want the label to ellipsify.

When I provide `tabBarLabel` as a static field on my screen and I assign it to a string, a long tab label will wrap to multiple lines:

![image](https://user-images.githubusercontent.com/2230992/28009057-9d8a53f8-651f-11e7-9be7-d10afc90a40d.png)

If I assign `tabBarLabel` to a function that returns a `Text` component with `numberOfLines={1}`, the text doesn't wrap, but it does ellipsify:

![image](https://user-images.githubusercontent.com/2230992/28009114-d60eb5e8-651f-11e7-877a-bacbef4d0769.png)

I want the text to stay on one line and for the tab to grow to accommodate the label text. I've tried playing with the `tabStyle` and `labelStyle` keys in `tabBarOptions`, but haven't found a solution. How can I make this work?

**Comment by matthamil** [comment]
You can supply your own [tabBarComponent](https://reactnavigation.org/docs/navigators/tab#TabNavigatorConfig) that renders custom tabs.

**Comment by stevengoldberg** [comment]
Thanks for the reply @matthamil -- I looked into passing a custom `tabBarComponent`, but saw that the `TabBarTop` component uses `TabBar` from the `react-native-tab-bar` lib, and I was hoping there'd be a way to solve this issue without recreating all of the functionality in that library.

Do you have any suggestions on what the custom component would look like in order to solve this issue?

**Comment by riugduso** [comment]
@stevengoldberg u can just truncate the long text of tab like following:
`
navigationOptions: {
          tabBarLabel: originText.length>10 ?
            originText.substr(0, 8).concat('…') :
            originText,
        }
`

**Comment by YasirPanjsheri** [comment]
Hi, how about making it responsive! I have 4 tab and even though each is labeled with one word, yet it gets wrapped on a smaller screen size, is there a way to go about this ?

**Comment by arfianadam** [comment]
I also really like to know how to accomplish this. The main thing about the dynamic width is not about the label container, but the indicator on the bottom. I peek into the default component and the current calculation (for the position, animation, etc) is based on static tab width. So in order to implement this is you need to extend the component and replace all those methods with your own. Surely this is gonna be exhausting.

**Comment by shukla12manish** [comment]
I am also facing the same issue. The tab labels are getting wrapped on smaller screen. Kindly help.

**Comment by shukla12manish** [comment]
I also applied ellipsizeMode:'tail' and numberofLines:1 in labelStyle but nothing happened.

**Comment by kdastan** [comment]
@stevengoldberg did you solve this issue ?

**Comment by satya164** [comment]
You can specify your own `renderLabel` prop in `tabBarOptions`, or make the tab bar scrollable with `scrollEnabled: true`. But note that Material design guidelines recommend breaking the label into multiple rows instead of hiding a part of it https://material.io/guidelines/components/tabs.html#tabs-content. If you need to hide part of the label, maybe you should have a smaller label, because otherwise, it's difficult for the user to know what's in the tab when part of the label is hidden.

**Comment by maharjanaman** [comment]
Any solution to this??? Stuck on this for days :disappointed:

**Comment by kamalpandey** [comment]
Any progress on this?? Please share
