### ISSUE TITLE
is need to provide other position of tabbar  like' left' ro 'right' for develop pad

### ISSUE THREAD

**Issue by bestlbw** [react-community/react-navigation#2141]
in order to develop better for pad ,can provide more tabbarposition like ‘left’ or ‘right’ in TabNavigator，
![image](https://user-images.githubusercontent.com/23213008/28202347-7b417b92-68a7-11e7-9851-ace37c5603d1.png)

**Comment by spencercarli** [comment]
Is this a common pattern on the ipad?

**Comment by tavriaforever** [comment]
Usually on Ipad menu put in the sidebar like on screenshot. Screens change, but tabbar stands on the same position without transition. So possibility to change tabbar position to left/right would be very convenient. 

If you know how to make this tabbar on Ipad in another why it would be great info.

![2017-09-13_16-44-50](https://user-images.githubusercontent.com/975906/30380714-f73ebd74-98a2-11e7-95b3-43c85b8099cf.png)

**Comment by SteffeyDev** [comment]
That looks like a split view with a UITableView on the left and a normal view on the right, Tab Bars on iOS are always on the bottom.  You could make this effect in your own app by switching to a drawer layout or custom view perhaps when the orientation changes.

**Comment by kelset** [comment]
Pinging OP @bestlbw since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

Moreover I think, as @SteffeyDev says, that you are trying to use a tabbar for something it is not designed for.

**Comment by kelset** [comment]
Hi there @bestlbw ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by tavriaforever** [comment]
Thanks!
