### ISSUE TITLE
STATUSBAR_HEIGHT for Android

### ISSUE THREAD

**Issue by efkan** [react-community/react-navigation#2164]
I use Android Emulator (Nexus 5X with API 23) and my component is seemed as swiped to below for 25 px.

If I'm right, [at this line](https://github.com/react-community/react-navigation/blob/b310b153fd76edd27ecbf4d6d2d71ead1d33a530/src/views/Header.js#L37) `25` should be assigned to `STATUSBAR_HEIGHT` value for Android.

**Comment by kelset** [comment]
Pinging OP @() since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

Moreover I think it's a duplicate of https://github.com/react-community/react-navigation/issues/12

**Comment by kelset** [comment]
Hi there @efkan ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
