### ISSUE TITLE
Race Condition in reset NavigationActions method

### ISSUE THREAD

**Issue by yeknava** [react-community/react-navigation#2165]
### Current Behavior

when calling navigation NavigationActions.reset for first time in app shows screen with index 0 for a moment and then desire screen. steps:
1. app loads first screen
2. after hitting login button app loads second screen. (with navigate method)
3. user hitting another button to see third screen.
4. for a moment i see first screen and then third screen.
```jsx
NavigationActions.reset({index: 0,[NavigationActions.navigate({ routeName: 'thirdScreen'})]})
```
i use StackNavigator with redux.
### Expected Behavior
rest stack without showing index zero screen.

### Your Environment
| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.46.2

**Comment by jedrichards** [comment]
As far as I can reset is massively buggy in the current version (`1.0.0-beta.12`). Just search the issues there's loads related to bugs and people confused about resetting the navigation stack.

**Comment by kelset** [comment]
Pinging OP @yeknava since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @yeknava ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
