### ISSUE TITLE
Changing transition animation when transitioning between TabNavigator screens

### ISSUE THREAD

**Issue by PhillipWinder** [react-community/react-navigation#2202]
Hey guys,

as of now we can set 

    animationEnabled: boolean

in the TabNavigatorConfig of a TabNavigator. The default animation is sliding the new screen in from left/right. 

How can I change this animation to for example fade in/fade out instead of sliding?

**Comment by davidtrogers** [comment]
I've been looking for this feature too and I noticed [the docs](https://reactnavigation.org/docs/navigators/tab#TabNavigatorConfig) don't have it as an option so I did some digging:

Because react-navigation uses [TabViewAnimated from react-native-tab-view](https://github.com/react-community/react-navigation/blob/v1.0.0-beta.12/src/views/TabView/TabView.js#L5) under the hood and because [it's possible to add a `configureTransition` prop for TabViewAnimated](https://github.com/react-native-community/react-native-tab-view/issues/173) [(which passes configureTransition to TabViewPagerPan anyway)](https://github.com/react-native-community/react-native-tab-view#tabviewanimated-), we could pass a `configureTransition` prop to [`TabViewAnimated`](https://github.com/react-community/react-navigation/blob/v1.0.0-beta.12/src/views/TabView/TabView.js#L171) and EverythingShouldWork™.

I'll try to put together a PR in the next few days unless someone beats me to it.

**Comment by davidtrogers** [comment]
@PhillipWinder easier than I thought it would be!

**Comment by PhillipWinder** [comment]
@davidtrogers thanks! How long do you think will it take to merge?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by davidtrogers** [comment]
@spencercarli hi! can we re-open this issue again?  It is actually not a question but a feature request for which I've supplied a PR #2222 . I've *finally* updated the branch and I think it is ready to merge if you are open to it.

**Comment by spencercarli** [comment]
Hey @davidtrogers  - I would merge it, but you PR was actually merged already and shipped in beta.20! Thanks for your contribution 😄
