### ISSUE TITLE
Question: Differences from ex-navigation

### ISSUE THREAD

**Issue by JulianKingman** [react-community/react-navigation#221]
I'm curious about the changes made from the ex-navigation package, specifically I'm a little baffled by the move away from components for navigation, it seemed much more intuitive and made certain things very clear. Do you have information anywhere on the reasoning behind some of the changes?

In case it's not obvious what I mean, this (before):
````jsx
<SlidingTabNavigation {...things}>
  <SlidingTabNavigationItem {...moreThings}>
    {content}
  </SlidingTabNavigationItem>
</SlidingTabNavigation>
````

as opposed to this (after):
````jsx
MainTabNavigation = TabNavigator({
  ...routes
},{
  ...config
});
<MainTabNavigation screenProps={...things} {...noMoreThings}/>
````

**Comment by satya164** [comment]
I won't say `ex-navigation` made things very clear. We couldn't do optimisations without causing confusion (https://github.com/exponent/ex-navigation/issues/397#issuecomment-277877579). It was also not possible to build tooling around it since you can't statically analyse the navigators.

> specifically I'm a little baffled by the move away from components for navigation

They are still components. You just define them differently. Think of how you use redux's `connect` differently, but it's still a component.

**Comment by grabbou** [comment]
For the rest of the changes, apart from what @satya164 has outlined, please follow this thread https://github.com/react-community/react-navigation/issues/37#issue-203664999 where we work on migration guides and show how to upgrade apps.
