### ISSUE TITLE
Adding  accessibilityLabel to tabNavigator? 

### ISSUE THREAD

**Issue by momoDeako** [react-community/react-navigation#2214]
I would like to add  accessibilityLabel to all my tabs, is there any way to currently accomplish this? 

If not, I would be interested to contributing for this merge. If anyone else is working on this, please let me know.

**Comment by momoDeako** [comment]
Here is what I'm thinking what the interface looks like: 
Any feedback would be appreciated

`   Recent: { screen: RecentChatsScreen,
        navigationOptions: {
        accessibilityLabel: "Recent",
        title: "Recent",
    }},`

**Comment by kelset** [comment]
Pinging OP @momoDeako since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @momoDeako ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
