### ISSUE TITLE
Route XXXX should declare a screen Error.

### ISSUE THREAD

**Issue by Ravenclaw968** [react-community/react-navigation#2229]
https://gist.github.com/Ravenclaw968/00a7019dde813b8943491c6642524172

I have the code above and I get this error below.

https://www.dropbox.com/s/7nn0y0twwd6aewd/Photo%20Jul%2023%2C%202%2031%2031%20PM.png?dl=0

I tried moving the SimpleApp variable before the HomeScreen class, but I get the same error but instead of "User," it says "Home"

How would I go about fixing the problem?

**Comment by valetarton** [comment]
@Ravenclaw968 
I would first ensure your UserScreen file when you import it is actually exporting a class. (im sure it is, though I cant tell you how many times I set everything up and for get to export default)

My second suggestion would be instead of calling "export default " on the class and then declaring the const "after" 
make it a regular ol class and "export default" after your const. I know const gets hoisted in javascript, but just my paranoid brain.

**Comment by Ravenclaw968** [comment]
Thanks!
