### ISSUE TITLE
an error found in the Transitioner example

### ISSUE THREAD

**Issue by linjiajian999** [react-community/react-navigation#2243]
### Current Behavior

this is my setting
``` jsx
<Transitioner
   configureTransition={this._configureTransition}
   navigation={this.props.navigation}
   render={this._render}
   onTransitionStart={this.onTransitionStart}
   onTransitionEnd={this.onTransitionEnd}
/>
```
the same as [Transitioner doc](https://reactnavigation.org/docs/views/transitioner)

then there is a prompt that " cannot read property 'forEach' of undefined "
in ScenesReducer.js 99:19
``` javascript
nextState.routes.forEach
```
 I log the "nextState" is
``` javascript
{
  key: "id-1501060202060-2",
  params: undefined,
  routeName: "Index"
}
```
so that i found the props 'navigation' of Transitioner need the property 'index' and 'routes'
[navigation prop](https://reactnavigation.org/docs/views/transitioner#navigation-prop)

Is the example [Transitioner doc](https://reactnavigation.org/docs/views/transitioner)  wrong?
###  Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.44.3
| node             | 7.10.0
| npm       | 4.2.0

**Comment by kateray** [comment]
Ah, I just ran into this too. Is there an example of how to set up Transitioner that you've found that works?

**Comment by Empact** [comment]
I'm seeing this error outside the context of a transitioner.

**Comment by kelset** [comment]
Pinging OP @linjiajian999  since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @linjiajian999 ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by linjiajian999** [comment]
@kelset okay. I will test it again in the new version and give the relevant report later.

**Comment by NickDelfino** [comment]
Has anyone else fixed this nextstate.routes.foreach issue? I opened up a stackoverflow post just now for what I believe is the same problem as everyone here: https://stackoverflow.com/questions/47848999/redux-with-react-navigation-nested-navigators-typeerror-undefined-is-not-an-ob

I think it is definitely because of the nested navigators but I am unsure how to resolve the issue.

Any luck finding anything?

**Comment by gaurav-pantelwar** [comment]
@NickDelfino any luck?  cuz i am getting the same issue.

**Comment by NickDelfino** [comment]
@gaurav-pantelwar I'll be honest I gave up on the navigation redux store integration for now. I am instead passing a navigation reference to the actions that need it to navigate. 

This probably isn't the best long term solution but it is working as I want it to. I hope in the future react-navigation will support these nested navigator systems more clearly.
