### ISSUE TITLE
Reset from nested navigator-with-props

### ISSUE THREAD

**Issue by stereodenis** [react-community/react-navigation#2274]
> action - Object - Optional - (advanced) The sub-action to run in the child router, if the screen is a navigator. Any one of the actions described in this doc can be set as a sub-action.

When screen is function, that returns navigator — resetting is not working
```
const MainNavigator = StackNavigator({
  Main: {
    screen: ({ navigation, screenProps }) => (
      <MyStackNavigator screenProps={{ ...screenProps, rootNavigation: navigation }} />
    )
    //screen: MyStackNavigator <-- works

  }
})

const resetAction = NavigationActions.navigate({
  routeName: 'Main',
  action: NavigationActions.navigate({ routeName: 'SubRoute', params: { params } }),
})
this.props.screenProps.rootNavigation.dispatch(resetAction)
```
### Current Behavior
not resetting to SubRoute
### Expected Behavior
resetting to SubRoute
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.12
| react-native     |  0.43.4
| node             | v8.1.3
| npm or yarn      | 0.27.5

**Comment by spencercarli** [comment]
If you try the following setup, does it work?

```javascript
const MainNavigator = StackNavigator({
  Main: {
    screen: (props) => (
      <MyStackNavigator {...props} />
    )
    //screen: MyStackNavigator <-- works

  }
})
```

Notice how I'm passing the props direction vs. on `screenProps`. Does that allow your usecase to continue to work?

**Comment by quadsurf** [comment]
For me it does not... my issue is that I am resetting from a child component that is not registered to any Stack (nor should it be registered to/in Stack) because this child component is not a screen. So when I dispatch the reset action, I get the following error:

> Cannot get config because the route does not have a routeName

Well of course it can't get "config" because it's not registered on Stack... it's not a route, it's a nested child component, and I don't have the option of sending it up to its parent route.

This is a bug in my opinion, because 'reset' should have a default outcome if no config exists.

**Comment by kelset** [comment]
Pinging OP @stereodenis since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @stereodenis ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
