### ISSUE TITLE
Normal for initalRoute to always mount before the actual navigated route?

### ISSUE THREAD

**Issue by csumrell** [react-community/react-navigation#2289]
I have a few stacknavigators nested inside a drawer. 

``````````
const TrackerStack = StackNavigator({
  Home: { screen: HomeScreen },
  Settings: { screen: SettingsScreen },
  Progress: { screen: ProgressScreen },
  Add: { screen: AddScreen}
});

//Put all Individual Stacks into a Drawer
const HomeScreenRouter = DrawerNavigator(
  {
    Stack1: { screen: TrackerStack },
    Stack2: { screen: Stack2Screen },
    Stack3: { screen: Stack3Screen },
  },
  {
    contentComponent: props => <SideBar {...props} />
  }
);
`````````````
In some stacks, you can navigate to any of the pages without having to view the initial route. For example, in the side drawer you can click on any of the items on the TrackerStack (Home, Settings Progress, Add). However, when i navigate to any of the pages besides the default inital "Home", the home page will be mounted and then the actual navigated route will mount. 

Is this normal behavior for a stack navigator? Is there any way to not have the inital route mount before?

**Comment by spencercarli** [comment]
Does the home screen visibly show or is it just in the state? A running example of this would be very helpful.

**Comment by vonovak** [comment]
@csumrell does this work for you? https://github.com/react-community/react-navigation/issues/2621#issuecomment-338557276

**Comment by kelset** [comment]
Hi there @csumrell,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since Spencer's and Vojtech's last comments I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
