### ISSUE TITLE
There is no way to reset a parent's navigationOptions when navigating back in the StackNavigator

### ISSUE THREAD

**Issue by jsteiner** [react-community/react-navigation#2309]
My goal is to always render a specific screen with a specific set of header styles. There is seemingly no way to achieve this with the current API, but apologies if I've missed something.

Here's the current behavior:

`ScreenA` sets the header's background color to _red_:

```
class ScreenA extends React.Component {
  static navigationOptions = ({ navigationOptions }) =>
    _.merge(navigationOptions, {
      headerStyle: {
        backgroundColor: "red",
      },
    });
}
```

You navigate to `ScreenB`, which sets the background color to _blue_:

```
class ScreenB extends React.Component {
  static navigationOptions = ({ navigationOptions }) =>
    _.merge(navigationOptions, {
      headerStyle: {
        backgroundColor: "blue",
      },
    });
}
```

When you press "Back" on `ScreenB`, `ScreenB` is dismissed, but the `navigationOptions` function is not called on `ScreenA` (probably because the screen was still active behind `ScreenB`). This means that the `backgroundColor` for `ScreenA` is now _blue_ as a consequence of navigating to `ScreenB`.

I looked and couldn't find any lifecycle hooks or way for me to guarantee that any time you see `ScreenA` it would render with a specific style.

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11

**Comment by spencercarli** [comment]
Hey @jsteiner - this makes sense and should be fixed. It would help a lot if you could provide a running example of this! Thanks

**Comment by kelset** [comment]
Pinging OP @jsteiner since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

Moreover, this it actually possible, read this issue: https://github.com/react-community/react-navigation/issues/2818

**Comment by kelset** [comment]
Hi there @jsteiner ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
