### ISSUE TITLE
mode prop for Screen

### ISSUE THREAD

**Issue by nihgwu** [react-community/react-navigation#232]
Right now `mode` is only available for `StackNavigatorConfig`and only accepts a string, so all the `Screen`s in it are with the same transition mode, if we want different modes between views, we need to define different `Navigators` and nest them, which makes things complex, so I have the following propose:
1. add `mode` to `Screen Navigation Options`
2. make `mode` accepts a function

Any ideas?  I'd love to send a PR to implement

**Comment by satya164** [comment]
Feel free to send a PR moving `mode` to `navigationOptions` and deprecate in `StackNavigatorConfig`

We also need to deprecate `visible` prop. Make sure to post a video of what happens when one two consecutive screens have different modes.

> make mode accepts a function

Why do you need it to be a function?

**Comment by nihgwu** [comment]
If `mode` could be a function, then we can keep `mode` in `StackNavigatorConfig`, and config the `mode` here according the router state or params

But I think the first option is more sensible

**Comment by ericvicenti** [comment]
I haven't done this in the past because it causes some visual issue in comparison to navigator nesting.

Here's an example. Say I have a stack with a modal on top of a card. When the modal animates back to he card, the modal looks fine but the card still has the card movement, which means it is slightly offscreen to the left, and as the modal dismisses it moves back to the center of screen.

The issue is fixable, but we need to be careful as we make big changes to CardStack, which is arguably the most complicated part of the codebase.

**Comment by nihgwu** [comment]
I have a workaround for this https://github.com/nihgwu/react-native-dva-starter#advance, but this will introduce nested navigator issues

**Comment by jeffreymendez1993** [comment]
Is this actively being worked on?

**Comment by ericvicenti** [comment]
For now, you can use this hack to easily support both types of screen inside of one navigator:

https://github.com/react-community/react-navigation/issues/707#issuecomment-293748852

It would be a huge change to add this feature as a navigation option, and we are trying to stabilize for v1. @nihgwu, if you have an idea for a simple implementation that doesn't cause lots of regressions, feel free to open a new issue and tag me.

**Comment by 18234068849** [comment]
![image](https://user-images.githubusercontent.com/25168008/48362878-98c5de80-e6df-11e8-9563-cc33f222e78c.png)
