### ISSUE TITLE
Proposal: Change type of laziness in TabNavigator (lazy prop)

### ISSUE THREAD

**Issue by shilch** [react-community/react-navigation#2321]
This is a proposal to change the way how the TabNavigator / TabView pre-renders the tab screens:

### Current Behavior
Currently we have the option `lazy` that tells whether to render every component when needed or to render every component beforehand. When setting `lazy` to `true` you can see the components rendering while swiping.

### Expected Behavior
I expected that lazy works the way the ViewPager on Android does: for every tab it renders the left and the right tab beforehand so that they are instantly available when swiping.

### Your Environment
| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.47.1

**Comment by kelset** [comment]
Pinging OP @shilch since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

Moreover, I think this FR should be actually open on `react-native-tab-view`

**Comment by shilch** [comment]
This proposal is 4 months old now. I do not know if the library was updated in the meantime. My App still uses the 1.0.0-beta.11 version. Will check this in the next days.

**Comment by kelset** [comment]
> I do not know if the library was updated in the meantime.

There have been [10 releases](https://github.com/react-community/react-navigation/releases) and we're gonna do another one hopefully this coming week.

Please let me know after you check.

**Comment by kelset** [comment]
Hi there @shilch,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
