### ISSUE TITLE
getScreenForRouteName without routeConfig

### ISSUE THREAD

**Issue by JulianKingman** [react-community/react-navigation#2328]
Is there a helper function that gets the screen (or screen options) for the routename, without requiring the routeConfig object? I'm trying to get screen options for this PR: https://github.com/react-community/react-navigation/pull/2308
I have a `routeName` available, but not `routeConfig`. I can get close by doing this, but this seems crazy-complicated for something simple.
```javascript
this.props.router.getScreenOptions(
        addNavigationHelpers({
          // Note: this gives errors in some cases, but gives you the idea
          state:  transitionProps.navigation.state.routes[1] || prevTransitionProps.navigation.state.routes[1]
        })
      )
```

Related:
https://github.com/react-community/react-navigation/issues/1474

**Comment by kelset** [comment]
Pinging OP @JulianKingman since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

(Moreover, since it looks to me that you "made it work" for your PR, maybe you found a way to do it)

**Comment by kelset** [comment]
Hi there @JulianKingman ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
