### ISSUE TITLE
Don't render twice when goBack and re navigate on same screen

### ISSUE THREAD

**Issue by thomasarbona** [react-community/react-navigation#2331]
I use StackNavigator for a small application with some screens.

### Current Behavior
When I am on screen B, goBack on screen A (B was unmount) and re navigate on B, B is re-mount.

### Expected Behavior
I expect that the StackNavigator keep screen B mount so when I re navigate on B it don't render it twice.
How to do that ? Should I navigate without goBack ? (I use fade transition)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.43.4
| node             |  6.10.3
| npm or yarn      | 3.10.10

**Comment by spencercarli** [comment]
Here's a [snack](https://snack.expo.io/By3kQ5UD-) to go along with this.

I'm not sure why you would want the behavior you described as going back would imply you're not longer interested in that screen.

I also imagine it would add a host of issues with tracking navigation state (what happens when you go from screen 1 to screen 2, back to screen 1, then to screen 3 - does screen 2 get unmounted?)

**Comment by sseyha** [comment]
@spencercarli 
I'm not sure about @thomasarbona purpose.
But in my thought, he might not want to reload the content data again and again.
And that is what i want either, because i don't want user stuck on reload the content of screen page as always when they navigate from screen to screen.
Hope it will have the solution. Regards, :)

**Comment by spencercarli** [comment]
@sseyha ah that makes complete sense! Hadn't thought about that.

I'm typically using Redux so in cases like this I would have saved the data to the store after the first screen mount and then any subsequent screen mounts would use the old data and refresh in the background.

**Comment by sseyha** [comment]
@spencercarli 
Wow, you have a great idea. You blow my mind now.
It's a bit hard for me, because i'm new with React and Redux as well.
If you don't mind, could you please share us small project about this?
It will be honor and save my day of spending on React Navigation.
Please... :)

**Comment by spencercarli** [comment]
I don't have any small examples directly related to this but you can see my strategy in action in [this repo](https://github.com/HandlebarLabs/currency-converter-starter).

That repo is broken down into a bunch of branches (it's for a course) but the final app can be found on the [module-7-lesson-4-upload](https://github.com/HandlebarLabs/currency-converter-starter/tree/module-7-lesson-4-upload) branch.

**Comment by sseyha** [comment]
@spencercarli I will learn more about redux. However, Thank so much for your guide. Appreciate!

**Comment by thomasarbona** [comment]
Thanks for your help! But my problem with the reloading isn't about reload any data (effectively stored in redux) but is to reload a fiew GLView components that take time to render.

**Comment by spencercarli** [comment]
Ah, I see. I'm not sure of a solution to this issue. I suppose I've seen a similar issue when pushing a screen with a map onto the stack. I'll do some thinking and if I can think of anything useful I'll try to add it to this thread.

**Comment by sseyha** [comment]
@spencercarli You how to refresh or reload the current active page of drawer?

**Comment by nhuthan** [comment]
+1

**Comment by JayricMok** [comment]
+ 1, don't want to reload the component again and again when re-enter the screen. Hope there have a solution for this.

**Comment by kelset** [comment]
Pinging OP @thomasarbona since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

Moreover:
> When I am on screen B, goBack on screen A (B was unmount) and re navigate on B, B is re-mount.

This is literally the way a stack is supposed to work.

If there are data you need to manage/show in the second screen, you need to use a state manager like Redux. Or you could use a tab navigator without showing the tabbar.

**Comment by kelset** [comment]
Hi there @thomasarbona ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by Shamar22** [comment]
To the above posters that want to reload the content data, you can create a function which resets the data to their original state.

**Comment by emilemoureau** [comment]
Hello! Someone found a solution?
