### ISSUE TITLE
StackNavigation animation bug causes onlayout to get abnormal

### ISSUE THREAD

**Issue by fangkyi03** [react-community/react-navigation#2373]
1. I implemented a drop-down menu myself
Not through modal, which opens up the entire page
Although I realized this effect
Current interface
Stack:{
Screen:{test1},
Screen:{test2}
}
Let me suppose that my present structure is like this
Because I'm going through onLayout to get the actual location of the drop-down menu
Then use UIManager.measure
This to get the actual location
Here, I found that this UIManager.measure access was normal when I was in test1, but at test2, this command UIManager.measure
What is obtained is (width*pos)
Such a value causes my view display to be abnormal
Finally, I found out that there was something wrong with your animation
I'll change it into...

InputRange:[i, i+1],
OutputRange:[0, -width]

After this appearance, there will be no previous problem
Second, because you have this tabnavigation without left
My side also manually changed it, found that you are writing in this side, completely without taking into account the needs of the left tabnavigation, in animation, if I click later
TabViewPagerPan this view will directly block my written left tab, resulting in no Click

**Comment by kelset** [comment]
Pinging OP @fangkyi03 since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @fangkyi03 ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
