### ISSUE TITLE
Drawer overlap status bar

### ISSUE THREAD

**Issue by James2516** [react-community/react-navigation#2384]
### Current Behavior

https://i.stack.imgur.com/gxgmz.png
The drawer overlaps with the Android status bar. Is there a way to prevent that?
```
contentOptions: {
  style: {
    marginTop: 24,
  },
}
```

This only gives margin to the drawer content.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.46.4
| node             |  v8.3.0
| npm or yarn      | 4.6.1

**Comment by vonovak** [comment]
this is probably related to using expo, fix should be in #2446

**Comment by kelset** [comment]
Pinging OP @James2516 since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @James2516 ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
