### ISSUE TITLE
TypeError:expected dynamic type 'double',but had type 'string' when using goBack() on android simulator

### ISSUE THREAD

**Issue by sejo2016** [react-community/react-navigation#2387]
I got a issue when I custom a back button on page component using goBack(),my code as below:

```
export default class ContactList extends PureComponent{
    static navigationOptions = ({navigation,screenProps}) => ({
        headerTitle:'title',
        headerLeft:(<TouchableOpacity style={{}} onPress={()=>navigation.goBack()}/>),
        headerRight:(
            <TouchableOpacity>
                <Text style={{}}>menu</Text>
            </TouchableOpacity>
        )
    })
    ...
}
```
ios is ok,but android 
![android_bug](https://user-images.githubusercontent.com/19886235/29309776-c0feac78-81dd-11e7-881b-a01e61326ae2.png)

the dependencies i use as below:
"react": "16.0.0-alpha.12",
"react-native": "^0.46.4",
"react-navigation": "^1.0.0-beta.11",

does anyone can finger out  what caused this issue?

**Comment by sejo2016** [comment]
It's amazing!I tried today and get a right direction,it's fine!during the time,i have re-installed dependencies for above twice and restarted my computer,I think it may caused by react-native compile.

**Comment by timurridjanovic** [comment]
I'm getting the same thing..

**Comment by timurridjanovic** [comment]
Figured out what my issue was, but it's odd as hell.. I only had a right chevron icon, so I applied a 180 degree rotate transform on it for my back button.. When I pressed on goBack, I had this same error: TypeError:expected dynamic type 'double',but had type 'string'.. If I remove the rotation transform everything works lol... Pretty odd..

**Comment by nikoskleidis** [comment]
Amazing! I had exactly the same issue! Thanks

**Comment by natakina** [comment]
I have the same error. It happens when I rotate elements and then click on them. One element is the switcher of camera (react-native-camera), another one - go back arrow from react-navigation.
Maybe this issue belongs to react-native and not to react-navigation?

**Comment by yangningBU** [comment]
I got the same error when attempting to opening a DatePicker with the DatePickerAndroid API after switching to react-navigation (^1.0.0-beta.19) from react-native-router-flux (^4.0.0-beta.22). I believe https://github.com/facebook/react-native/issues/3216 is relevant - it is possible there is a bug in the way react-navigation is delegating certain transitions.

**Comment by yangningBU** [comment]
@timurridjanovic I believe that problem is mentioned here https://github.com/facebook/react-native/issues/3216#issuecomment-341571771

**Comment by nicolit** [comment]
Hi I have a bug, whenever I try to setParams is crashes. screenshot is attached. Only when the setParams line in componentDidMount is set in comment it works ok.

`export default class ReviewsScreen extends Component {
static navigationOptions = props => {
const { navigation } = props;
const { params = {} } = navigation.state;
let _headerRight = DishReviewsScreen.shareButton(navigation);
if (params.isSharing) {
_headerRight = ;
}
return {
title: 'Reviews',
headerTitleStyle: { color: lightTheme.headerTitle },
headerStyle: AppStyles.navigationHeaderStyle,
headerLeft: DishReviewsScreen.backButton(navigation),
headerTintColor: lightTheme.headerBackButton,
headerRight: _headerRight,
};
};

static shareButton = navigation => {
const { params = {} } = navigation.state;
return (
<TouchableOpacity
style={{ marginRight: 10 }}
onPress={() => {
params.shareItem ? params.shareItem : () => null;
}}>
<Icon
name={'md-share'}
type={'ionicon'}
color={'black'}
size={24}
iconStyle={{marginRight: 8}}
/>

);
};

static backButton = navigation => {
const { key } = navigation.state;
return (
<TouchableOpacity
style={{ marginLeft: 10 }}
onPress={() => {
navigation.dispatch(NavigationActions.back({ key }));
}}>
<Icon
name={'md-arrow-back'}
type={'ionicon'}
size={24}
color={'black'}
iconStyle={{marginLeft: 8}}
/>

);
};

constructor(props) {
super(props);
this.onBackPress = this.onBackPress.bind(this);
this._shareItem = this._shareItem.bind(this);
}
componentDidMount() {
BackHandler.addEventListener('hardwareBackPress', this.onBackPress);
this.props.navigation.setParams({ shareItem: this._shareItem }); // ----> this does not work
}
componentWillUnmount() {
BackHandler.removeEventListener('hardwareBackPress', this.onBackPress);
}
onBackPress() {
const { navigation } = this.props;
const navState = navigation.state;
if (navState && navState.key) {
let { key } = navState;
navigation.dispatch(NavigationActions.back({ key }));
//navigation.goBack( key );
return true;
} else {
return false;
}
}
_shareItem = () => {
// Update state, show ActivityIndicator
this.props.navigation.setParams({ isSharing: true });
const { itemReducer } = this.props;
const { id, icon } = itemReducer;
shareItem(id, icon).then(() => {
this.props.navigation.setParams({ isSharing: false });
});
};
render(){
return (
<View style={{ backgroundColor: 'transparent' }}>);
}
}
`
Current Behavior:

when this screen is rendered and mounted, it crashes.
Expected Behavior

the share button was suppose to be attched to the "shareItem" param in componentDidMount method.
I made the same way as the example on the official site: https://reactnavigation.org/docs/intro/headers
Your Environment- from package.json

"react": "^16.2.0",
"react-native": "^0.51.0",
"react-navigation": "^1.0.0-beta.27",
"react-redux": "^5.0.6",
"redux": "^3.6.0",
"node": "v6.11.2",
"npm": "5.6.0",

I'm using Mint OS (Linux), Vscode IDE to debug remotely, running on OnePlus5 (Android 8).
![photo5981241705350933419](https://user-images.githubusercontent.com/10170174/35042316-da7d0ea6-fb90-11e7-88e6-8216b312d239.jpg)

**Comment by udfalkso** [comment]
@timurridjanovic Same issue here.  Clicking on rotated element on android causes this issue.  Get rid of rotation and it goes away.  Thanks!!

**Comment by rashtay** [comment]
I was facing the same issue with the below-given code:

```
<TouchableOpacity>
  <Image /> {/*  I was rotating the image  */}
</TouchableOpacity>
```

I changed the code to:
```
<TouchableOpacity>
  <View> {/*  I started rotating the wrapper  */}
    <Image />
  </View>
</TouchableOpacity>
```
and everything worked fine.

**Comment by nicolit** [comment]
Hi,
I think it's because <TouchableOpacity> and all Touchables expect only one
child, one which can pass native props, since when you press the Touchable
the pressing effect needs the inner child to participate in the effect.

I think in my case it is more related to the navigation, sonI'll try to
update to the newest version.
Thanks

**Comment by lvstross** [comment]
So I had the same error pop up when I applied a `transform: [{ rotate: '90deg' }],` on the `TouchableOpacity` element, but when removed the style and instead added it as a style directly on the `Icon` itself, the error didn't pop up and everything worked as it should. Not sure why this is the case but I guess if you need to rotate an icon, do apply that style to the `TouchableOpacity`. Instead apply it to the `Icon` directly.

**Comment by kevin-bpract** [comment]
Fixed by rm -rf nodemodules/ && npm install

**Comment by sedrak-ghukasyan** [comment]
I had the same problem, and my solution was simply to remove the fontSize property from the TextInput styles. I’m not sure why, but it worked.
