### ISSUE TITLE
Switching tabs with swipe broken after navigating to TabNavigator with deep link

### ISSUE THREAD

**Issue by Keksike** [react-community/react-navigation#2388]
### Current Behavior
Swipe-gesture animation broken after navigating to TabNavigator from deep link.

After navigating to a TabNavigator which has `swipeEnabled: true` & `animationEnabled: true` the swipe-gesture doesn't finish changing of tabs, but rather gets stuck between the tabs where you release the gesture.

### Expected Behavior

Have the swipe work as normal, finishing the changing of tabs even if you release the swipe before it has fully navigated to the other tab.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  react-navigation@1.0.0-beta.11
| react-native     |  react-native@0.44.3
| node             |  v8.2.1
| npm or yarn      | 5.3.0

**Comment by kelset** [comment]
Pinging OP @Keksike  since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @Keksike ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
