### ISSUE TITLE
When to use route.key, route.routeName and what's the difference between the two

### ISSUE THREAD

**Issue by alexkuc** [react-community/react-navigation#2395]
I am currently in the process of building a custom navigator with a custom view and TabRouter. There is one part which I couldn't clarify via docs or the existing GitHub issues. What's the difference between route.key and route.routeName? Initially, they have identical values which confuse me.

**Comment by spencercarli** [comment]
Though I'm not exactly sure, I would say it's probably best to use `routeName` in most cases. It's certainly something worth finding out the exact answer and clarifying in the docs.

**Comment by matthamil** [comment]
It looks like there is a discrepancy between how the StackRouter and TabRouter use keys, but this is due to the inherent nature of how stacks and tabs should work. For the StackRouter, the key is to [uniquely identify the page in the stack](https://github.com/react-community/react-navigation/blob/5e075e1c31d5e6192f2532a815b1737fa27ed65b/src/routers/StackRouter.js#L134) so you can navigate to the same route with different params and still register the action as a new navigation action (navigating from "Profile" with params `{ username: "Matt" }` to "Profile" with params `{ username: "Alex" }`). If I hit "Back", I should be presented with the "Profile" page with the params `{ username: "Matt" }`. 

It looks like the key for the TabRouter [is dependent upon the route name](https://github.com/react-community/react-navigation/blob/5e075e1c31d5e6192f2532a815b1737fa27ed65b/src/routers/TabRouter.js#L74-L79). You can still navigate to the same tab with params like in the above example, however, when you press "Back", you will not be redirected to the same tab again with the previous params. Setting the params on the current route in the TabRouter looks like it's [modifying the tab in place](https://github.com/react-community/react-navigation/blob/5e075e1c31d5e6192f2532a815b1737fa27ed65b/src/routers/TabRouter.js#L181-L201) instead of adding a new path to the router's history. This is because you aren't building a stack-like history with a tab router. Tab navigation actions are idempotent so you can't push the same tab route onto the router's history multiple times.

**Comment by alexkuc** [comment]
Thank you very much @matthamil for your elaborate explanation. Just to clarify that I understood you, StackRouter relies on route.key to be able to preserve state (i.e. params) when navigating back and forth while TabRouter uses route.routeName which doesn't preserve state (i.e. params) when navigating. 

Is this correct? 

Also, currently I use route.key for TabRouter. Could it have any unintentional consequences? Is it better to use router.routeName for TabRouter?

**Comment by matthamil** [comment]
StackRouter uses the `key` to uniquely identify an item in its history. TabRouter also uses `key`  to uniquely identify items in it's history, but the `key` is derived from the `route.routeName`. TabRouter does preserve params; however, if you navigate to the current route with different params (i.e. `navigation.navigate('SameRoute', { newParams: 'abc' });`), you are not adding a new item to the TabRouter's history. You are modifying the last item in its history (the current tab), since you cannot treat navigating from the current tab to the current tab again as a new addition to its history (due to the tab navigator's idempotent nature). Hopefully that clears it up a little more maybe? :)

**Comment by alexkuc** [comment]
Yeah, @matthamil makes perfect sense, thank you very much again!

In regards to the `route.key` and `route.routeName`, I am referring to this:

```
<Button key={route.routeName} onPress={()=>navigation.navigate(route.routeName)}>
    <Icon name={_iconName} />
</Button>
```
This is from the part of the code that generates actual tab buttons for the tab bar. From your explanation, I understand that in terms of TabRouter, this shouldn't make a difference but for StackNavigator I need to use `route.key`. Right?

**Comment by matthamil** [comment]
You should use the route name if it is a StackRouter too. It will generate the a [unique random key internally](https://github.com/react-community/react-navigation/blob/5e075e1c31d5e6192f2532a815b1737fa27ed65b/src/routers/StackRouter.js#L28-L30) to prevent naming collisions.

**Comment by alexkuc** [comment]
Awesome, thank you for the clarification! 

One last thing I wanted to clarify, currently [this](https://reactnavigation.org/docs/navigators/navigation-prop#goBack-Close-the-active-screen-and-move-back), [this](https://reactnavigation.org/docs/navigators/navigation-actions#Back) and [this](https://reactnavigation.org/docs/navigators/navigation-actions#SetParams) say that you need to use `key` (they didn't mention anything regarding `routeName`). Is this outdated information?

**Comment by matthamil** [comment]
Yes, you should use the key in those instances. I was unsure what you were needing the key for originally. When you are trying to go back, in say for instance a Stack, you need to know which key to go back from. Since the same screen could be pushed to the stack history with different params, you will need to use the key in those cases to identify which specific point in the stack history to go back from. You can find the key in the data stored in the navigation state, `this.props.navigation.state`.

**Comment by alexkuc** [comment]
Oh, my apologies, I guess I have overlooked initially. So I think I got it this time now. When I use `navigate` I need to specify `routeName` as parameter but when I use `goBack`, `Back` or `SetParams`, I need to specify `key`.

**Comment by alexkuc** [comment]
I am closing this issue as I believe everything is clear and was addressed. Thank you, everybody, for helping me with my questions!
