### ISSUE TITLE
How to reset navigation from subroute on StackNavigator to DrawerNavigator

### ISSUE THREAD

**Issue by dashracer** [react-community/react-navigation#2414]
### Current Behavior
I've create a simple app with Navigation code like this

```
const AccountStack = StackNavigator({
  ForgotPasswordScreen: { screen: ForgotPasswordScreen },
  AccountScreen: { screen: AccountScreen },
  RegistrationScreen: { screen: RegistrationScreen },
  LoginScreen: { screen: LoginScreen },
  EditProfileScreen: { screen: EditProfileScreen }
}, {
  stateName: 'AccountStack',
  headerMode: 'none',
  initialRouteName: 'AccountScreen',
  navigationOptions: {
    headerStyle: styles.header
  }
})

const PrimaryNav = DrawerNavigator(
  {
    Home: {
      screen: HomeScreen
    },
    Account: {
      screen: AccountStack
    }
  },
  {
    stateName: 'PrimaryNav',
    initialRouteName: 'Home',
    drawerPosition: 'left'
  }

)

export default PrimaryNav
```

How can I reset the navigation to open HomeScreen if currently on LoginScreen or any other screen on Account StackNavigator?

I've tried modified react navigation according to [#1384](https://github.com/react-community/react-navigation/pull/1384) but still cannot fix it.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.12
| react-native     |  0.45.1
| node             | 8.1.4
| npm      | 5.3.0

**Comment by spencercarli** [comment]
If you want to reset from any screen in the `AccountStack` you can do

```javascript
import { NavigationActions } from 'react-navigation'

const resetAction = NavigationActions.reset({
  index: 0,
  actions: [
    NavigationActions.navigate({ routeName: 'AccountScreen' })
  ]
})
this.props.navigation.dispatch(resetAction)
```
which will then clear that stack and set that screen as the only active screen.

**Comment by dashracer** [comment]
Hi @spencercarli , 

How about reset to `HomeScreen` from any screen in the `AccountStack`?

That is my main problem right now.

**Comment by dashracer** [comment]
I've found the solution,

I dispatch two navigation action

```
const resetAction = NavigationActions.reset({
      index: 0,
      actions: [
        NavigationActions.navigate({
          routeName: 'AccountScreen',
          params: {}
        })
      ]
    })
    const goHome = NavigationActions.navigate({
      routeName: 'Home',
      params: {}
    })
    this.props.navigation.dispatch(resetAction)
    this.props.navigation.dispatch(goHome)

```

Thank You 💃

**Comment by bakarshams** [comment]
@spencercarli  Hi. I really appreciate your contributions. I want to reset the whole stack navigation of my tabs app.
Tabs Nav(Parent Navigator)
Tab 1 (Stack Nav)
Tab 2 (Stack Nav)
Tab 3 (Stack Nav)
I used tab tabBarOnPress to reset stack:

tabBarOnPress: (tab, jumpToIndex) => {
const {
dispatch,
state,
} = navigation
if (tab.focused) {
dispatch(NavigationActions.reset({
index: 0,
actions: [
NavigationActions.navigate({ routeName:"HomeScreen" })
]
}))
} else {
jumpToIndex(tab.index) // go to another tab (the default behavior)
}
}

The issue is:
After the reset, it says that "There is no route defined for key HomeScreen" but I can see in console that homescreen component has been executed coz I have put some console statements there.

Please help me regarding this.

**Comment by yashaRO** [comment]
@bakarshams use the code wrapper on your code to make it easier to read (''' code ''')

**Comment by soyhares** [comment]
You must use createSwitchNavigator and then only use this.props.navigation.navigate('YOUR_STACK_NAME')
