### ISSUE TITLE
Incorrect behaviour with nested StackRouters and TabRouter 

### ISSUE THREAD

**Issue by JakeCoxon** [react-community/react-navigation#2445]
### Current Behavior

Given the following hierarchy
```
  StackRouter  (outer)
    StackRouter  (inner)
      TabRouter
```

When I navigate to a tab that the tab router is already on, the outer stack router duplicates my inner view instead of doing nothing.

In the source this is the code path that happens for getStateForAction
* TabRouter returns null [here](https://github.com/react-community/react-navigation/blob/master/src/routers/TabRouter.js#L210) because nothing should change
* StackRouter (inner) returns its own state [here](https://github.com/react-community/react-navigation/blob/master/src/routers/StackRouter.js#L152-L156) because TabRouter returned null
* StackRouter (outer) goes on to push a route because it thinks the child (inner) hasn't handled anything

I suspect that the incorrect behaviour is in step 2 where StackRouter returns state. Perhaps the correct behaviour is that StackRouter should be to return null if its child returns null, propagating the null to the top of the hierarchy

Here's a gif showing the first click correctly navigating to the tab, and the second click duplicating the whole stack
![Gif](http://i.imgur.com/ef9m3E2.gif)

### Expected Behavior
I would expect trying to navigate to a tab that the router is already on should do nothing.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.12
| react-native     | 0.36.1
| node             |
| npm or yarn      |

**Comment by kelset** [comment]
Pinging OP @JakeCoxon since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

That said, I also think it may a duplicate / related to these two issues:
* https://github.com/react-community/react-navigation/issues/3009
* https://github.com/react-community/react-navigation/issues/2622

And may be solved via:
* https://github.com/react-community/react-navigation/pull/1515
or
* https://github.com/react-community/react-navigation/pull/1888

Can you please let me know if that's the case via a comment in the PR that fixes it?

**Comment by kelset** [comment]
Hi there @JakeCoxon ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
