### ISSUE TITLE
swipe StackNavigator

### ISSUE THREAD

**Issue by manuTro** [react-community/react-navigation#2447]
Is it possible to swipe between screens with StackNavigator?

**Comment by spencercarli** [comment]
Yes.

**Comment by manuTro** [comment]
@spencercarli I've read the documentation but I've found just the `swipeenabled` option but It is for TabNavigator. I need it for the StackNavigator. Can you tell me where I should read? Thanks :) 
Sorry, I didn't follow the issue template since this isn't an issue, but just a question. I don't know if there is another way/space to write questions ^^'

**Comment by richeterre** [comment]
@manuTro, please respect this project's maintainers and their time, and take a few seconds (!) to check what the issue template has to say on docs and questions. Thanks 😉

**Comment by sunkaigoon** [comment]
@spencercarli Hello, do you know how to swipe to any other screens (with gesturesEnabled：true) please? I have three screens A, B, C. I navigate A to B, B to C. I want goBack to A, of course it works by using goBack() function, but how make it by swiping? Thank you.

**Comment by mmjd** [comment]
How is it possible to swipe between stacks like instagram stories? I can not find any reference?

**Comment by ntomallen** [comment]
Use `gesturesEnabled` to enable swiping back in a stack navigator. (See [here](https://reactnavigation.org/docs/en/stack-navigator.html#gesturesenabled)).

Still looking for something to enable swiping forward, though..

**Comment by Kielan** [comment]
@manuTro these issues are the first ones that pop up in google search so it is particularly important to follow the maintainers guidelines especially for common issues, which other people are also going to come across.
Since the latest version of react navigation there is truly no documentation on implementing custom transition and navigations. It would be nice if someone provided a relevant link to implementing custom navigators and transition in the vein of this.

https://medium.com/the-react-native-log/implement-snapchat-like-swipe-navigation-declaratively-in-react-native-309e71229c89
