### ISSUE TITLE
How can i remove the borderBottom of header?

### ISSUE THREAD

**Issue by cizhaoyang** [react-community/react-navigation#2457]
static navigationOptions = ({ navigation }) => ({
        headerStyle: { backgroundColor: 'red' , borderBottomColor:'transparent',borderBottomWidth: 0 },
    })

I set like that,but it do not work! why?

**Comment by JulianKingman** [comment]
also set `shadowColor: 'transparent',` (iOS) and `elevation:0` (Android)

**Comment by Xaber20110202** [comment]
The new version 1.0.0-beta.11
navigationOptions = {
    headerStyle: {
        elevation: 0,
        shadowOpacity: 0
    }
 }
works for me.
https://github.com/react-community/react-navigation/issues/790

**Comment by fkotsian** [comment]
If you are like me and wondering why this CSS does not work, for me it was because I had already set headerStyle in my initial navigator props and was attempting to override it with a static property in my component (React-Navigator 2.x)

Apparently 2.x doesn't allow overriding the initial headerProperties via static property, I fixed this by parameterizing the initial headerStyle and configuring it during the global navigator setup
