### ISSUE TITLE
Can no longer set `initialRouteName` in `DrawerNavigatorConfig` in RN 0.47 (iOS only)

### ISSUE THREAD

**Issue by LilyMGoh** [react-community/react-navigation#2464]
After upgrading from Expo SDK 19 (RN 0.46) to SDK 20 (RN 0.47), `DrawerNavigator` is no longer working. Instead of rendering `initialRouteName` as the initial route the component renders the first route defined in `DrawerNavigator`. The issue is only on iOS but not Android.

**Comment by spencercarli** [comment]
Could you fill out the issue template for this?

**Comment by LilyMGoh** [comment]
@spencercarli Hope this help!

### Current Behavior
On iOS, instead of rendering `initialRouteName` as the initial route `DrawerNavigator` renders the first route defined. Works fine on Android.

### Expected Behavior
Should be able to dynamically set `initialRouteName` in `DrawerNavigator`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.11
| react-native     | 0.47
| node             | 7.9.0
| yarn      | 0.23.2

**Comment by LilyMGoh** [comment]
Any updates on this?

**Comment by DomKM** [comment]
@spencercarli Can you confirm that this is an issue with react-navigation on RN 0.47 and, if so, when might a fix be available?

**Comment by kelset** [comment]
Pinging OP @LilyMGoh since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open (does it still happen in latest version?); if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @LilyMGoh ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
