### ISSUE TITLE
Infinite navigation loop in Stack Navigator when dispatching "navigate" after "reset"

### ISSUE THREAD

**Issue by pensierinmusica** [react-community/react-navigation#2473]
Hi,

If I dispatch a `reset` and then a `navigate` action Stack Navigator gets in an infinite loop and keeps navigating to the second component.

```js
import { NavigationActions } from 'react-navigation';

const nav = this.props.navigation;

const resetAction = NavigationActions.reset({
  index: 0,
  actions: [NavigationActions.navigate({ routeName: 'RouteOne' })]
});

const navigateAction = NavigationActions.navigate({ routeName: 'RouteTwo' });

nav.dispatch(resetAction);
nav.dispatch(navigateAction);
```

If I wait a bit before dispatching the second action though it behaves as expected:

```js
setTimeout(() => {
  nav.dispatch(navigateAction);
}, 1000);
```

Do you know how this can be fixed? Thx!

**Comment by pensierinmusica** [comment]
@matthamil shall we add the `bug` label?

**Comment by spearmootz** [comment]
this happens to me too. I listen to the background AppState event and then i sort of do a resetAction, the route is basically a splash which after 500ms it switches to the login screen. for some reason, sometimes, it loops back and forth between the splash and the Login

**Comment by kelset** [comment]
Pinging OP @pensierinmusica since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open (does it still happen in latest version?); if I get no answer in the next 7 days I will close it.

Moreover, I suggest you take a look at the discussion / how to debug this kind of issue over here https://github.com/react-community/react-navigation/issues/2702

**Comment by kelset** [comment]
Hi there @pensierinmusica ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by lon-io** [comment]
Wrap your call in `InteractionManager.runAfterInteractions` like so:
```
InteractionManager.runAfterInteractions(() => {
     nav.dispatch(navigateAction);
});
```
Sources: 
https://github.com/react-navigation/react-navigation/issues/2702#issuecomment-341933786
https://facebook.github.io/react-native/docs/interactionmanager.html

**Comment by mhuggins** [comment]
`InteractionManager.runAfterInteractions` didn't work for me.

**Comment by matthamil** [comment]
@mhuggins Can you open a new issue?

**Comment by mhuggins** [comment]
@matthamil I ended up resolving this by using `useEffect` with a second argument.  (See [Optimizing Performance by Skipping Effects](https://reactjs.org/docs/hooks-effect.html#tip-optimizing-performance-by-skipping-effects).)  This allows my effect to only load once my data is loaded.

I'm using react-apollo, which allowed me to do something like this:

```js
function MyComponent(props) {
  const { data, error, loading, refetch } = useQuery(recipeQuery, {
    variables: {
      id: navigation.getParam('id'),
    },
  });

  const loaded = Boolean(data.recipe);

  useEffect(() => {
    if (loaded) {
      navigation.setParams({ foo: 'bar' });
    }
  }, [loaded]);

  // ...snip...
}
```
