### ISSUE TITLE
TabBar bottom gap / white border/line

### ISSUE THREAD

**Issue by JulianKingman** [react-community/react-navigation#2474]
There's a small gap border that appears between tab bar icons on iPhone 5s with three tabs. I can confirm it happens on both the device, and the simulator, and it appears to be a gap (changing the background of the wrapping View inside the TabBarBottom component changes the gap color).

I can hide it by setting the backgroundColor in the style, but perhaps the backgroundColor should default to the inactiveBackgroundColor

<img width="315" alt="screen shot 2017-08-25 at 8 13 03 am" src="https://user-images.githubusercontent.com/1566400/29714005-1e94abec-896f-11e7-97e4-6f6463c4144e.png">

**Comment by wlwg** [comment]
This also happens to me on iPhone SE device (which has the same screen with iPhone 5). Anyone knows a workaround?

**Comment by kelset** [comment]
Pinging OP @JulianKingman since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open (does it still happen in the latest version?); if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @JulianKingman,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it (and yeah #3052 is a duplicate but has a bit more follow up so better to keep that one open).

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
