### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by beeperbeepity** [react-community/react-navigation#2476]
I apologize for posting a non-bug issue on your GitHub project. But this seems like the most appropriate place to raise this concern.

We're working on a production RN app and have discovered that React Navigation is missing some fundamental features. Luckily we've been able to work around or hack our way through every issue thus far, sometimes at the expense of an optimal UX.

So is this project still under active development? Or has it gone stale? We (and I believe a good portion of the community) would appreciate an honest answer.

### 1.) We're seeing the same/related issues posted time and time again:
* Resetting nested Tab Navigators
* Customizing the back button in the Header
* Dynamically declaring the initial route in a navigator
* Modal transitions on a per-scene basis
* Lack of documentation
* The list goes on and on

### 2.) Plenty of PRs address these issues but they're not being merged
This is self explanatory. We've even seen one poor guy commit a "Real World" example and the maintainers decided not to merge it. This at least would've helped with the lack of documentation.

### 3.) We would contribute but...
See point number 2 above. There are 98 open PRs at the moment. _The community is doing their best to contribute but it doesn't seem to matter._ We're concerned that we'll end up with our own fork of the project that has no community support because it seems unlikely our changes will get merged back into the main project.

### 4.) The 1.0 Stable Roadmap is 4 months late
This is probably the most concerning part. We would ask for a roadmap to get an idea of where things are at. But we _have_ a roadmap. And even the roadmap has gone stale. This leaves us feeling pretty hopeless.

### 5.) Various other concerning signs that this project may be dying
* There hasn't been an official release for almost three months
* There have only been a handful of merges since the last pre-release
* Maintainers (although they are understandably busy spending time on other OSS projects) don't appear to be as involved in this project anymore

### Final Thoughts: We _WANT_ React Navigation to work out
There are probably valid excuses to every single concern we've listed here. But React Native at least has been able to keep up with a monthly release cadence. This project doesn't seem to be progressing ~at the same pace~ at all lately. So what should we do?

This is the package the community chose, so we want to follow that choice wholeheartedly. Is it just not the right time to build a production-ready app with React Navigation? If so, can _THAT_ at least be communicated so that other members of the community don't fall into the same pitfalls that we have?

Yours truly,

A sleep-deprived dev who has spent endless nights hacking navigation solutions together over the past two weeks.

P.S. Regardless of these concerns, we still could not be more appreciative for all the hard work on this project and on React Native. Everything stated here is out of love for the open source React community and it's contributors. So regardless of where this project ends up, keep up the solid open source work my friends.

**Comment by valetarton** [comment]
Agreed would love to see if there is any traction on this.

I haven't made any PRs, however, I have tried my best (when I have time) to cull the issues log where I have experience by commenting to help.

Started using this for several projects in May / June and would like to know if this library worth sticking with as a LT solution or should I fork my own and start working on things?

**Comment by kernelgonnapanic** [comment]
I've actually wanted to post a similar issue here recently. More and more teams is deciding to start building their production apps using react-navigation as it's even recommended in react native docs. I agree that community behind react-native should take some action on that and make it work out.

**Comment by valetarton** [comment]
> recommended in react native docs
That is the part most stinging, it's recommended.

**Comment by ippa** [comment]
I've been wondering the same thing. I really hope it's a temporary slump. The react-native ecosystem really needs a recommended way of doing navigation, and for the last 6 months I've been betting on react-navigation. For the most time it's been working great, but I've been bitten by all the corner-cases as others have been reporting.

Thanks for all the great work so far. A clarification from the maintainers about the future of this library would be greatly appreciated!

**Comment by richardgirges** [comment]
Totally agree. I've been struggling with react-navigation for months now. Mainstream FB-backed OSS projects usually have great support and great release cycles. My team tries to stick with the mainstream choices for that reason alone (react-navigation being one of those choices).

However, react-navigation has a different type of problem because the community support is there. People are posting helpful comments all over these issues, PRs are coming in at a healthy pace, etc. It's the _maintainer support_ that's stalled out. I keep seeing the _"do your part to contribute"_ argument throughout the issue comments - but that argument's null and void when people's contributions are ignored for extended periods of time. At least onboard some willing and able maintainers to handle things while the core maintainers are busy.

[This is THE recommended external navigation solution in the React Native docs.](https://facebook.github.io/react-native/docs/navigation.html#react-navigation) No other external navigation solution is mentioned. **That can't be taken lightly considering how unmaintained this project is, relative to how fast RN is growing.**

Either way, despite this slump, I'm appreciative of all the work the maintainers and the community have done thus far. It's not something I would've been able to do myself, so much respect. I hope the future of react-navigation is a bright one. :)

**Comment by jacksontbryan** [comment]
I agree with the worry about activity level in this repo.  As the recommended navigation solution, this is a core building block of an app and it needs more active maintainers. Or perhaps additional maintainers.  I think this is pretty close it just has some common problems that keep getting re-raised.  My particular wishlist:

1) Different transition modes (card/modal) per scene rather than for the whole navigator.
2) Built-in transition mode for a transparent modal (current animations fade the previous screen to 0 opacity and you have to override)
3) Improved examples and documentation.

**Comment by spencercarli** [comment]
Hey all!

Thanks for the feedback - I'm going to leave this open to continue discussion. There are a few other issues with similar sentiments but each one brings unique input, so thank you!

A bit of an update/news on what's going on for the project - as you can tell the project stalled out for quite a while. There are two of us actively looking things over (we've just joined in recently) and this is our tentative game plan

1. Get the Github issues under control. Seeing 700+ open issues is scary to anyone considering this project. At least 50% of them are questions, 10-20% are duplicates, and the rest are great bugs reports & feature requests. 
2. Get the pull requests under control, at least documentation/example related ones.
3. New roadmap to 1.0
4. Start development/merge pull requests in relation to 1.0

We're working on it! It's a side hustle for all of us 😄 

Again, thanks for the valuable and respectful input so far (and apologies if I don't get back to any mentions right away)

**Comment by matthamil** [comment]
Hey everyone,

Echoing what @spencercarli said, thank you everyone for the input and concern about the project.

I want to write a post for the sake of transparency to keep the community informed. The timeline to 1.0 (#723) was originally planned for mid-April, but since then, we've had some of the original contributors stop working on the project. Some of the people at Callstack were early contributors to react-navigation; however, Callstack has [stepped away from react-navigation](https://facebook.github.io/react-native/blog/2017/06/21/react-native-monthly-1.html). Some original contributors have said they have stopped working on react-navigation due to wanting to use a native solution or sometimes even feeling like their proposed ideas were never discussed. Obviously, we want to maintain react-navigation and also bring it out of beta. We want react-navigation to be a viable JS solution to navigation for any one in the community, and we want to hear your ideas to make it better.

@skevy has also mentioned that he is working on the project, and has [even submitted a PR to react-native](https://github.com/facebook/react-native/pull/15322) which indirectly helps react-navigation. Originally when I joined the project, he mentioned that he wanted to prioritize bug fixes and triaging issues while he started working to refactor the code base.

There are lots of issues and open PRs, and, like Spencer said, we want to get this project up to speed again. I guess you could say that we're in a transitioning period right now. Thank you everyone for your support, bug reports, PRs, questions--everything.

**Comment by tirrorex** [comment]
If the problem here is the number of main collaborators, why not give right to accept pr and stuff to more people?
That would help the repo very much imo.
Thanks for getting back to us :)

**Comment by vonovak** [comment]
@matthamil @spencercarli I also feel like there should be more than two people who are able to close issues and merge PRs.

**Comment by vanhoutk** [comment]
@beeperbeepity Sorry if this is sidetracking a bit, your profile didn't have any other means of contact (although I feel like your question has already been answered). Is there any chance you've managed to create workarounds for the issues you listed? I'm specifically interested in if you've managed to solve resetting nested Tab Navigators and Dynamically declaring the initial route in a navigator.

**Comment by vonovak** [comment]
@vanhoutk maybe you wanna say how you can be reached so you can discuss this privately

**Comment by iamclaytonray** [comment]
If number of collobarators is an issue, I'll offer up any free time I have to contribute. I wouldn't really consider myself a good programmer but maybe I could take docs off of your hands or answer general questions posted under Issues? I'd love to see this project continue to push forward so if I can do anything, I'd be happy to. I know it's not the best way to contribute but it's something :-)

**Comment by richardgirges** [comment]
^ Likewise. I'm happy to regularly contribute. Also open to providing _some_ monetary sponsorship if that would help; no agenda on my end, no strings attached.

**Comment by sospedra** [comment]
I absolutely agree with:

> "[...]Regardless of these concerns, we still could not be more appreciative for all the hard work on this project and on React Native[...]"

But I'm on the verge to make a spin-off of the project just like happened with `io.js` and `node.js`.

Which makes me feel like: 😞 

I hear that some changes are happening with the collaborators. Callstack drop off and so on. This should be a great news.

And yet, the project organization and leadership is not transparent.
So, I don't know. It's complicated.

🚶

**Comment by matthamil** [comment]
@sospedra transparency is one of my top concerns. Expect a write up posted to the react-navigation blog in the coming week. We'll detail the new path to 1.0 and the steps we'll be taking to get us there. Thank you for your patience and understanding.

**Comment by xhou** [comment]
I got severals issue and I couldn't find an elegant solutions. What suprises me is lots people had similiar issues to me but no one had a proper solution for a couple of months. I have to give up my efforts on this project. I will try wix react-native-navigation

**Comment by sospedra** [comment]
Well, the week pass. This is the last time I believe in any word from the collaborator. I'm very sorry of these words. I'm just hoping @lelandrichardson keeps his word here https://github.com/airbnb/native-navigation/issues/145#issuecomment-329384356 and free the repo.

I want to hihglight that a fork won't be the same because it's React Native official web and team who's suggesting this lib as the best and kind-of official lib.

**Comment by matthamil** [comment]
Hi all, as promised, the updated roadmap to 1.0 is viewable here: https://github.com/react-community/react-navigation/issues/2585. An official blog post will be posted to the react-navigation website shortly to follow.

**Comment by sospedra** [comment]
yaaaay! @matthamil  🎊 


Can we close this in favour of #2585 ?

**Comment by richardgirges** [comment]
YES!!!! Roadmap's looking good! Thanks @matthamil :D

**Comment by matthamil** [comment]
Closing in favor of #2585 . I strongly encourage anyone experiencing issues with the library to comment on the new roadmap to 1.0 issue. If you are using any hacky solutions, please let us know. They might not be incorporated into the roadmap, but making everyone aware of these is important :)
