### ISSUE TITLE
drawer overlaps with StatusBar on ios

### ISSUE THREAD

**Issue by Hayko1994** [react-community/react-navigation#2536]
<img width="322" alt="30078292-d0183218-928d-11e7-9487-d56e2d7a32a2" src="https://user-images.githubusercontent.com/22639899/30081570-bf0ff748-9298-11e7-9515-6ca1f6efae97.png">

On Android, drawer works perfectly and status bar looks like good. While on ios it overlaps. How can it be solved? I am using expo and tried all in their documentation still the same issue I see on the simulator.

**Comment by khanghoang** [comment]
@Hayko1994 you can workaround by calling hide/show status bar on iOS. I've seen a lot of apps do the same thing (Google Inbox and Slack).

**Comment by kelset** [comment]
Pinging OP @Hayko1994 since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open (does it still happen in the latest version?); if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @Hayko1994 ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by Knierim** [comment]
just use css. in case your side drawer is an aside, use this:

aside {
  top: env(safe-area-inset-top)!important;
}
