### ISSUE TITLE
Drawer Navigation goBack() fade out animation

### ISSUE THREAD

**Issue by MelodiiLy** [react-community/react-navigation#2542]
Hello, in my Drawer Navigation, it's the normal transition when I go to a screen in Drawer Mune. However, when I goBack() from this screen, the transition becomes fade out. Is this normal? How can I get the normal transition with goBack()? Thanks!

**Comment by spencercarli** [comment]
Could you provide a reproduction of what you're experiencing? And/or video/gif? Also, what's your environment?

**Comment by kelset** [comment]
Hi there @MelodiiLy,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since Spencer's last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
