### ISSUE TITLE
Custom Overflow tab can not works on Android

### ISSUE THREAD

**Issue by guoliang1206** [react-community/react-navigation#2547]
I need design my tab like this, but it didn't works well on android, it will be cut down.
![2017-09-07 9 40 31](https://user-images.githubusercontent.com/12846676/30142205-0be3620c-93b2-11e7-9134-3e470ab8ede3.png)

I have search some issues, does the RN in android not support the overflow:'visible'? 
How can I realize this required?

**Comment by khanghoang** [comment]
@guoliang1206 I think in your case, you may need to use a custom tabbar view.

**Comment by mantas-janulionis** [comment]
You should use FlatUIImplementationProvider on android to enable overflow:'visible'

**Comment by spencercarli** [comment]
Since this is a non-standard tabbar it's not something that this library supports.

That being said, as @khanghoang mentioned, you can create a customized tabbar for your application that has the necessary design. A great starting point would be the [TabBarBottom](https://github.com/react-community/react-navigation/blob/master/src/views/TabView/TabBarBottom.js) so you can get a sense of how the tab bar currently works.

Good luck!

**Comment by est7** [comment]
@guoliang1206 怎么样,你最后怎么实现的?

**Comment by AmirHosseinSalari** [comment]
@guoliang1206 Hi, did you find the solution?

**Comment by wuyunqiang** [comment]
@guoliang1206  are you solution?
