### ISSUE TITLE
React.createElement: type is invalid

### ISSUE THREAD

**Issue by mike-niemand** [react-community/react-navigation#2552]
I'm hoping this is me making an error but I get: 

_React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in._

Whenever I try and wrap a stack navigator in a view as follows:

```
return (
            <View style={{flex: 1}}>
                <Stack onNavigationStateChange={null} />
            </View>
        );
```
If I remove the View tags it works fine. I have the same problem if I set headerLeft to anything more complex than a `<Button />` e.g. `<View><Text>Press me</Text></View>`

Am I missing something simple?

**Comment by spencercarli** [comment]
We need more info about your code. From looking at the little bit you've provided I'm guessing it's your import throwing things off. Looks like you're importing `Stack` rather than `StackNavigator`. Try

`import { StackNavigator } from 'react-native';`

Also, this type of question is better suited for StackOverflow or #react-navigation on Reactiflux as it's a usage issue rather than a library bug or feature request. I encourage you to ask there if my solution didn't work. Thanks!
