### ISSUE TITLE
TabNavigator dynamic tab implementation

### ISSUE THREAD

**Issue by TrustTheBoy** [react-community/react-navigation#2570]
Hi all, I am currently implementing dynamic TabNavigator, the number of tabs depends on the number of database stores. Stupid I encountered an unsolvable question: the label view can not determine which index the current God is clicking on, or how to use the `screenProps` passer, use this way to communicate`screenProps = {this.state.tabData [index]} ` ?

```javascript
...
onTabScrollView = () => {
        if (this.state.tabData && this.state.tabData.length>0) {
            let classData = {};
            let tabData = this.state.tabData;
            for (let i = 0; i < this.state.tabData.length; i++) {
                classData[this.state.tabData[i].busid] = {screen:TextViewTest,navigationOptions:{tabBarLabel: this.state.tabData[i].busname}};
                tabData[i].index = i;
            }
            let Tab = TabNavigator(classData,OPTION);
            return <Tab screenProps={this.state.tabData} index={0}/>
        }
        return <View><Text>null </Text></View>
    }
    render(){
        return(
            <View style={{flex:1,backgroundColor:'red'}}>
                {this.onTabScrollView()}
            </View>
        );
    }
...
```
and TextViewTest
```javascript
class TextViewTest extends Component {
    static tabBarOptions = { activeBackgroundColor:"red" };
    render(){
        return(
            <View style={{flex:1,backgroundColor:'green'}}>
                <Text>{this.props.screenProps[0].processkey}</Text>
            </View>
        );
    }
}
```
and sample graph
![qq20170912-101752](https://user-images.githubusercontent.com/20201085/30305144-d4eb8d64-9736-11e7-8fa4-49e74b538df8.gif)

```javascript
 this.props.screenProps[0].processkey
````

**Comment by TheTekton** [comment]
Kind of difficult to read. Also funny as God made it into the translation. 🤣 If I understand correctly, you're asking how to provide your tab data array as a prop to screenProps?

What about something like the following?

TabScroll.js
```
onTabScrollView = () => {
  // ...
  return (
    <Tab screenProps={{ data: this.state.tabData[0] }} index={0}/>
  );
// ...
```

TextViewTest.js
```
class TextViewTest extends Component {
    // ...
    render() {
        return (
            <View>
                <Text>{this.props.screenProps.data.processkey}</Text>
            </View>
        );
    }
}
```

**Comment by dustturtle** [comment]
how to create dynamic tabs & stack screens? I only got the static usage from the demo. Please help! 
openglnewbee@163.com    If someone can tell me or send me an email, thanks a lot!

**Comment by kelset** [comment]
Pinging OP @TrustTheBoy since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open (does it still happen in the latest version?); if I get no answer in the next 7 days I will close it.

---

@dustturtle 
> how to create dynamic tabs & stack screens?

Currently that I know of there is no "standard" way.

**Comment by kelset** [comment]
Hi there @TrustTheBoy ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
