### ISSUE TITLE
Cannot update during an existing state transition

### ISSUE THREAD

**Issue by JSafaiyeh** [react-community/react-navigation#2571]
After a user logs into the application I want to clear the navigation stack.

I use the following code to achieve that:
```javascript
resetNavStack = () => {
    const resetAction = NavigationActions.reset({
      index: 0,
      actions: [
        NavigationActions.navigate({ routeName: 'HomeStack' }),
      ],
    });

    this.props.navigation.dispatch(resetAction);
  }
```

On the transition I get this error:
`Warning: Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`.`

What is the solution to resolve this? Thanks!

**Comment by dantman** [comment]
Where does `resetNavStack` get called from?

**Comment by JSafaiyeh** [comment]
@dantman resetNavStack gets called when login is successful.

`<LoginForm onLoginSuccess={() => this.resetNavStack()} />`

**Comment by dantman** [comment]
@JSafaiyeh And when does `LoginForm` call `onLoginSuccess`?

**Comment by kelset** [comment]
Pinging OP @JSafaiyeh since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open (does it still happen in the latest version?); if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @JSafaiyeh ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
