### ISSUE TITLE
Stack Navigator stacking issue with nested navigator

### ISSUE THREAD

**Issue by sooxiaotong** [react-community/react-navigation#2577]
Stack navigator nested in Drawer navigator can navigate to itself and stacking above it until device lagging. I want when clicking the same item in drawer on the same page, simply close the drawer.
![ios](https://user-images.githubusercontent.com/13378059/30391232-397d8bd2-98eb-11e7-8050-814f393921fa.gif)

|software|version|
|--- |--- |
|react-navigation| 1.0.0-beta.11
|react-native|0.47.2|

**Comment by matthamil** [comment]
You can prevent this by using the `navigation` prop to detect the current route. If the current route name matches the name of the route you are navigating to, prevent the navigation action from firing.  Currently, the library does not support idempotent actions (you can navigate to the same screen over and over) but it is part of the new roadmap. https://github.com/react-community/react-navigation/issues/2585. Until this exists in the lib, you'll need to hand-roll a solution.

**Comment by sooxiaotong** [comment]
I'm using redux, and `onnavigationstatechange` doesn't work too, i have no idea how to detect the previous and current route =)

**Comment by GantMan** [comment]
@here - that issue is happening because it thinks there's a new item being pushed, instead of referencing a stack for it to bring back into memory. 

If you see the structure I outline in my blog post: https://shift.infinite.red/react-navigation-drawer-tutorial-a802fc3ee6dc

YOu can see a way that prevents stacking.  But if you reference outside of a stack, it will push.  Makes sense?

**Comment by adkl** [comment]
@matthamil How do you prevent a navigation action?

**Comment by GantMan** [comment]
you would have to prevent the dispatch.

**Comment by adkl** [comment]
I haven't found a way to prevent the already fired dispatch :/ . Are you talking about simply not dispatching any action or...?

**Comment by GantMan** [comment]
So yes, the goal is to get to where the dispatch is being fired and not run it.   

A second method is to change what listens and reacts to the dispatch.

But you can't actually unring the bell. When a dispatch is fired, it's done.

**Comment by kelset** [comment]
Pinging OP @sooxiaotong since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open (does it still happen in the latest version?); if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @sooxiaotong ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by Kwamena-S** [comment]
Hi. Has there been a definite solution for this issue? @GantMan 's solution fixes this issue, but has the drawer covering only the screen and not the header.
