### ISSUE TITLE
Pass NavigationSceneRendererProps to transitionSpec

### ISSUE THREAD

**Issue by AndreiCalazans** [react-community/react-navigation#2591]
For custom transitions, we can define different transitions inside the screenInterpolator thanks to the NavigationSceneRendererProps. Could we maybe have the same thing happen to the  transitionSpec ?

If transitionSpec was also to get the NavigationSceneRendererProps we'd be able to define custom specs for each transition, as its my case at the moment.

**Comment by msaray818** [comment]
the NavigationSceneRendererProps we'd be able to define custom specs for each transition, as its my case at the moment.

**Comment by kelset** [comment]
Pinging OP @AndreiCalazans since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open (does it still happen in the latest version?); if I get no answer in the next 7 days I will close it.

Moreover, I think this PR https://github.com/react-community/react-navigation/pull/2946 should enable what you ask - you should be able to test via master.

**Comment by AndreiCalazans** [comment]
Thanks
