### ISSUE TITLE
TabBar location moved up (shouldn't) when Android keyboard is shown

### ISSUE THREAD

**Issue by yctung** [react-community/react-navigation#2607]
### Current Behavior
I set the location of tab bar in the bottom. In this case, the tab bar element will move (incorrectly) to above the keyboard when the keyboard is shown (https://imgur.com/a/81vkn)

### Expected Behavior
Tab bar should keep in the bottom and be blocked by the shown keyboard (right?).

### Your Environment
"react-navigation": "1.0.0-beta.11"
Andorid Nexus 6p

Attached is the example picture of it: https://imgur.com/a/81vkn

**Comment by justinlok** [comment]
I solved this by using a custom tabbar component and adding keyboard listeners.

    componentWillMount() {
        this.keyboardDidShowListener = Keyboard.addListener('keyboardDidShow', () => this.setState({visible:false}));
        this.keyboardDidHideListener = Keyboard.addListener('keyboardDidHide', () => this.setState({visible:true}));
    }

    componentWillUnmount() {
        this.keyboardDidShowListener.remove();
        this.keyboardDidHideListener.remove();
    }

**Comment by AtticusFetch** [comment]
in AndroidManifest.xml, android:windowSoftInputMode="adjustResize|stateAlwaysHidden|adjustPan"
did the thing for me

**Comment by spencercarli** [comment]
@AtticusFetch's answer is correct. This is an android configuration issue

**Comment by junshengpierre** [comment]
Setting `android:windowSoftInputMode="adjustResize|stateAlwaysHidden|adjustPan"` in AndroidManifest.xml causes the entire app to lose the ability to have the layout moved up by the keyboard including text inputs. Does anyone know how to prevent only the tab bar from being moved up?

**Comment by Jp3rd** [comment]
any updates on this?

**Comment by Jp3rd** [comment]
I found the answer [here](https://github.com/happypancake/react-native-tab-navigator/issues/48)

**Comment by davebro** [comment]
@Jp3rd That solution does the same thing @junshengpierre said it should not do. It basically takes away the ability for any content, like buttons or text inputs, to move to the top of the keyboard when shown. The real functionality I think we want is, when the keyboard is shown, keep the tabbar at the bottom, but allow for other content, like a save button or something, to show at the top of the keyboard. Since there doesn't seem to be a way to support that currently in react navigation, I suppose the temporary solution would be to use a custom tabbar and control using keyboard listeners.
