### ISSUE TITLE
StackNavigation must register Component at first?

### ISSUE THREAD

**Issue by MrErHu** [react-community/react-navigation#2612]
For example, I has a ListView and each item navigate to a screen that is also a ListView and same as before. So I has many screen need to be registered in StackNavigation. Is there any way to register many times? 
The result like this:
![](http://oj232uzqf.bkt.clouddn.com/123.gif)

**Comment by vonovak** [comment]
In an effort to decrease the number of open issues, I'll close this one since it's not an issue but rather a question. Now, if I were trying to achieve this, I would not create a separate screen for *each* of the items, but only create one or two screens that would render the correct thing based on a parameter that you'd pass when navigating.
