### ISSUE TITLE
RFC: Merge default navigationOptions with screen navigationOptions.

### ISSUE THREAD

**Issue by miracle2k** [react-community/react-navigation#263]
I'd like to propose that this behaviour (by design according to https://github.com/react-community/react-navigation/issues/170) change.

I completed expected them to be merged, and I am not really convinced they shouldn't be. It seems a very common use case that I'd want to change the color of the navigation bar globally, and then add some left/right buttons on various screens.

The current way forces users to manually merge in the default header config for *every* screen.

I even think that this can be added w/o affecting backwards-compatibility all that much. If `header` is a function, the user can manually handle the parent values. But if header is given as an object literal, then merge it.

**Comment by grabbou** [comment]
We had this feature working for a while but turned it off as there were a lot of discussions regarding that. 

CC: @ericvicenti @satya164

**Comment by satya164** [comment]
cc @skevy too

**Comment by brentvatne** [comment]
I agree with this, we should merge them

**Comment by ericvicenti** [comment]
We already *do merge* at the top level navigationOptions, so if we had a `headerColor` navigation option rather than `header.color` option, you would have the expected behavior. This is exactly why I wish we had a flatter list of nav options, rather than having them name-spaced into `header`, `tabBar`, etc.

@miracle2k, to make this proposal more clear, can you write a brief code sample, (maybe your header color example), with a comment saying what would change, ("this would be red, but I think we should change the behavior so it is blue").

Is the leading proposal to do a deep merge of navigation options? Or only merge one more level? Or should we add logic to only merge the "header" option?

If you need the merging behavior in the mean time, you can implement it here like @satya164 demonstrated: https://github.com/react-community/react-navigation/issues/170#issuecomment-277286638

**Comment by grabbou** [comment]
Closing as options are now flat.
