### ISSUE TITLE
DrawerNavigator open already focused screen

### ISSUE THREAD

**Issue by matheusrocha89** [react-community/react-navigation#2648]
When I use the DrawerNavigator I put the screens on a Stack to show the header like I saw in some closed issues here, "To show header on DrawerNavigator screens, wrap the screen on a StackNavigator". For me that's fine but I think there is a behavior that can be improved. If this wrapped screen has a big Stack this can be a problem cause the DrawerItem reopen focused screens if you tap on it. 
To avoid that I used the `onItemPress` method for `DrawerItems` and verify if the item pressed is focused, if it is I just close the drawer to avoid open the same stack again and have performance issues and navigation issues since If I don't do that and clicked on the focused `DrawerItem` when I tap on Android hardware back button I will navigate back to the same stack cause it's opened more the once.

What I suggest is that maybe, this verification can be the default, what do you think guys? If you want maybe I can help opening a pull request.

### Current Behavior
 - If you press a focused option on DrawerMenu the new screen or stack is opened again.

### Expected Behavior
- If you press a focused option on DrawerMenu just close the menu and avoid open the already opened screen or stack.

### Your Environment
 - Android device
 - Android emulator

| software         | version
| ---------------- | -------
| react-navigation | v1.0.0-beta.12
| react-native     | 0.45.1
| node             |  7.5.0
| npm or yarn      |  npm: 4.1.2 yarn: 1.0.0

**Comment by matheusrocha89** [comment]
My bad, I saw the code of the DrawerSidebar you already do that, I think that because I changed the `contentComponent` "To achieve a scrollable View" like I read on [docs](https://reactnavigation.org/docs/navigators/drawer#Example:) Maybe we should remember the user about this behavior that he needs to treat if he try the same approach

**Comment by kelset** [comment]
Pinging OP @matheusrocha89 since this issue has not been active for a while, and it's related to an old version of the lib.

Moreover it looks like in your second comment you answered your own question ;)

Please let me know if you want this to remain open (does it still happen in the latest version?); if I get no answer in the next 7 days I will close it.

**Comment by abartolo** [comment]
Hey @matheusrocha89 , how did you end up handling this problem? I am currently in this situation but would like to see your approach to get a better understanding.

**Comment by abartolo** [comment]
@matheusrocha89 to follow up on my question. I think I may have found an answer. So what I basically need is my custom Drawer to NOT open a new screen if the screen is already on the stack. Without this there will be multiple stacks existing and slow down the app heavily if the users goes back and forth through the application.

The following link might help since it looks through the stack if the screen is already there and goes to it instead of adding another to the stack.

https://stackoverflow.com/questions/46607156/react-native-go-back-to-a-specific-screen-in-stack

**Comment by matheusrocha89** [comment]
@abartolo I did exactly that, I verified if the screen that I am trying to navigate is already opened, if it is I just close the drawer, if not I will navigate to the new screen.
