### ISSUE TITLE
android 7.1兼容问题

### ISSUE THREAD

**Issue by AngelaZhouxiaoxiao** [react-community/react-navigation#2672]
打开纯RN开发的app 进入某个功能页，然后再按home键，此时app从后台回到前台会正常停留在之前打开的页面，但如果从桌面通过点击icon进入app则会进入到APP的首页而不是之前打开的页面。

**Comment by kelset** [comment]
Hi @AngelaZhouxiaoxiao  ! It looks like this is a general question about react-navigation: I suggest next time you use [Stack Overflow](https://stackoverflow.com/search?q=react-navigation) which is better suited for answering these types of questions. I also encourage you to join the [Reactiflux](https://www.reactiflux.com/) community on Discord. There are React Native and React Navigation channels with helpful people who might be able to answer your question. I would also like to mention that there is a collection of helpful links and tutorials for React Navigation [here](https://github.com/react-navigation/react-navigation-links) which might be helpful for you.

That said, I am not completely sure since I don't speak what I think is japanese - and since you haven't followed the issue template it makes it quite hard to understand anyway.

If you believe that you are experiencing a bug or have a feature request, please open a new Issue following the dedicated template or submit a PR.
