### ISSUE TITLE
Imported files not working

### ISSUE THREAD

**Issue by mbbarry91** [react-community/react-navigation#2717]
I have imported two files which I want to navigate to but it runs into error like this one 
Bundling `index.android.js`  [development, non-minified, hmr enabled]  32.2% (452/797), failed.
error: bundling failed: "Unable to resolve module `./CustomerComponents/MapContainer` from `C:\\Users\\Barry\\Desktop\\T
axiMoto\\Navigation\\Routes.js`: could not resolve `C:\\Users\\Barry\\Desktop\\TaxiMoto\\Navigation\\CustomerComponents\
\MapContainer' as a folder: it did not contain a package, nor an index file"

![error1](https://user-images.githubusercontent.com/25786816/31324454-44294838-ace5-11e7-999c-6d3bd9edc622.PNG)

I have also tried the suggested solution but none of them seem to be working as the error still

**Comment by kelset** [comment]
This is not an issue with the library, as the error says it's related to the way you import the file `MapContainer`.

By the look of it, since I cannot see where the `Routes.js` file is stored, I assume it's in /Navigation. If that's the case, you need to write `../CustomerComponents/MapContainer` I think.

Again, not related to the library, so I'm closing this issue.
