### ISSUE TITLE
Error: Maximum call stack size is exceeded appears, while navigating to anther screen

### ISSUE THREAD

**Issue by adsellor** [react-community/react-navigation#2746]
I have two screens in my projects, LoginView and SignupView, there is an error message [Maximum call stack size is exceeded]. It seems like it is calling the function to navigate to screen recursively, but I couldn't find anything. Is it react-navigation bag or am I doing smth wrong.
Here is the code for the screen I need to navigate from 
```
/**
 * flow 
 * Login view
 */

import React, { PureComponent } from 'react';
import {
    View,
} from 'react-native';

import styled from 'styled-components/native';
import DefaultButton from '../components/default-button';
import Hr from '../components/horizontal-line';


class LoginView extends PureComponent {
    render() {
        return (
            <LoginContainer>
                <DefaultButton icon='facebook' iconColor='#3B5998' background='#fff' value='Login with Facebook' />
                <DefaultButton icon='google' iconColor='#d62d20' background='#fff' value='Login with Google' />
                <Hr />
                <DefaultButton onPress={() => this.props.navigation.navigate('Signup')} value='Log In / Sign Up' />
            </LoginContainer>
        )
    }
}


const LoginContainer = styled.View`
    justify-content: center;
    align-items: center; 
    flex: 1;
    background: #787878;
`;

export default LoginView
```

Here is code of the screen I need to navigate to 
```
import React, { PureComponent } from 'react';
import {
    View,
} from 'react-native';

import styled from 'styled-components/native';
import DefaultButton from '../components/default-button';
import DefaultInput from '../components/default-input';
import Hr from '../components/horizontal-line';

class SignupView extends PureComponent {
    render() {
        return(
            <LoginContainer>
                <DefaultInput value='E-Mail' />
                <DefaultInput value='Password' />
                <DefaultButton value='Login' />
            </LoginContainer>
        )
    }
}


const LoginContainer = styled.View`
    justify-content: center;
    align-items: center; 
    flex: 1;
    background: #787878;
`;

export default SignupView
```

Here is the navigation stack config 
```
/** flow
 * Navigation config file
 */

import { StackNavigator }  from  'react-navigation';
import LoginView from '../views/LoginView';
import SignupView from '../views/SignupView';



export default RegistrationStack = new StackNavigator({
    Login: {
        screen: LoginView,
        navigationOptions: {
            header: null,
        },
    },
    Signup: {
        screen: SignupView,
        navigationOptions: {
            header: null,
        },
    },
})
```

**Comment by kelset** [comment]
Hi @adsellor! It looks like this is not a bug of the library nor a feature request: I suggest next time you use [Stack Overflow](https://stackoverflow.com/search?q=react-navigation) which is better suited for answering these types of questions. I also encourage you to join the [Reactiflux](https://www.reactiflux.com/) community on Discord. There are React Native and React Navigation channels with helpful people who might be able to answer your question. I would also like to mention that there is a collection of helpful links and tutorials for React Navigation [here](https://github.com/react-navigation/react-navigation-links) which might be helpful for you.

That said, if by removing

`                <DefaultButton onPress={() => this.props.navigation.navigate('Signup')} value='Log In / Sign Up' />
`

from the Login View it means that the call stack is not caused by that method.

Moreover, I'm sort of concerned by your definition - can you try rewriting it this way?

```js
export default RegistrationStack = new StackNavigator({
    Login: {
        screen: LoginView,
    },
    Signup: {
        screen: SignupView,
    },
}, {
   navigationOptions: {
        header: null,
   },
})
```



If you believe that you are experiencing a bug or have a feature request, please open a new Issue following the dedicated template or submit a PR.
