### ISSUE TITLE
Unable to pass parameters to another screen on navigationoption

### ISSUE THREAD

**Issue by rjamaro** [react-community/react-navigation#2779]
Hi all,

I am trying to pass parameters to another screen when I press a button on navigation options, but on the next screen I receive the following message when I try for instance to display the customer name. 

The error message I am getting is "undefined is not an object (evaluating 'params.customer.name')"

The code that I am using to call is the following:

![image](https://user-images.githubusercontent.com/6115281/31707142-6ca951e0-b3fc-11e7-8ea3-f60dc8691fa8.png)

The code that I am using to process the information passed is the following:

![image](https://user-images.githubusercontent.com/6115281/31707186-8ee40304-b3fc-11e7-9034-42095c6f25f8.png)

Any ideias?

Thanks

**Comment by sanjayholla94** [comment]
Please post this question on StackOverflow, link it back here and close the issue. It'll really help us manage the issues if you post **questions** on a separate platform. 
Having said that, I can see that you're passing the wrong params in your navigate function.
The problem is with this code:
```js
const { params } = navigation.state.params.customer 
```
Assuming that you wanted to pass the customer object from `CustomerInfo` to `UpdateCustomer`, you should change it to the following:
```js
//this will assign the value of params.customer to the const variable
const { customer } = navigation.state.params; 
navigation.navigate('UpdateCustomer', {customer}); 
```
You'll be able to access it by through `this.props.navigation.state.params.customer`

Please read the [docs](https://reactnavigation.org/docs/intro/#Passing-params) thoroughly before posting an issue

**Comment by rjamaro** [comment]
thanks
