### ISSUE TITLE
Custom actions do not get propagated to StackRouter child routers

### ISSUE THREAD

**Issue by TikiTDO** [react-community/react-navigation#284]
I am trying to create a custom router to respond to my app's events as per the `Custom Navigation Actions` section of the [official guide](https://reactnavigation.org/docs/routers/). 

When I nest a navigator using my custom router within a StackNavigator, my custom router fails to receive actions from the parent.

**Comment by matthamil** [comment]
Hi there! This issue is being closed because it has been inactive for a while. We're closing issues after a period of inactivity. Please do not take this personally :)
If you think this issue should remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:
* Does the issue still reproduce on the latest release? Post a comment with the version you tested.
* If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/react-community/react-navigation/blob/master/.github/ISSUE_TEMPLATE.md).
* Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.
If you would like to work on a patch to fix the issue, contributions are very welcome! Read through the [contributors guide](https://github.com/react-community/react-navigation/blob/master/docs/guides/Contributors.md), and feel free to hop into [#react-navigation](https://reactiflux.com) if you need help planning your contribution.
