### ISSUE TITLE
Screen transition bleeds activity background color and makes screen content transparent 

### ISSUE THREAD

**Issue by gilbertKaradja** [react-community/react-navigation#2842]
### Current Behavior(Android)
If I have a background color set for my activity, say green, when page transitions occur within my application you will see a shadow with said color covering the previous page before the new page is stacked on top.
You can see an example here (https://stackoverflow.com/questions/46867697/react-native-android-screen-content-becomes-transparent-on-navigation).  Also sometimes some of the content in the previous page turns transparent when navigating. 

### Expected Behavior
Using the old, cross-platform navigator provided by react-native did not result in this behavior although in that navigator the animation was a bit different.  Instead of somewhat sliding pages on top each other it will scroll the full length of a screen instead.

### Your Environment
react-navigation: 1.0.0-beta.11
react-native : 0.48.1

**Comment by kelset** [comment]
Hi, thanks for reporting.

Some quick follow up questions:
1. have you tried updating to the latest release?
1. does it happen only on Android?
1. does it happen on both debug and release modes?
1. does it happen with Debugger on or off? Both?
1. from the screenshots in the SO question it's kinda of hard to understand where the issue is; I mean, is your issue only "during" the animation of the navigation or something "weird" appearing after the navigation? Can you provide a GIF or a repo or a [snack](https://snack.expo.io/) to reproduce this issue?

**Comment by kelset** [comment]
Ping @gilbertKaradja - please answer my questions or I'll close this issue for inactivity.
Moreover, we just released a new version ´beta.17´ which I think will help you out.

**Comment by gilbertKaradja** [comment]
Hi, 
Sorry for the long delay.
1) Not yet
2) Tested only on Android
3) Both versions
4) Both
5) Its only during the animation. 

I was able to resolve the issue by settitng:

cardStyle: {
    opacity: 1
}

**Comment by kelset** [comment]
Ok, so I think the issue can be closed. Let me know if you think it should be open.
