### ISSUE TITLE
StackNavigator inside DrawerNavigator inside StackNavigator.error!

### ISSUE THREAD

**Issue by RoarRain** [react-community/react-navigation#2877]
I want use  route  inside DrawerNavigator, I push a StackNavigator inside DrawerNavigator,
it is error.

`This navigator has both navigation and container props, so it is unclear if it should own its own state. Remove props: "items, activeItemKey, getLabel, renderIcon, onItemPress, router" if the navigator should get its state from the navigation prop. If the navigator should maintain its own state, do not pass a navigation prop`

`
const CustomerManagerDrawerNavigator = DrawerNavigator(
    {
     
        CustomerManager: {
            screen: CustomerManager
        },

    }, {
        drawerWidth: 300,
        drawerPosition: 'right',
        contentComponent: MenuNavigator
        },
);
export default CustomerManagerDrawerNavigator;
`

`const MenuNavigator = StackNavigator({

    ExportClues: {
        screen: ExportClues
    },

    SelectDateTime: {
        screen: SelectDateTime
    }

});

export default MenuNavigator;
`

How to use it?

| software         | version
| ---------------- | -------
"react-navigation": "^1.0.0-beta.16",
 "react-native": "0.48.0",
 "npm": "^5.3.0",

**Comment by kelset** [comment]
Hi @RoarRain ! It looks like this is not a bug of the library nor a feature request, so I'll close it: I suggest next time you use [Stack Overflow](https://stackoverflow.com/search?q=react-navigation) which is better suited for answering these types of questions. I also encourage you to join the [Reactiflux](https://www.reactiflux.com/) community on Discord. There are React Native and React Navigation channels with helpful people who might be able to answer your question. I would also like to mention that there is a collection of helpful links and tutorials for React Navigation in the [README](https://github.com/react-community/react-navigation#community-contributions) which might be helpful for you.

If you believe that you are experiencing a bug or have a feature request, please open a new Issue following the dedicated template or submit a PR.

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
