### ISSUE TITLE
how do you guys develop quickly?

### ISSUE THREAD

**Issue by pvinis** [react-community/react-navigation#2879]
i want to contribute more.
i have the `NavigationPlayground` running, but everytime i make a change in the library, i need to stop the packager, `trash node_modules`, `yarn install`, `yarn start`, do `R` to reset the cache, then i see my change.
is there a way to do this loop faster?
how do other contributors here work?
thanks.

**Comment by kelset** [comment]
Ping @davepack @Ashoat @vonovak

**Comment by vojtechnovak** [comment]
Hi! I recommend using haul. The big deal about haul is that it supports symlinks, so then you can have your navigation playground in location A, your react-navigation fork in location B and using `yarn link` you can use that fork with your playground.

That being said, if you want to work on something bigger I suggest you first let us know by asking in the corresponding issue so we can tell you how fast we'll be able to review the contribution, because we all have a number of PRs that we already plan to review. If reviewing PRs is something you would like to do, that would be extremely helpful too. I can provide you with a list of PRs that you could review, let me know if you are interested.

**Comment by vonovak** [comment]
Sorry, I previously commented from a different account.

Hi! I recommend using haul. The big deal about haul is that it supports symlinks, so then you can have your navigation playground in location A, your react-navigation fork in location B and using yarn link you can use that fork with your playground.

That being said, if you want to work on something bigger I suggest you first let us know by asking in the corresponding issue so we can tell you how fast we'll be able to review the contribution, because we all have a number of PRs that we already plan to review. If reviewing PRs is something you would like to do, that would be extremely helpful too. I can provide you with a list of PRs that you could review, let me know if you are interested.

**Comment by pvinis** [comment]
i dont know haul, so i will check it out today.

about the things to work on, i will do as you say for it.

i would be open to help you with the prs. i like this repo/library, but it used to be very left out. im happy to help make it better, and more active.

**Comment by pvinis** [comment]
i dont see how `haul` can help. the `NavigationPlayground` is a crna app, so haul isnt even able to work there.

am i missing something?

**Comment by Ashoat** [comment]
I think npm handles `file:..` with symlinks, whereas yarn copies the folder wholesale. I’m not sure why yarn behaves differently, and I agree it slows down development. The symlink solution has its own quirks - you end up with duplicate module providers, and I’ve had to use a rn-cli.config.js in the past to tell the packager (default one, not haul) to ignore certain directories. This is what I do for react-native-tag-input, a package I help maintain. I haven’t actually set this up for react-navigation, however, since my contributions so far have primarily been in fixing Flow types, which doesn’t require as much compilation and re-compilation.

The packager also needs to watch symlinks when they exist, but the default packager does this now too, so afaik you don’t necessarily need haul for this.

I use symlinks in node_modules in my personal project as well. I actually committed the symlink to my repo there, so git always complains if there’s something wrong. However, I don’t have the duplicate module problem there.

**Comment by smithaitufe** [comment]
@vonovak *interested*

**Comment by kelset** [comment]
Thanks for your interest in helping out @smithaitufe & @pvinis!
Until @vonovak gives you a more precise list/sublists of PRs (if needed), here are some good places to start:
* PRs that have the label ["review needed"](https://github.com/react-community/react-navigation/labels/Status%3A%20Needs%20Review) - if you want to help out reviewing the code
* Issues with the tag ["help wanted"](https://github.com/react-community/react-navigation/labels/Status%3A%20Help%20Wanted) - if you want to help the community/answer questions/try to help figure out why an issue happens
* Issues with the tag ["Good First Task"](https://github.com/react-community/react-navigation/labels/Type%3A%20Good%20First%20Task) - these basically are opportunities for new PRs

The tagging is still not covering 100% of the PRs/Issues but we're getting there.
Thanks again for your interest! 🙏

**Comment by vonovak** [comment]
@pvinis sorry, I actually didn't use haul with navigation playground, only worked with my own app. As for what needs review - #2308 and #2790 come to my mind, and other than that just like kelset said, when you go through the PRs you'll probably find something that makes sense to merge. Thanks!

**Comment by vonovak** [comment]
Question was answered, closing :)
