### ISSUE TITLE
TabNavigator When you only need to set the text, the text is not centered vertically. Is there any solution?

### ISSUE THREAD

**Issue by azhon** [react-community/react-navigation#2884]
TabNavigator When you only need to set the text, the text is not centered vertically. Is there any solution?
<img width="375" alt="qq20171102-205840 2x" src="https://user-images.githubusercontent.com/20559556/32327205-a813504e-c010-11e7-9bec-b0d4e64bdde7.png">

**Comment by kelset** [comment]
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
