### ISSUE TITLE
I can't go back from StackNav to DrawerNav

### ISSUE THREAD

**Issue by wsupajirakit** [react-community/react-navigation#2934]
Start from 1Screen (DrawerNav)-> Profile (Stack Nav)

On ProfileScreen I can't use goback() but another screen on same Stack can use it.
```

  render() {

    const backAction = NavigationActions.back({
    key: '1Screen'
      })

    const {goBack} = this.props.navigation;

    return (
      <Button small transparent
      onPress={this.props.navigation.dispatch(backAction)}>           <<<<< Not work
      </Button>

      <Button small transparent
      onPress={() => goBack()}>                             <<<<< Not work
      </Button>

     )
```

```


export const Profile = StackNavigator({
  ProfileScreen: {
    screen: ProfileScreen,
    navigationOptions: {
      gesturesEnabled: false,
      header: null,
    },
  },
  ChangePasswordScreen: {
    screen: ChangePasswordScreen,
    navigationOptions: {
      gesturesEnabled: false,
      header: null,
    },
  },
});


export const Drawer = DrawerNavigator ({
  1Screen: {
    screen: 1Screen,
    navigationOptions: {
          drawer:{
              label: 'Sc 1',
          },
        }
  },
  Profile: {
    screen: ProfileStack,
    navigationOptions: {
      drawer:{
          label: 'My Profile',
      },
    }
  },
});


```

**Comment by kelset** [comment]
That's because on `ProfileScreen` you are in the realm of the `StackNavigator`.
To go back in the realm of the `DrawerNavigator` you need to call the goBack from `ProfileStack`.

Closing because it's not a bug. Moreover is sort-of duplicate of https://github.com/react-community/react-navigation/issues/2559.

I suggest next time you use [Stack Overflow](https://stackoverflow.com/search?q=react-navigation) which is better suited for answering these types of questions. I also encourage you to join the [Reactiflux](https://www.reactiflux.com/) community on Discord. There are React Native and React Navigation channels with helpful people who might be able to answer your question. I would also like to mention that there is a collection of helpful links and tutorials for React Navigation in the [README](https://github.com/react-community/react-navigation#community-contributions) which might be helpful for you.

If you believe that you are experiencing a bug or have a feature request, please open a new Issue following the dedicated template or submit a PR.
