### ISSUE TITLE
Animate Header Height

### ISSUE THREAD

**Issue by LouisJS** [react-community/react-navigation#2943]
### Current Behavior

I'm trying to update the Header Height inside my screen when my Keyboard is visible.
To do this, I'm passing a parameter
```
static navigationOptions = ({ navigation, screenProps }) => ({
    title: 'Create an account',
    headerTintColor: 'white',
    headerStyle: {
      backgroundColor: '#59A6F9',
      borderBottomWidth: 0,
      height: navigation.state.params.heightSize
    },
  });
```
I've created a listener to my Keyboard and set a Callback in which i do :

```
this.props.navigation.setParams({heightSize: 300});
```

### Result

My height is changing. But it takes easily 1 to 2 seconds on my iOS simulator.
On my Android, its a bit quicker, and i think it waits for my Keyboard animation to end before triggering the Height's header update.

I've plan to add some animation to change that Height later.
Is there a better way to update this styling ?

**Comment by kelset** [comment]
Hi @LouisJS ! It looks like this is not a bug of the library nor a feature request, so I'll close it: I suggest next time you use [Stack Overflow](https://stackoverflow.com/search?q=react-navigation) which is better suited for answering these types of questions. I also encourage you to join the [Reactiflux](https://www.reactiflux.com/) community on Discord. There are React Native and React Navigation channels with helpful people who might be able to answer your question. I would also like to mention that there is a collection of helpful links and tutorials for React Navigation in the [README](https://github.com/react-community/react-navigation#community-contributions) which might be helpful for you.

That said, the fact that it's slow it's probably because you are trying to "overload" the app to handle both the keyboard moving and the setParam of the header at the same time. If you see a difference in time required between when you have the remote debugger on and off, then it means that it's your code (most likely) that is "heavy loading" the performances.

And
> i think it waits for my Keyboard animation to end before triggering the Height's header update.

It may be, depending on how you wrote the code to catch the keyboard interaction.

If you believe that you are experiencing a bug or have a feature request, please open a new Issue following the dedicated template or submit a PR.

**Comment by vonovak** [comment]
@LouisJS what event names have you used when subscribing? Have you tried `keyboardWillShow`?
