### ISSUE TITLE
Infinite loop when using setParams with nested stacked routers after reset action

### ISSUE THREAD

**Issue by dmhood** [react-community/react-navigation#296]
I've been banging my head against this for a bit and can't figure out the exact issue, but I think I'm pretty close.  Basically if you have two nested stacked routers and call navigate.reset to go to a screen which immediately calls navigate.setParams (such as in componentWillMount), the app will get stuck in an infinite loop.

Here is a reproducible example where I was using a redux version of NavigationPlayground: https://github.com/react-community/react-navigation/compare/master...sportsaction:error?expand=1

I can't find a specific issue in the router, but if you watch the logs you can see it tries to process the reset action over and over again.  I think this is related to #160 , but I'm not totally sure how.

If someone can help point me in the right direction I'd be happy to submit a PR!

**Comment by ericvicenti** [comment]
I'm not sure what is going wrong here, but needing to call setParams from `componentDidMount` is a major code smell. Hopefully you can find a way to refactor to avoid that situation.

**Comment by dmhood** [comment]
@ericvicenti if that's the case is there a better answer to https://github.com/react-community/react-navigation/issues/145 ?  How would we set left/right buttons dynamically when we navigate to a new scene?

**Comment by satya164** [comment]
> How would we set left/right buttons dynamically when we navigate to a new scene

Set them based on `params`

**Comment by dmhood** [comment]
That's not really practical when I'm trying to change the left/right nav buttons based on some sort of dynamic state/object.  For example, if I have a "User" screen and only want a "Message" button to show up if the user already has a verified email, should I have to add that logic to everything that links to the User screen?  I feel like that should definitely be something the User screen manages itself.

**Comment by satya164** [comment]
> That's not really practical when I'm trying to change the left/right nav buttons based on some sort of dynamic state/object.

How do you get that state in the component? Technically the only props the component receives are the params, if you can derive the state from params, you can do the same for header elements too.

> should I have to add that logic to everything that links to the User screen

Connect your left/right elements to redux, or use an HOC.

**Comment by ericvicenti** [comment]
Yep, I agree with @satya164's answer. If you don't want to use params, then use some other mechanism to allow data to flow into the component. Personally I would use redux connect

**Comment by dmhood** [comment]
I still think there are several issues with this approach, and a few issues are popping up because of it:  https://github.com/react-community/react-navigation/issues/210, https://github.com/react-community/react-navigation/issues/240, https://github.com/react-community/react-navigation/issues/145.

It seems inefficient to have to figure out the initial state twice (once statically for a button, then again for the actual component class instance), especially if it is an expensive operation.  Additionally things like context or the DOM in a web-app might have an impact on the header, and params/redux state won't cover it.

**Comment by ericvicenti** [comment]
> It seems inefficient to have to figure out the initial state twice (once statically for a button, then again for the actual component class instance)

Maybe there is a way to share the initial state between the two places?

> Additionally things like react context or the DOM in a web-app might have an impact on the header, and params/redux state won't cover it.

I'm having troubles visualizing this use case. It might be more clear with a bit of code.

**Comment by dmhood** [comment]
the initial post on https://github.com/react-community/react-navigation/issues/210 shows an example needing context.

**Comment by satya164** [comment]
> It seems inefficient to have to figure out the initial state twice (once statically for a button, then again for the actual component class instance), especially if it is an expensive operation.

You can use a memoization technique to avoid figuring out things twice.

> Additionally things like react context or the DOM in a web-app might have an impact on the header, and params/redux state won't cover it.

Yeah, a big problem is params is pretty limited.

To be honest, things like header are pretty coupled to the screen most of the times. But there are few problems when we don't have static properties. This design is the same as in ExNavigation. Things like drawer navigation won't be able to get the screen details unless you have a static property, since the screen isn't actually rendered.

A non-static `getNavigationOptions` method won't be very useful either since you'd want it go get called again when you do `setState`.

Though ExNavigation had a much better story, because you could bi-directionally communicate with your elements in the static configuration screen via events. You could pass full data in events, or anything really, unlike params, which are part of the navigation state and we expect params to be a flat object containing only strings, which makes them way less useful.

Here's the example https://github.com/exponent/ex-navigation/blob/master/example/components/EventEmitterExample.js

I think such a two-way communication in React Navigation will be a little difficult to achieve since you only have params, unless you use something like redux.

I proposed to use events in #51 since I think having an event system will be pretty useful for a lot of things, and I would prefer not to have both events and lifecycle methods. But there was a lot of pushback.

But let's talk about alternative solutions with what we have today.

Long back I talked to @skevy about something like this for ExNavigation,

```js
class MyScreen extends Component {
  static navigationOptions = {
    // define the options here
    // you can later override stuff from here in your render
  };

  render() {
    <View>
       <NavigationHelper.Header
          title='Hello there'
          right={<DoneButton />}
      />
      ... your content goes here
    </View>
  }
}

export default NavigationHelper.createScreen(MyScreen);
```

Under the hood, `NavigationHelper.createScreen` will setup an event system and copy your static properties onto the wrapper HOC. Then `NavigationHelper.Header` will communicate with the static options via a event system and update stuff inside header

Now, a big limitation of this approach is we can only support props which are React Elements (and fake it for things like title which support both strings and react elements), since we'd actually need lifecycle methods there to setup listeners. Then we can pass the full component via the event callbacks every-time they update. Not pretty, but the outer API is pretty nice since we get a nice declarative API and our components are located where they should live, inside `render`.

Now to support non-element configuration options, we'd need params to actually support any type of data and not just strings, so we could communicate via params instead of an event system. Plus it shouldn't cause stack overflow error.

This API can totally be outside core, but I think it's not possible to build this with what we have today. We can only build a pretty limited version of it.

What if `navigationOptions` was an observable instead? Then we could build this easily with the event system and support all kind of options. We could subscribe when screen mounts and unsubscribe when it unmounts, without having to setup listeners in `left`, `right` components etc. This sounds like taking it too far, but one can hope :D

**Comment by dmhood** [comment]
I agree that the even system sounds more flexible/easier to use.  Hopefully we can have something like that in the future!

FWIW I've gone back and implemented all the header logic I needed without using setParams in componentDidMount, but I still think it's likely this issue continues to pop up.  

As an aside, why does the lib expect state params to be only strings?  I've used all sorts of types all over the place and it seems fine.

**Comment by 0x6e6562** [comment]
@dmhood I've run into exactly the same issue as you - dispatching a navigation reset in a nested context when you use the `setParams/componentDidMount` hack causes the app to tailspin.

So it's back to the drawing board - it is funny that it is so difficult to connect the current state of a component to a header button - it doesn't feel like a strange use case.

Because of this, and the fact that it works well with ExNavigation, it's a shame that the event emitter paradigm suggested by @satya164 has not been adopted here.

**Comment by migueloller** [comment]
The discussion around https://github.com/react-community/react-navigation/issues/1639#issuecomment-305572963 seems to be relevant to the infinite loop in `setParams` and the need for props access for dynamic `navigationOptions`.

**Comment by 0x6e6562** [comment]
@migueloller https://github.com/react-community/react-navigation/issues/1639#issuecomment-305572963 appears to describe the effect that I am experiencing, so it's back to the drawing board.

It feels a bit heavyweight to dispatch form contents via the redux store - ideally I would like a header button to trigger the dispatch of the form data into the store when editing has been completed. Maybe I'm too set in my ways?

Because of this, I've been playing around with the pattern of setting `headerMode: 'none'` and rendering a custom header as suggesting by @richardfickling https://github.com/react-community/react-navigation/issues/707#issuecomment-300507321

**Comment by tiendn** [comment]
I has added **timeout** before `setParams`, and it works.
```javascript
setTimeout(() => {
  this.props.navigation.setParams({
     save: this.save.bind(this),
     ....
  });
}, 1000);
```

**Comment by lon-io** [comment]
See https://github.com/react-navigation/react-navigation/issues/2473#issuecomment-361107240 for a reference to how I was able to solve this

**Comment by mhuggins** [comment]
Although I'm new to hooks, I came up with a solution that feels like less of a hack to me (a la `setTimeout`).  I created a hook called `useDidMount` to ensure the code inside only runs on mount and not after re-renders.

```js
import { useEffect, useState } from 'react';

export default function useDidMount(callback) {
  const [mounted, setMounted] = useState(true);

  useEffect(() => {
    if (!mounted) {
      setMounted(true);
      callback();
    }
  });
}
```
