### ISSUE TITLE
A question about the source code

### ISSUE THREAD

**Issue by johnwatsondev** [react-community/react-navigation#2983]
### The issue list is reserved for bugs and feature requests, not for questions.
I know this. I have asked in reactiflux. But I still have no effective way to solve this question. Sorry about that. 😭 

### My Question
https://stackoverflow.com/q/47308311/3171537

### Environment
Newest react-navigation's master code

### I will close this issue later. Thanks in advance.

**Comment by kelset** [comment]
Hi @johnwatsondev! It looks like this is not a bug of the library nor a feature request, so I'll close it: I suggest next time you use [Stack Overflow](https://stackoverflow.com/search?q=react-navigation) which is better suited for answering these types of questions. I also encourage you to join the [Reactiflux](https://www.reactiflux.com/) community on Discord. There are React Native and React Navigation channels with helpful people who might be able to answer your question. I would also like to mention that there is a collection of helpful links and tutorials for React Navigation in the [README](https://github.com/react-community/react-navigation#community-contributions) which might be helpful for you.

That said, from my understanding, the basic version of an answer to your question is because `Transitioner` has been created in such a way that can be used for different purposes. There's also a section [in the docs](https://reactnavigation.org/docs/views/transitioner#render-function).

If you believe that you are experiencing a bug or have a feature request, please open a new Issue following the dedicated template or submit a PR.

**Comment by johnwatsondev** [comment]
@kelset Hello. My question is not the definition of `Transition`'s render function. My question is the `_render` method only has **ONE** parameter [here](https://github.com/react-community/react-navigation/blob/master/src/views/CardStack/CardStackTransitioner.js#L93). the `_render`'s flow definition is [here](https://github.com/react-community/react-navigation/blob/master/src/views/CardStack/CardStackTransitioner.js#L47).  And the `NavigationSceneRenderer` flow type is `() => React.Node` in [here](https://github.com/react-community/react-navigation/blob/master/src/TypeDefinition.js#L551). I'm just confused the function's definition in `CardStackTransitioner`.
