### ISSUE TITLE
[iPhone X] TabBarTop missing 20pt top padding

### ISSUE THREAD

**Issue by edo1493** [react-community/react-navigation#2986]
Hi guys, 

thanks for adding iPhone X support. It seems there is a 20pt top padding missing on TabBarTop. I am on the latest React Native and Navigation. I am not sure if this should go in react-native-tab-view or you left the padding out on purpose.

**Comment by kelset** [comment]
Closing because you haven't followed the issue template.

Moreover, I suggest you check these [two](https://stackoverflow.com/questions/46316879/react-native-odd-spaces-on-iphone-x) [links](https://medium.com/react-native-training/react-native-iphonex-92ff511282af) to make sure you have configured your iPhone X implementation properly.

If it still happen, open a new issue **that follows the template**

**Comment by edo1493** [comment]
They are not related, but thanks for pointing me out the internet does exist.
