### ISSUE TITLE
Click doesn't work 

### ISSUE THREAD

**Issue by hajjiTarik** [react-community/react-navigation#3025]
Hi, 

I'm working on an application with native react and react navigation all working very well until today.
I did a `npm update` and the version of react-navigation has changed

    from : "react-navigation": "1.0.0-beta.13",
    to : "react-navigation": "^ 1.0.0-beta.21",

then i can scroll but I can't click, and i have no error

Best regards

**Comment by matthamil** [comment]
Hi @hajjiTarik , thanks for the issue. It looks like there's not enough information for us to know how to help you.

If you're reporting a bug, please be sure to include:
1. What you did (the source code and navigation configuration)
2. The actual navigation behavior
3. What you expected to happen instead

Include as many relevant details about the environment you experienced the bug in:

| software         | version
| ---------------- | -------
| react-navigation |
| react-native     |
| node             |
| npm or yarn      |

If it's something else, please provide as much additional information as possible. Thanks!

**Comment by kelset** [comment]
Hi there @hajjiTarik,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since Matt's last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that **uses** the new Issue Template to provide some more details to help us solve it.
