### ISSUE TITLE
Navigate problems

### ISSUE THREAD

**Issue by fenglu09** [react-community/react-navigation#3070]
There is such a scene in my application,   `list -> detail -> list2 -> detail`.

### Current Behavior
Currently cannot go `detail` from `list2`, because list2 is navigate  from `detail`。
`Detail` screen is the same one width different `id`.
### Expected Behavior
After navigate to `list2` from `detail`, I need navigate to `detail` screen after press `item`  in `list`.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |1.0.0-beta.11
| react-native     |0.48.2
| node             |v6.9.1
| npm or yarn      |4.0.2

**Comment by kelset** [comment]
1. you are using a really old version of the library, please update to latest and let me know if that still happens 
1. please create a [Snack](https://snack.expo.io/) that reproduces the issue because in my project adding multiple times the same screen with different params works fine
1. are you using a state manager like redux?

**Comment by fenglu09** [comment]
It works with the latest version.  Thanks.
