### ISSUE TITLE
static NavigationOptions lost the props when use Decorator@

### ISSUE THREAD

**Issue by Mscynol** [react-community/react-navigation#3123]
If I use decorators, the navigator does not detect the static navigationOptions.
Is there a better way to solute it?

This does not work:
@NetInfoDecorator
export default class ManagerView extends Component {
    static navigationOptions = { headerTitle: 'manager' };
}
No title !!!!!

I can show the title when I don't use the decorator
This does not work:
export default class ManagerView extends Component {
    static navigationOptions = { headerTitle: 'manager' };
}

**Comment by kelset** [comment]
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a repo or a snack to reproduce this issue?

**Comment by marlti7** [comment]
same problem. fixed it?
