### ISSUE TITLE
Deep linking redirects to initialRoute screen if dynamic initialRoute is set

### ISSUE THREAD

**Issue by jinxac** [react-community/react-navigation#3129]
### Current Behavior
I have a scenario in which we have to change initialRoute screen dynamically based on few parameters.

Following is my stack navigator in which I have set **InitialRoute**.

```
const MainNavigation = StackNavigator({
  InitialRoute: {
    screen: InitialRoute
  },
  [ROUTE_CONSTANTS.WelcomeStart]: {
    screen: WelcomeExperience
  },
  [ROUTE_CONSTANTS.WelcomeFinish]: {
    screen: Welcome,
    navigationOptions: {
      gesturesEnabled: true
    }
   ...*/
  },
```

Here goes my InitialRoute which is basically a component which navigates to the screens:-

```
class BaseRedirector extends React.Component {
  /* eslint-disable react/no-unused-prop-types */
  static propTypes = {
    client: PropTypes.object.isRequired,
    dispatch: PropTypes.func.isRequired,
    navigation: PropTypes.object.isRequired,
    pinStatus: PropTypes.bool,
    refreshToken: PropTypes.string.isRequired
  };
  /* eslint-enable react/no-unused-prop-types */

  async componentWillMount () {
    const accessTokenInAsyncStore = await AsyncStorage.getItem(STORAGE_KEYS.accessToken);
    let route;
    const params = {};
    if (this.props.pinStatus) route = ROUTE_CONSTANTS.PinLogin;
    else if (!accessTokenInAsyncStore) route = ROUTE_CONSTANTS.WelcomeStart;
    else if (accessTokenInAsyncStore) {
      if (await shouldRefreshAccessToken()) refreshAccessToken(accessTokenInAsyncStore, this.props.navigation);
      this.props.dispatch(receiveAccessToken(accessTokenInAsyncStore));

      if (await this.isTransactionActive()) {
        if (this.props.refreshToken) {
          route = ROUTE_CONSTANTS.PinCreate;
        } else {
          this.props.dispatch(receiveAccessToken(""));
          removeAccessTokenDetailsFromAsyncStore();
          route = ROUTE_CONSTANTS.WelcomeStart;
        }
      } else {
        // FIXME: Replace does not work for tabs
        this.props.navigation.navigate(ROUTE_CONSTANTS.Tab, {
          noInvestment: true
        });
        return;
      }
    }
    replaceRoute(this.props.navigation, route, params);
  }

  isTransactionActive = async () => {
    const {data: {accounts}} = await this.props.client.query({
      query: LOGIN_REDIRECTION_QUERY,
      fetchPolicy: "network-only"
    });

    return !!(accounts && accounts.length && accounts[0].transactionActive);
  };

  render () {
    return (
      <View style={styles.container}>
        <WealthyActivityIndicator />
      </View>
    );
  }
}

function getLoginDetails (store) {
  const {wlStore} = store;
  const {login} = wlStore;
  const {pinStatus, refreshToken} = login;
  return {
    pinStatus,
    refreshToken
  };
}

module.exports = withApollo(connect(getLoginDetails)(BaseRedirector));
```

This works fine for me until deeplinking came into the picture. For deeplinking, I have 2 screens, one to reset password and one to login. Now **if I close the application** and open the link received in my email it opens the application and deeplinks to correct screen but immediately sends me to the screen returned by InitialRoute mentioned above. 

### Expected Behavior
Dynamic initial route should not interfere with deeplinks.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta-21
| react-native     | 0.47.2
| node             | 8.2.1
| npm or yarn      | 5.3.0

**Comment by jinxac** [comment]
@kelset can you please tell what more information is required?

**Comment by kelset** [comment]
I am a bit confused, can you explain me a bit better this:

>  it opens the application and deeplinks to correct screen but immediately sends me to the screen returned by InitialRoute mentioned above.

From my understanding:
1. app is closed
1. you click on an url
1. the url "deeplinks" into the app
1. the app opens and navigate to screen A
1. "something else" navigates from A to screen B

Is that correct?
To me it looks more like a "race condition" between the deep linking before the app has been loaded properly (ex. if you have redux persist in place). I don't see how it's a bug of the library.

(and please give me time to write a comment instead of jumping the gun)

**Comment by jinxac** [comment]
> (and please give me time to write a comment instead of jumping the gun)

My bad :) 

> To me it looks more like a "race condition" between the deep linking before the app has been loaded properly (ex. if you have redux persist in place). I don't see how it's a bug of the library.


Yes points 1-4 are correct and app navigate to correct deeplinked screen.  Now if dynamic initial route is set it automatically navigates to the screen returned by `InitialRoute Component
`. I tried commenting out this dynamic InitialRoute for time being and tried running the app and it works fine and it stays at deeplinked screen. 

Hope it explains it.

**Comment by kelset** [comment]
> Now if dynamic initial route is set it automatically navigates to the screen returned by InitialRoute Component

Ok then to me this says that your code is working fine, but it's just "late to the party".
Can you share your code where you handle deep linking?

In my app I "forced" the deeplinking to wait 1000ms before doing anything, so that I am sure that the app finished loading properly before anything.

Another approach would be to modify your dynamic initialRoute in order to "recognize" that the app has been opened by deep linking and to not do anything in that scenario.

Again, I don't see how this is a bug in the library.

**Comment by jinxac** [comment]
> Ok then to me this says that your code is working fine, but it's just "late to the party".
> Can you share your code where you handle deep linking?

```
  [ROUTE_CONSTANTS.ForgotPasswordReset]: {
    screen: mapNavigationStateParamsToProps(ForgotPasswordReset),
    path: "https://:uri/auth/reset"
  },
  [ROUTE_CONSTANTS.LoginStart]: {
    screen: mapNavigationStateParamsToProps(Login),
    path: "https://:uri/auth/:activationState"
  },
```

> In my app I "forced" the deeplinking to wait 1000ms before doing anything, so that I am sure that the app finished loading properly before anything.

> Another approach would be to modify your dynamic initialRoute in order to "recognize" that the app has been opened by deep linking and to not do anything in that scenario.

Package takes care of this internally from what I see in `createNavigationContainer`.Can you please share how did you achieve this in your app?

> Again, I don't see how this is a bug in the library.

With dynamic initial route it shows random behaviour but works with static initial route so I think there might be something going wrong here.

**Comment by kelset** [comment]
Ohh ok you are using it via [the lib](https://reactnavigation.org/docs/guides/linking). In my app I use the standard RN [Linking](https://facebook.github.io/react-native/docs/linking.html) and do something like

```js
componentDidMount() {
  Linking.getInitialURL().then((url) => {
    if (url) {
      // here I navigate based on the url via standard NavigationActions
    }
  }).catch(err => console.error('An error occurred', err));
}
```

That aside:
> With dynamic initial route it shows random behaviour but works with static initial route so I think there might be something going wrong here. Might be a race condition might be bug

I think you should change the name of that screen that you call `initialRoute` because I think you are confusing defining the routes of a navigator with passing [an option that decides the initial route](https://reactnavigation.org/docs/navigators/stack#StackNavigatorConfig).

And, again, I don't think it's a bug because:
1. it's the `componentWillMount` of `BaseRedirector` that does a `replaceRoute` "too late"
1. the navigators are not expecting to have the routes dynamically changing

**Comment by jinxac** [comment]
@kelset thanks a lot for your help. Race condition seems to be the case. I changed _handleOpenUrl in createNavigationContainer to dispatch the action after a delay and it works fine.

```
    _handleOpenURL = ({ url }: { url: string }) => {
      const parsedUrl = this._urlToPathAndParams(url);
      if (parsedUrl) {
        const { path, params } = parsedUrl;
        const action = Component.router.getActionForPathAndParams(path, params);
        if (action) {
          setTimeout(() => {
            this.dispatch(action)
          }, 500);
        }
      }
    };


```

>  In my app I use the standard RN Linking and do something like

If i need to avoid using library functions and use the standard RN linking is their any configuration i need to avoid?

**Comment by kelset** [comment]
Uhm nothing in particular that I can think of. Glad you managed to solve your issue 👌

**Comment by tbua** [comment]
I use static initialroute (I think?-- you can see below) But I'm getting the same problem:
1. close the app
2. click on the deep-linked url
3. the url navigate into the app
4. the app opens and navigate to screen 'ChangePassword'
5. "something else" navigates from ChangePassword to screen Splash

What's weird is that when I console.log out what's happening, it seems like the app actually visited Splash screen first and was sending some api request to backend. And THEN the URL listener gets triggered and the page will finally load to ChangePassword screen, but due to some error sent by splash api, errors will show. 

What I want is for the splash not to be called at all so no unwanted api calls will be made. I just want the link to directly navigate to ChangePassword page without any glitch. When I test deep linking while the app is open in the background, it works fine, but I really cant figure out why it's not working when the app is closed.

This is my route structure, with the initialRouteName set to splash:

```
const AppNavigator: NavigationContainer = StackNavigator(
    {
        ChangePassword: { screen: ChangePasswordScreen },
        Splash: { screen: SplashScreen },
        Login: { screen: LoginScreen },
         .....
    },
    {
        initialRouteName: appConstants.routeName.splash,
        navigationOptions: { header: null, gesturesEnabled: false },
        transitionConfig: TransitionConfiguration
    }
);
```

This is how I handle listening to url-- [here](https://github.com/react-navigation/react-navigation/issues/1189#issuecomment-339268524) is the tutorial I was following. I put it in App.js. The line 'LISTENING TO DEEPLINKING' gets triggered AFTER the splash saga's initialize action prints 'IN SPLASH SCREEN'.

```
class App extends React.Component {
  componentDidMount() {
    console.log('LISTENING TO DEEPLINKING');
    Linking.addEventListener('url', event => { 
      this.handleOpenURL(event.url) 
    });
    Linking.getInitialURL().then(url => url && this.handleOpenURL(url));
  }

  componentWillUnmount() {
    Linking.removeEventListener('url', this.handleOpenURL);
  }

  handleOpenURL(url) {
    const path = url.split(':/')[1];
    LinkRoutes(path);
  }
....
```

Link Routes is just a function I was following from this post for react native with redux. It looks something like this:
```
import Path from 'path-parser';
import {NavigationActions} from 'react-navigation';
import store from './store/configureStore';

const paths = [
  {
    routeName: 'ChangePassword',
    path: new Path('/changepassword/:token'),
  },
];

const findPath = url => paths.find(path => path.path.test(url));

export default url => {
  const pathObject = findPath(url);
  if (!pathObject) return;

  const navigateAction = NavigationActions.navigate({
    routeName: pathObject.routeName,
    params: pathObject.path.test(url),
  });
  store.dispatch(navigateAction);
};
```

Any help is appreciated. Thanks

**Comment by tbua** [comment]
i workaround the issue by putting the calls from componentDidMount and componentWillUnmount into splash screen instead.
