### ISSUE TITLE
Is it possible to change swipeEnabled of TabNavigator dymanically?

### ISSUE THREAD

**Issue by lichenglu** [react-community/react-navigation#3145]
I have a `tabNavigator` with two screens in it. However, I was not able to find any suggestion on how to change the `swipeEnabled` of this tavNavigator during runtime?

I tried things like this in one of the screens
```
static navigationOptions = ({ navigation }) => {
        const { params }  = navigation.state
        return {
            header: null,
            swipeEnabled: params && params.swipeEnabled
        };
    };

then set swipeEnabled in some of the event callbacks through setParams
```
This did not work, and I guess it is expected, as I am not changing the props of `tabNavigator` but a screen within it.

However, is there a way that I could change `swipeEnabled` dynamically? I need to do this as the swipe behavior is in conflict with another swipe behavior of items in a listview, which could result in unwanted tab change.

Thanks in advance!

**Comment by kelset** [comment]
Hi @(user)! It looks like this is not a bug of the library nor a feature request, so I'll close it: I suggest next time you use [Stack Overflow](https://stackoverflow.com/search?q=react-navigation) which is better suited for answering these types of questions. I also encourage you to join the [Reactiflux](https://www.reactiflux.com/) community on Discord. There are React Native and React Navigation channels with helpful people who might be able to answer your question. I would also like to mention that there is a collection of helpful links and tutorials for React Navigation in the [README](https://github.com/react-community/react-navigation#community-contributions) which might be helpful for you.

That said, no, I don't think you can change it dynamically. You would need to unmount and remount that tab navigator.

If you believe that you are experiencing a bug or have a feature request, please open a new Issue following the dedicated template or submit a PR.

**Comment by koenpunt** [comment]
Well I guess the feature request here could be; "how to dynamically change navigator config", which I think is really relevant. 

For example; we have a data driven app, where the number of columns in a _nested_ `TabNavigator` is defined remotely, and when this number is below 3, we want to disable swiping between them (this because the tabs itself are fixed, and when there are less than 3 tabs, even if there's no tab visible, a user could still swipe to the "nonexisting" tab). Currently we have it implemented by maintaining a copy of the `TabNavigator`, and doing some magic with screen props.

But having an official API for this would be much appreciated. Or if you can think of a way how to do this without maintaining a copy of the navigator?

**Comment by YouvaIBRAHIM** [comment]
try this
`
import { useNavigation } from '@react-navigation/native';
const navigation = useNavigation(); 

navigation.getParent().setOptions({swipeEnabled : false})
`
