### ISSUE TITLE
Switch to learna?

### ISSUE THREAD

**Issue by ericvicenti** [react-community/react-navigation#321]
It may make sense to switch to Lerna so that our packages can be more decoupled. For example, on web we incidentally pull in a bunch of react native stuff. As `react-navigation` gets used in more environments, people may prefer to swap out pieces, and I think we should make that easy.

What do people think about the idea? Will the overhead of maintaining many modules be reasonable? How hard will it be to set up?

**Comment by satya164** [comment]
I think a big problem will be that RN packager doesn't support symlinks. So unless we customize it heavily, we won't be able to switch to lerna.  Also it might be difficult to if we want to test it locally in other apps other than the example app.

Recently at callstack we needed to use a new unpublished commit in jest and were unable to install it from GIT because it uses lerna. I think this will be a problem too, unless there's a solution I'm not aware of.

**Comment by sibelius** [comment]
this could be helpful - https://react-native.canny.io/feature-requests/p/symlink-support-for-packager

**Comment by satya164** [comment]
@sibelius with watchman not having support for symlinks and no plans for supporting them, it'll be impossible to have proper support

**Comment by ericvicenti** [comment]
I hear there may be some people working on an alternative to RN packager that supports symlinks :-D

https://github.com/callstack-io/haul

Maybe we can try it out on this repo?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
