### ISSUE TITLE
Module Requires 'RCTLinking' in React Native Project

### ISSUE THREAD

**Issue by apandhi** [react-community/react-navigation#336]
I ran into an issue when integrating react-navigation with an existing iOS project. Turns out RCTLinking is needed in the Podspec. 

I just wanted to document this here for anyone else searching. I'll submit a PR for documentation on this soon.

**Comment by grabbou** [comment]
> I'll submit a PR for documentation on this soon.

Nice one, thanks!

**Comment by kelset** [comment]
Pinging OP @apandhi since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @apandhi ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.
