### ISSUE TITLE
how to display view on top of navigation header

### ISSUE THREAD

**Issue by sluramod** [react-community/react-navigation#363]
Hello,

For some reason I cannot display overlay on top of navigation header. Even when I use large zIndex value, it still shows under. My use case -I need to display in-app notification. 

Thank you.

**Comment by satya164** [comment]
Are using Android or iOS?

**Comment by sluramod** [comment]
iOS

**Comment by sluramod** [comment]
?

**Comment by grabbou** [comment]
In order to overlay the header, you have to render not inside the `scene`, but outside, in the parent, that renders your navigator.

```
render() {
  return (
     <View>
         <Navigator />
         {this.state.hasNotification && <DisplayNotification />}
     </View>
  );
}
```
So, basically, in the component that renders navigator, render another component that will display in-app notification. To trigger it, you can use e.g. redux & dispatch action `showNotification`.

**Comment by sluramod** [comment]
@grabbou that's what I did, but it's inconvenient since I need to do this for all types of overlays that I may have in the app. I would say this is a design issue that should be addressed.

**Comment by satya164** [comment]
Use a portal. Closing this issue because it's not specific to react navigation

**Comment by sluramod** [comment]
@satya164 I disagree, it's very specific to react navigation.

**Comment by designorant** [comment]
Since the title of this issue is about views, not in-app notifications specifically, I'd like to point out that the proposed solution is indeed fine for notifications, but the problem remains for anything else unless someone can think of a nested navigators scenario that works for the following example:

Let's say we've got a set of screens in a StackNavigator, one of which with a 'drag and drop' or 'swipe up/bottom' elements that need to cover the header when moved. How would we tackle that?

**Comment by satya164** [comment]
> Let's say we've got a set of screens in a StackNavigator, one of which with 'drag and drop' or 'swipe up/bottom' elements that need to cover the header when moved. How would we tackle that?

You'd have a parent navigator which shows these items and wraps your normal stack navigator. It's not different from how you'd use drawer navigator to draw on top of the header.

**Comment by godness84** [comment]
Tip: in some cases it's necessary to set `zIndex `and `elevation` > 4 to the view that should cover the header.

**Comment by AlexMouton** [comment]
@grabbou 
Hi Mike
Slight aside but: Should your example from February still work? 
I am trying to do as you suggest with a StackNavigation, but the navigation disappears when I put it inside a view?
Thanks
AM

**Comment by sigidhanafi** [comment]
Hi,
I solve this problem using Modal on React Native. Modal will cover all screen.

**Comment by ewalti** [comment]
What if I want to break an element out of it's current view hierarchy using `position: absolute` and/or `zIndex: {someBigNumber}`? Doesn't seem possible since the `<Header>` is lower in the view hierarchy than the scene `<Card>`.

**Comment by stantoncbradley** [comment]
We want to show toast/banners that come down from the top. we can (and were) using redux to solve this. However it is a hassle and couples together parts of our that otherwise would be decoupled. I prefer to keep redux as sparse as possible, and I don't want my root component responsible for our different banners just to work around react-navigation.  Modal doesn't work because we still want the user to be able to interact with the rest of the screen. Would love to see support for this, thanks!
