### ISSUE TITLE
Can't disable the drawer sliding out when a child of StackNavigator

### ISSUE THREAD

**Issue by AleskiWeb** [react-community/react-navigation#3946]
### Current Behavior

- What code are you running and what is happening?

I have added `gesturesEnabled: false` to pretty much every screen item and stack and when I swipe from the left of the screen the drawer still opens.

In parent navigator
```
export const AppStackNavigation = StackNavigator ({
    Drawer: {
        screen: DrawerStackNavigation,
        navigationOptions: () => ({
            gesturesEnabled: false
        })
    }
},
{
    initialRouteName: 'Drawer',
    navigationOptions: ({ navigation }) => ({
        headerLeft: <Text onPress={() => navigation.navigate('DrawerToggle')}>Menu</Text>,
        title: 'Survey Application',
        gesturesEnabled: false
    })
})
```

In `DrawerNavigator`

```
export const DrawerStackNavigation = DrawerNavigator ({
    Feed: {
        screen: Feed,
        navigationOptions: () => ({
            drawerLabel: 'My Feed',
            gesturesEnabled: false
        })
    },
{
    initialRouteName: 'Feed',
    navigationOptions: () => ({
        gesturesEnabled: false
    })
})
```

### Expected Behavior

- What do you expect should be happening?

I would have assumed the draw would stop opening when I swipe now.

### How to reproduce

Create an application navigation stack that is a `StackNavigator` containing a `DrawerNavigator` (to have the persistant title above the drawer) and then try to disable the drawer sliding out using gestures.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |1.5.10
| react-native     |0.52.0
| node             |8.9.4
| npm or yarn      |(yarn) 1.5.1

**Comment by shubham1164** [comment]
I am facing the same issue. @AleskiWeb have you solved it?

**Comment by brentvatne** [comment]
@shubham1164 

hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
