### ISSUE TITLE
Move addNavigationHelpers functions to an action creators file

### ISSUE THREAD

**Issue by mrpatiwi** [react-community/react-navigation#40]
When using with Redux we have to manually create the objects to dispatch:

```js
dispatch({ type: 'Navigate', routeName: 'Home' });
```

This make us dependent on the `type` string value key.

I took a look the source code and found that [`addNavigationHelpers.js`](https://github.com/react-community/react-navigation/blob/master/src/addNavigationHelpers.js) have the so called _Action creators_.

It might me helpful to move those functions to a separate file and include them on `addNavigationHelpers.js` but also expose them to be imported on custom reducers.

```js
export const navigate = (routeName, params, action) => ({
  type: 'Navigate',
  routeName,
  params,
  action,
});

// ...
```

Posible usage on custom reducers:
```js
import * as actions from 'react-navigation/actions';

function reducer(state = initialState, action) {
  switch (action.type) {
    case LOGIN_SUCCESS:
      return AppNavigator.router.getStateForAction(actions.navigate('Home'), state); 
   default:
      return AppNavigator.router.getStateForAction(action, state);
  }
}
```

**Comment by satya164** [comment]
Sounds like a good idea. cc @ericvicenti

**Comment by ericvicenti** [comment]
I agree this makes sense for redux users. PR would be accepted!

**Comment by jcarbo** [comment]
Definitely agree. Manually creating the action (e.g. `dispatch({ type: 'Navigate', routeName: 'Home' });` is error prone and brittle.

On a related note:
- the current redux action types are super general (`Navigate`, `SetParams`, `Reset`, `Back`). They should probably be prefixed to avoid collisions. For reference, `react-router-redux` prefixes their actions with `@@router/` (see https://github.com/reactjs/react-router-redux/blob/master/src/reducer.js)
- (I think) best practice for redux is to have one place where you export your action types and then use them as constants instead of by string. It seems like this repo is only referencing them by string (e.g. https://github.com/react-community/react-navigation/blob/0c9903556242f7d9b59df88180d395774b707701/src/routers/StackRouter.js#L202).

Thoughts? It would be a breaking change for people manually using string types in their codebase but I think this is something you'd want to nip in the bud.
