### ISSUE TITLE
Ability to center Android header when only left/right header button present

### ISSUE THREAD

**Issue by dmhood** [react-community/react-navigation#445]
Due to one of the recent changes in how the header is rendered, I'm not sure how to go about centering the header title on Android if you have only a left/right header button.

![image](https://cloud.githubusercontent.com/assets/2395637/23240860/9adc8e76-f924-11e6-8f07-437438ff9573.png)

Having a right/left button pushes it left/right.  I can't flex it since it's wrapped in the animated view, and alignSelf: 'center' only centers it inside the view, not the outer animated view itself.

This used to work fine before, so maybe there is another option/setting I'm just not seeing.  Is there a way to do this without having to set a specific margin depending on if a left/right button is present?

**Comment by grabbou** [comment]
That sounds like a valid request. I am not an Android developer, so cannot confirm whether this falls under being a `native` feature and should be implemented in default header or not.

> This used to work fine before

I don't think it used to work in the initial release, see this code: https://github.com/react-community/react-navigation/blob/c37ad8a0a924d13f3897bc72fbda52aac76904b6/src/views/Header.js#L115-L120 in original diff - whenever left/right was missing, the title was pushed to the other direction.

Here's screenshot with `textAlign: center` right after titleStyle was supported:
<img width="384" alt="screen shot 2017-02-23 at 07 52 12" src="https://cloud.githubusercontent.com/assets/2464966/23247942/20934b2c-f99d-11e6-9543-636499df3e39.png">

**Comment by dmhood** [comment]
Hmm maybe there was another change further down the line?  I have it working on my fork (up to the back button label change) https://github.com/sportsaction/react-navigation with the following style:

```javascript
titleStyle: {
      textAlign: 'center'
}
```

![image](https://cloud.githubusercontent.com/assets/2395637/23248342/bea9a5f8-f953-11e6-9f72-462d231ddb65.png)

**Comment by grabbou** [comment]
Actually, that was never meant to work that way. [This commit](https://github.com/react-community/react-navigation/pull/254) removed `style` which made the `style.left/style.right` no-longer take effect. It was shortly after fixed in another pull request (the one you refer to).

The intermediate state caused a couple of glitches and one of the side effects was making `center` to work. It is worth noting that it was never supported officially.

Let me label that as a `feature request` and I'll see what we can do in order to support it the best way.

**Comment by dmhood** [comment]
Sounds good, thanks!
