### ISSUE TITLE
Using two parallel navigators using Redux does not trigger RESET action

### ISSUE THREAD

**Issue by luisfcofv** [react-community/react-navigation#452]
I have this navigation setup:

- App
  - **TabNavigator**
    - StackNavigator
    - StackNavigator
  - Full screen modal
    - **StackNavigator**

** Please note TabNavigator and modal StackNavigator are not nested.

Here is my AppWithNavigationState:

```javascript
const Stack1Navigator = StackNavigator({
  screen: Screen1
});

const Stack2Navigator = StackNavigator({
  screen: Screen2,
});

const AppNavigator = TabNavigator({
  screen: Stack1Navigator,
  screen: Stack2Navigator,
});

@connect(state => ({
  appNavigator: state. appNavigator,
}))
class AppWithNavigationState extends React.Component {
  render() {
    return (
      <AppNavigator navigation={addNavigationHelpers({
        dispatch: this.props.dispatch,
        state: this.props.appNavigator,
      })} />
    );
  }
}
```

ModalWithNavigationState:

```javascript
const ModalNavigator = StackNavigator({
  screen: ModalScreen1,
  screen: ModalScreen2,
  screen: ModalScreen3,
});

@connect(state => ({
  modalNavigator: state.modalNavigator,
}))
class ModalWithNavigationState extends React.Component {
  render() {
    return (
      <AppNavigator navigation={addNavigationHelpers({
        dispatch: this.props.dispatch,
        state: this.props.modalNavigator,
      })} />
    );
  }
}
```

Combine reducers:
```javascript
export default combineReducers({
  appNavigator: (state, action) => (
    AppNavigator.router.getStateForAction(action, state)
  ),
  modalNavigator: (state, action) => (
    ModalNavigator.router.getStateForAction(action, state)
  ),
});
```

App:
```javascript
import { View, Modal } from 'react-native';

function App() {
  return (
    <View style={styles.container}>
      <AppWithNavigationState />
      <Modal visible>
        <ModalWithNavigationState />
      </Modal>
    </View>
  );
};
```

I'm trying to reset the stack in the Modal navigator by doing this in 'ModalScreen1'

```javascript
import { NavigationActions } from 'react-navigation'

const resetAction = NavigationActions.reset({
  index: 0,
  actions: [
    NavigationActions.navigate({ routeName: 'ModalScreen3'})
  ]
})

this.props.navigation.dispatch(resetAction)
```

My expected outcome would be:

```javascript
// AppNavigator: [Screen1, ...]
// ModalNavigator: [ModalScreen1]

// I'm in ModalScreen1
resetAction(..., routeName: 'ModalScreen3')

// AppNavigator: [Screen1, ...]
// ModalNavigator: [ModalScreen3]
```
However, I'm getting this error:
`There is no route defined for key ModalScreen3. Must be one of: 'Screen1', 'Screen2'`
Those routes are defined in AppNavigator, not ModalNavigator.

Ok..., then I tried to reset it to 'Screen1', and I got this error now:
`There is no route defined for key Screen1. Must be one of: 'ModalScreen1', 'ModalScreen2', ModalScreen3`
What??

Is it possible to have two parallel navigators?
Am I correctly setting it up with redux?

Thanks in advance

**Comment by luisfcofv** [comment]
There is a similar issue #395.
However, the issue is with parallel **nested** routes.

**Comment by matthamil** [comment]
Hi there! This issue is being closed because it has been inactive for a while. We're closing issues after a period of inactivity. Please do not take this personally :)
If you think this issue should remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:
* Does the issue still reproduce on the latest release? Post a comment with the version you tested.
* If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/react-community/react-navigation/blob/master/.github/ISSUE_TEMPLATE.md).
* Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.
If you would like to work on a patch to fix the issue, contributions are very welcome! Read through the [contributors guide](https://github.com/react-community/react-navigation/blob/master/docs/guides/Contributors.md), and feel free to hop into [#react-navigation](https://reactiflux.com) if you need help planning your contribution.

**Comment by nonameolsson** [comment]
I am also facing this issue, but I can't find a solution.
