### ISSUE TITLE
Screen loads twice when using TabNavigator

### ISSUE THREAD

**Issue by coreyt808** [react-community/react-navigation#476]
When using the TabNavigator the initial screen is loaded twice for some reason.  This can be seen by adding an Alert or console.log in componentDidMount.  I've replicated this in the SimpleTabs and StacksInTabs example.  The SimpleStack example doesn't load twice.

`const MyNavScreen = ({ navigation, banner }) => {
  Alert.alert(banner);
  return (
  <ScrollView style={styles.container}>
.......
  </ScrollView>
);
}`

**Comment by arthurpark** [comment]
Try setting `initialRouteName` in TabNavigatorConfig. It fixed the issue for me.

**Comment by coreyt808** [comment]
`initialRouteName` doesn't do anything for me.  

I can confirm that this doesn't happen in the beta 5 release though.  Will stick with beta 5 until this is fixed.

**Comment by makirby** [comment]
Also having the same problem & `initialRouteName` has had no effect stopping it.  Any idea what is causing it?

**Comment by makirby** [comment]
Seems its introduced in the update to react-native-tabs in #366. I downgraded the lib to 0.0.55 and now it no longer mounts the component twice on initial load.

**Comment by ivpusic** [comment]
I have the same issue

**Comment by grabbou** [comment]
cc: @satya164

**Comment by RedgooseDev** [comment]
same issue...

<img width="529" alt="screen 2017-03-03 am 7 17 45" src="https://cloud.githubusercontent.com/assets/1978100/23529608/8ec0e682-ffe1-11e6-9128-d8665011aafa.png">

**Comment by f0rr0** [comment]
Same issue. Using beta-6

**Comment by grabbou** [comment]
Can any of you past the stack trace here? I'll try to fix it for the beta-7 for today's release.

**Comment by f0rr0** [comment]
@grabbou there is no error thrown anywhere

**Comment by despreston** [comment]
+1 for getting this into the beta 7 release !!

**Comment by grabbou** [comment]
We will try :)

**Comment by arnsa** [comment]
Uhm, downgrading react-native-tabs to 0.0.55 fixed the problem to me.

**Comment by dondragon2** [comment]
@arnsa how do I downgrade the react-native-tabs? I am using `"react-navigation": "1.0.0-beta.5",`

**Comment by mostr** [comment]
Looks like it's already reported here https://github.com/react-native-community/react-native-tab-view/issues/160

**Comment by martsie** [comment]
Same issue for me, making it difficult to attach listeners to my components ...
Here's my tab navigator, each tab is another StackNavigator. If I put a breakpoint into component did mount of either of the screens then it fires twice despite only being shown to the user once.

```javascript
const Parks = StackNavigator({
  Home: { screen: ParksScreen, },
  Landmarks: { screen: LandmarksScreen },
}, {
    headerMode: 'screen',
    initialRouteName: 'Home',
    navigationOptions: {
      ...stackNavOptions,
      tabBar: {
        label: 'Parks',
        icon: ({ tintColor, focused }) => (
          <Image
            source={focused ? require('./src/images/ios/alphabet-filled.png') : require('./src/images/ios/alphabet.png')}
            style={[styles.icon, { tintColor: tintColor }]}
          />
        ),
      },
    },
  });


const Closest = StackNavigator({
  Closest: { screen: ClosestScreen },
}, {
    headerMode: 'screen',
    navigationOptions: {
      ...stackNavOptions,
      tabBar: {
        label: 'Map',
        icon: ({ tintColor, focused }) => (
          <Image
            source={focused ? require('./src/images/ios/map-filled.png') : require('./src/images/ios/map.png')}
            style={[styles.icon, { tintColor: tintColor }]}
          />
        ),
      }
    },
  })
const TabNav = TabNavigator({
  Home: {
    screen: Closest,
  },
  Parks: {
    screen: Parks,
  },
}, {
    tabBarOptions: {
      initialRouteName: 'Home',
      activeTintColor: '#fff',
      inactiveTintColor: '#bbb',
      style: {
        backgroundColor: colors.blue,
      },
      titleStyle: {
        color: 'white',
      }
    },
  })
```

**Comment by martsie** [comment]
Also stacktraces:

1st component mount
```
componentDidMount (ClosestScreen.js:62)
(anonymous) (ReactCompositeComponent.js:353)
measureLifeCyclePerf (ReactCompositeComponent.js:85)
(anonymous) (ReactCompositeComponent.js:352)
notifyAll (CallbackQueue.js:73)
close (ReactNativeReco…nsaction.js:36)
closeAll (Transaction.js:222)
perform (Transaction.js:163)
batchedMountComponentIntoNode (ReactNativeMount.js:77)
perform (Transaction.js:149)
batchedUpdates (ReactDefaultBat…Strategy.js:65)
batchedUpdates (ReactUpdates.js:111)
renderComponent (ReactNativeMount.js:141)
render (ReactNative.js:31)
renderApplication (renderApplication.js:33)
run (AppRegistry.js:76)
runApplication (AppRegistry.js:105)
__callFunction (MessageQueue.js:242)
(anonymous) (MessageQueue.js:108)
guard (MessageQueue.js:46)
callFunctionReturnFlushedQueue (MessageQueue.js:107)
(anonymous) (debuggerWorker.js:71)
```

Second component mount
```
componentDidMount (ClosestScreen.js:62)
(anonymous) (ReactCompositeComponent.js:353)
measureLifeCyclePerf (ReactCompositeComponent.js:85)
(anonymous) (ReactCompositeComponent.js:352)
notifyAll (CallbackQueue.js:73)
close (ReactNativeReco…nsaction.js:36)
closeAll (Transaction.js:222)
perform (Transaction.js:163)
perform (Transaction.js:149)
perform (ReactUpdates.js:95)
flushBatchedUpdates (ReactUpdates.js:199)
closeAll (Transaction.js:222)
perform (Transaction.js:163)
batchedUpdates (ReactDefaultBat…Strategy.js:65)
batchedUpdates (ReactUpdates.js:111)
_receiveRootNodeIDEvent (ReactNativeEventEmitter.js:126)
receiveEvent (ReactNativeEventEmitter.js:149)
__callFunction (MessageQueue.js:242)
(anonymous) (MessageQueue.js:108)
guard (MessageQueue.js:46)
callFunctionReturnFlushedQueue (MessageQueue.js:107)
(anonymous) (debuggerWorker.js:71)
```

In case that helps...

**Comment by duongtranpyco** [comment]
This issue still happened, please update to `"react-native-tab-view": "^0.0.55"`

**Comment by udfalkso** [comment]
I'm currently running into this issue with 1.0.0-beta.9

**Comment by NachtRitter** [comment]
I solved this problem with setting `lazy: true` for TabNavigator

**Comment by udfalkso** [comment]
Thanks @NachtRitter but that isn't solving it for me.

**Comment by chrismcleod** [comment]
same as @udfalkso 1.0.0-beta.11

**Comment by udfalkso** [comment]
Interesting @chrismcleod .  I'm also using redux.  This is how I'm generating my initial state. 

```
var action = TabNav.router.getActionForPathAndParams("InitialTabView")
const initialState = TabNav.router.getStateForAction(action)
```

**Comment by chrismcleod** [comment]
yea i created my first state in a similar way, but this initialState is actually coming from a rehydrate from redux-persist

**Comment by baldurpan** [comment]
+1

**Comment by lucadegasperi** [comment]
Same issue here. the first tab is always mounted twice, using lazy solves the problem only for the tabs that are not visible.

**Comment by Adamnator92** [comment]
+1, `lazy: true` didnt solve the render twice issue

**Comment by udfalkso** [comment]
@skevy Perhaps this issue should be reopened?

**Comment by satya164** [comment]
Please post full code or repro the issue on https://snack.expo.io

**Comment by timtawan** [comment]
Having same issues. Very slow on android!!

**Comment by bgribben** [comment]
I'm able to reproduce this issue but only when navigating away from the initial screen on componentDidMount. See https://github.com/PiggyPot/react-navigation-cdm-issue for an example. 

Can anyone reproduce this issue without the navigation element? Or can anyone suggest a better solution than those mentioned in my example?

**Comment by schettino** [comment]
Hello,

I kind of figured out what's happening here.

Apparently, there's nothing to do with the TabNavigator. Instead, it's a unwanted behavior with the StackNavigator. When we navigate to a stacked screen, it mounts a new component, even if it had mounted other before that. It's like no caching mounted components, neither unmouting them.

I have a set up with a TabNavigator within the StackNavigator. A login screen is attached to the StackNavigator. So, every time I redirect the user to the Login screen and he dismiss it (making him to go back to the TabNavigation), not only the components within the TabNavigation are mounted again, but also a new Login screen is mounted when the user go there again.

I will show in a simple manner that behavior. This is the way that helped me to really understand.

1) A component within the TabNavigator
![image](https://user-images.githubusercontent.com/7825467/27839626-fa8d1212-60c8-11e7-89b1-12948cf30a9f.png)

The hadleAction func check if the user is logged in. If it isn't, the user is redirect to the Login screen (StackNavigator). If he dismiss, he comes back to the TabNavigator (to a different tab from the one that requires login).

2) So the app starts up, we go to the tab navigation, then to the protected screen, that redirect us to the login screen.
![image](https://user-images.githubusercontent.com/7825467/27839791-81d573e4-60ca-11e7-9b63-f58499a87b50.png)

3) We dismiss it, and keep comming back, and eventually we end with something like that
![image](https://user-images.githubusercontent.com/7825467/27839841-e3152712-60ca-11e7-8f49-3027861de291.png)

---

So, my 2-step solution to prevent these behaviors is (using redux):

1)  Every time I wanted to go back to a tabbed screen from a stacked screen, I call a JUMP_TO_TAB action that changes the root index to 0 (which is my Tab Component), and then change it's index to the tab I want. This is a very rudimentar way just to illustrate:
```javascript
export const navReducer = (state, action) => {
  if (action.type === JUMP_TO_TAB) {
    const routes = [...state.routes];
    routes[0].index = action.payload.index; // 
    return { ...state, routes, index: 0 };
  }

  const newState = getStateForAction(action, state);
  return newState || state;
}
```

And then we made it:
![image](https://user-images.githubusercontent.com/7825467/27840339-6e356cc8-60ce-11e7-8643-53b7e8a8c939.png)

Well, kind of. Notice that a new login component is mounted every time we navigate to it. I suspect that it is happing because the getStateForAction function is not getting the cached component, but issuing a new one every time we need it. Or maybe I just configured something wrong, I don't know, but I apologize if it's the case.

Look, the Login component has been created over and over again, and pushed to the routes array.
![image](https://user-images.githubusercontent.com/7825467/27840428-3f838f1c-60cf-11e7-97b8-c0c14e024d5d.png)

One more time:
![image](https://user-images.githubusercontent.com/7825467/27840459-79d890cc-60cf-11e7-9651-157b322f66e2.png)

This leads us to the final step.

2) A small check to verify if the route was already issued. 
```javascript
if (state && action.routeName) {
  const index = state.routes.findIndex((route) => route.routeName === action.routeName);
  if (index > -1) {
    return { ...state, index };
  }
}
```
Then, when we navigate to Login,
![image](https://user-images.githubusercontent.com/7825467/27840521-0b99f942-60d0-11e7-858e-41cbef110afa.png)

It use the component already mounted.
![image](https://user-images.githubusercontent.com/7825467/27840545-3cb993c0-60d0-11e7-915b-44d5ea624815.png)

**Comment by fabriziomoscon** [comment]
I am seeing this issue as well with react-native.
All components representing the first screen of a tab are mounted twice.
I have updated `react-navigation` to the latest commit in master: https://github.com/react-community/react-navigation/commit/9037dd3c4eb608e2a4ca2fbe67fa833585f1d569
I am using RN `0.45.1`
and redux: `3.6.0`

My `Navigator`:

```JavaScript
import {
    StackNavigator,
    TabNavigator,
} from 'react-navigation'

const StackA = StackNavigator({
    ScreenA: {
        screen:            ScreenB,
        navigationOptions: {
            header: null,
        },
    },
    ScreenB:  {screen: SearchNumberViewContainer},
}, {
    initialRouteName: 'ScreenA',
    navigationOptions: {
        tabBarLabel: 'A',
    },
})

const StackB = StackNavigator({
    ScreenC: {
        screen:            ScreenC,
        navigationOptions: {
            header: null,
        },
    },
}, {
    initialRouteName: 'ScreenC',
    navigationOptions: {
        tabBarLabel: 'B',
    },
})


// TabNavigator is nested inside StackNavigator
const Tabs = TabNavigator({
    A: {screen: StackA},
    B: {screen: StackB},
}, {
    ...TabNavigator.Presets.AndroidTopTabs,
    tabBarPosition:   'top',
    animationEnabled: true,
    swipeEnabled:     true,
    backBehavior:     'initialRoute',
    lazy:             false,
})


const OnboardingStack = StackNavigator({
    Onboarding: {screen: OnboardingViewContainer},
}, {
    headerMode: 'none',
})

const AppNavigator = StackNavigator({
    Home:       {screen: Tabs},
    Onboarding: {screen: OnboardingStack},
}, {
    headerMode: 'none',
})

export default AppNavigator
```

I am nesting `TabNavigator` inside a `StackNavigator`.

**Comment by elfmatian** [comment]
redux+StackNavigator  
1.0.0-beta.11,
code:
router.getStateForAction(NavigationActions.navigate({routeName: 'LoadBasicData'}), state)

problem: LoadBasicData View componentWillMount function will excute twice. i can't resolve 

but i use 1.0.0-beta.9   very ok,

**Comment by AlmogRnD** [comment]
+1, has this been fixed

**Comment by luisfuertes** [comment]
I have this problem with Drawer

Versions:
``` 
		"react": "16.0.0-alpha.12",
		"react-native": "0.46.0",
		"react-navigation": "^1.0.0-beta.11",
```

AppNavigator.js config:
``` 
export const HomeNavigator = StackNavigator(
  {
    Home: { screen: Home },
    Film: { screen: Film },
  },
  {
    initialRouteName: 'Home',
  }
)


export const RegisterNavigator =  StackNavigator(
  {
    Register: { screen: Register },
  },
  {
    initialRouteName: 'Register',
  }
)


export const AppNavigator = DrawerNavigator({
  Home: {
    screen: HomeNavigator,
    navigationOptions: {
      drawerLabel: multiStrings.homeLabel,
      drawerIcon: ({ tintColor }) => (
        <Image source={require('quickets_app/src/resources/home.png')} style={{height: 16, width: 16, tintColor: tintColor}}/>
      ),
    }
  },

  Register: {
    screen: RegisterNavigator,
    navigationOptions: {
      drawerLabel: multiStrings.registerLabel,
      drawerIcon: ({ tintColor }) => (
        <Image source={require('quickets_app/src/resources/register.png')} style={{height: 18, width: 14, tintColor: tintColor}}/>
      ),
    }
  },

  Login: {
    screen: Login,
    navigationOptions: {
      drawerLabel: multiStrings.loginLabel,
  		drawerIcon: ({ tintColor }) => (
  			<Image source={require('quickets_app/src/resources/login.png')} style={{height: 16, width: 18, tintColor: tintColor}}/>
  		),
    }
  },
},
{
  initialRouteName: 'Home',
  contentComponent: (props) => <Drawer drawerProps={props} />,
  contentOptions: {
    activeTintColor: Colors.pink,
    style: {

    },
    labelStyle: {

    },
    activeBackgroundColor: 'transparent',
    inactiveTintColor: Colors.gray_3,
  }
});

const AppWithNavigationState = ({ dispatch, nav }) => (
  <AppNavigator navigation={addNavigationHelpers({ dispatch, state: nav })} />
)

AppWithNavigationState.propTypes = {
  dispatch: PropTypes.func.isRequired,
  nav: PropTypes.object.isRequired,
}

const mapStateToProps = state => ({
  nav: state.nav,
})

export default connect(mapStateToProps)(AppWithNavigationState)
``` 

Reducer: 
```
const firstAction = AppNavigator.router.getActionForPathAndParams('Home');
const initialNavState = AppNavigator.router.getStateForAction(firstAction)

export default function nav(state = initialNavState, action) {
  let nextState;
  switch (action.type) {

    case 'LOGIN':
      nextState = AppNavigator.router.getStateForAction(
        NavigationActions.navigate({ routeName: 'Home' }),
        state
      );
      break;

    case 'NOP':
      nextState = AppNavigator.router.getStateForAction(
        NavigationActions.navigate({ routeName: 'Login' }),
        state
      );
      break;

    default:
      nextState = AppNavigator.router.getStateForAction(action, state);
      break;
  }

  // Simply return the original `state` if `nextState` is null or undefined.
  return nextState || state;
}
```

Is for this line in reducer? `const initialNavState = AppNavigator.router.getStateForAction(firstAction)`? 

My componentWillMount Home function is called 3 times.

**Comment by bbrcan** [comment]
@skevy Can we get this issue reopened please?

It still seems like a number of people are experiencing it

**Comment by SteffeyDev** [comment]
I have this issue using a simple TabNavigator, whatever component I put under initialRouteName ends up being mounted 9 times before settling down (I checked this by putting a counter in componentDidMount).  Of course this causes a ton "Warning: Can only update a mounted or mounting component" errors, because callbacks are being triggered during re-mounts.  Makes the library practically unusable for me.

**Comment by dekm** [comment]
@luisfuertes thanks 

using const initialNavState = AppNavigator.router.getStateForAction({}) removed two of the calls for me.

For some reason I was getting 4 before.  Now though I'm stuck with 2.

**Comment by btroia** [comment]
@luisfuertes @dekm +1 I am also still experiencing the same issue with my navigator being called twice (can confirm this via console.log in my nav reducer), even after changing to:

` initialNavState = AppNavigator.router.getStateForAction({})`

in my nav reducer. Any updates?

**Comment by ImAtome** [comment]
+1 , I'm facing the same issue. But for me my navigator is being called 13 times ...

**Comment by SteffeyDev** [comment]
@ImAtome Are you calling StackNavigator({}, {}) or TabNavigator({}, {}) in the render() method?

**Comment by ImAtome** [comment]
@SteffeyDev I only render the RootNav StackNavigator which is in charge to display or not the others screens, right ? 
Here is basically what I'm doing: 

App.js
```javascript
import RootAppWithNavigationState from './navigators/RootAppNavigator'

class App extends Component {
  constructor(props) {
    super(props)
  }

  componentDidMount() {
    console.warn('App Mounted')
  }

  render () {

    return (
      <View style={ {flex: 1} }>
        <RootAppWithNavigationState />
      </View>
    )
  }
}

export default App
```

RootAppNavigator.js (RootNav)
```javascript
export const RootAppNavigator = StackNavigator(
  {
    AuthenticationScreens: { screen: AuthenticationScreens },
    AuthenticatedScreens: { screen: AuthenticatedScreens }
  },
  {
    initialRouteName:'AuthenticationScreens',
    navigationOptions: {
      gesturesEnabled: false
    },
    headerMode: 'none',
    cardStyle: { backgroundColor: 'white'}
  }
)

const RootAppWithNavigationState = ({ dispatch, nav }) => (
  <RootAppNavigator navigation={ addNavigationHelpers({ dispatch, state: nav }) } />
)

const mapStateToProps = state => ({
  nav: state.rootNav,
})

export default connect(mapStateToProps)(RootAppWithNavigationState)
```

AuthenticationScreens.js
```javascript
export const AuthenticationAppNavigator = StackNavigator(
  {
    SignInScreen: { screen: SignInScreen },
    SignUpStep1Screen: { screen: SignUpStep1Screen }
  },
  {
    initialRouteName: 'SignInScreen',
    headerMode: 'none',
    cardStyle: { backgroundColor: 'white'}
  }
)

const AuthenticationAppWithNavigationState = ({ dispatch, nav }) => (
   <AuthenticationAppNavigator navigation={ addNavigationHelpers({ dispatch, state: nav }) } />
)

const mapStateToProps = state => ({
  nav: state.authenticationNav,
})

export default connect(mapStateToProps)(AuthenticationAppWithNavigationState)
```

AuthenticatedScreens.js

```javascript
export const AuthenticatedAppNavigator = TabNavigator(
  {
    MarketScreen: { screen: MarketScreen },
    HomeScreen: { screen: HomeScreen },
    SettingsScreen: { screen: SettingsScreen }
  },
  {
    initialRouteName:'HomeScreen',
    tabBarOptions: {
      style: {
        backgroundColor:'white',
      },

      showLabel: false
    }
  }
)

const AuthenticatedAppWithNavigationState = ({ dispatch, nav }) => (
  <AuthenticatedAppNavigator navigation={ addNavigationHelpers({ dispatch, state: nav }) } />
)

const mapStateToProps = state => ({
  nav: state.authenticatedNav,
})

export default connect(mapStateToProps)(AuthenticatedAppWithNavigationState)
```

**Comment by SteffeyDev** [comment]
@ImAtome Yea that looks OK, I was having an issue where it was rendering 9 times that I fixed, but it looks like yours is something different.

**Comment by ImAtome** [comment]
@SteffeyDev Thank's anyway, I will try to figure it out why it's happening

**Comment by neetocode** [comment]
+1
I have a TabNavigator nested a StackNavigator. The TabNavigator is mounted twice

**Comment by vagnerSl** [comment]
+1

**Comment by ccoeder** [comment]
+1

**Comment by aevpraid** [comment]
I have a StackNavigator nested a DrawerNavigator. The DrawerNavigator is mounted three time

**Comment by rubancar** [comment]
I was facing the same problem, I just found a simple solution, in my case **MyApp** is an **StackNavigator** which includes a **TabNavigator** and **StackNavigator**, the problem came up  when I wanted to navigate from the **Home screen in Main** to **Results screen in Purchase**, so Results screen was double mounted, I solved this when I set **Results** as the name for my screen **Purchase in MyApp**, as you can see it's the same name of the **initialRouteName**  in **Purchase**, so It appears that you have to use the same name of the initialRouteName on a StackNavigator as the name of the screen in another StackNavigator, I leave an example code that right now It's working for me.

`const PurchaseStack = StackNavigator({
    Results: { screen: Results },
    Seats: { screen: Seats }
}, {
    initialRouteName: 'Results',
    headerMode: 'none'
});

const Main = TabNavigator({
    Home: { screen: Home },
    Tickets: { screen: Tickets },
    Login: { screen: Auth }
}, {
    initialRouteName: 'Home'
});

export default MyApp = StackNavigator({
    Main: { screen: Main },
    Results: { screen: PurchaseStack }
}, {
    initialRouteName: 'Main',
})
`

**Comment by pencilcheck** [comment]
Having the same issue for stacknavigator that loads the first screen twice, and you can see that the same screen get flashed twice. I don't know how to solve this, even the most simpliest example from the playground also produce the same results here somehow.

Using 
```
react-navigation@^1.0.0-beta.13:
  version "1.0.0-beta.13"
  resolved "https://registry.yarnpkg.com/react-navigation/-/react-navigation-1.0.0-beta.13.tgz#77521f7080e5755906a3483a28baedbbc66f763c"
  dependencies:
    babel-plugin-transform-define "^1.3.0"
    clamp "^1.0.1"
    hoist-non-react-statics "^2.2.0"
    path-to-regexp "^1.7.0"
    prop-types "^15.5.10"
    react-native-drawer-layout-polyfill "^1.3.2"
    react-native-tab-view "^0.0.69"
```

**Comment by NunoCardoso** [comment]
+1

**Comment by EsdrasEtrenne** [comment]
Solved this by naming everything down the tree by the same name as per @rubancar 's post:
```

  const MainNavigator = TabNavigator({
        welcome: {screen: WelcomeScreen},
        auth: {
          screen: StackNavigator({
            login: { screen: LoginScreen },
            register: { screen: RegisterScreen },
            forgotPassword: {screen: ForgotPasswordScreen},
            eula: {screen: EULAScreen},
          })
        },
        contacts:{
          screen: TabNavigator({
            contacts:{
              navigationOptions:{
                tabBarVisible: false
              },
              screen: TabNavigator({
                contacts: {
                  screen: StackNavigator({
                    contacts: { screen: ContactsScreen },
                    viewProfile: {
                      screen: ViewProfileScreen,
                      navigationOptions: ({ navigation }) => ({
                        tabBarVisible: false,
                        headerBackTitle: null
                      })
                    },
......more code
```

for me my first main screen is my contacts screen so I just renamed every branch down the tree contacts. Not the best thing as far as naming principles is concerned but it works and its a simple fix.

**Comment by Kottidev** [comment]
This issue still exist with last version 1.0.0-beta.19 when using Redux and TabNavigator.

componentWillMount is called twice

@grabbou

**Comment by ruinnel** [comment]
still existing version `1.0.0-beta.21`

in my case.
`TabNavigator` has 4 tab and each tab has `StackNavigator`..

I solved this problem using custom router.

in `router.getStateForAction` receive two action..
1. `{ type: 'Navigation/INIT' }`
2.  `Navigation/Navigate` for move to your `initialRouteName` in TabNavigator.

skip second action like this.
```
const defaultGetStateForAction = Nav.router.getStateForAction;

Nav.router.getStateForAction = (action, state) => {
  if (action && action.type === 'Navigation/NAVIGATE'
  && action.routeName === 'reserve'
  && action.action && action.action.routeName === 'main') {
    const index = _.get(state, 'routes.[0].index');
    const routeName = _.get(state, 'routes.[0].routes[0].routeName');
    if (index === 0 && routeName === 'main') {
      return state;
    }
  }

  return defaultGetStateForAction(action, state);
};
```
please change 
- `Nav` to your StackNavigator
- `routeName === 'main'` to `routeName === 'StackRouter's initialRouteName'` 

I am sorry that English is awkward.....

**Comment by EthanChouTW** [comment]
@luisfuertes 's fixs works for me, thanks

change from
```
const firstAction = AppNavigator.router.getActionForPathAndParams('Home');
const initialNavState = AppNavigator.router.getStateForAction(firstAction)
```
to 
```
 const initialNavState = AppNavigator.router.getStateForAction({})
```

and
add `initialRouteName ` in `navigatorConfig`

could prevent multiple mount calls for me

**Comment by mlazari** [comment]
@satya164 Here is a repro: https://snack.expo.io/By-qnQZ7f

**Comment by zygama** [comment]
I have the same problem in beta-22 ...

**Comment by thalesfp** [comment]
@rubancar solution works for me.

**Comment by mlazari** [comment]
**Repro code:** https://snack.expo.io/BJLIk4-Qz

**Navigation structure:**
```
MyTabNavigator
--MyStackNavigator
----MyScreen1
```

**Problem:** MyScreen1 loads twice

**Possible cause:**
MyScreen1 is loading first time when MyTabNavigator's router is sending Navigation/INIT to MyStackNavigator router's getStateForAction here:
[TabRouter](https://github.com/react-navigation/react-navigation/blob/master/src/routers/TabRouter.js#L66) -> [StackRouter](https://github.com/react-navigation/react-navigation/blob/master/src/routers/StackRouter.js#L146)
Second time it's loading when MyTabNavigator's router is sending Navigation/NAVIGATE to MyStackNavigator router's getStateForAction here:
[TabRouter](https://github.com/react-navigation/react-navigation/blob/master/src/routers/TabRouter.js#L104) -> [StackRouter](https://github.com/react-navigation/react-navigation/blob/master/src/routers/StackRouter.js#L198)

**Possible solutions:**
`const initialAction = MyTabNavigator.router.getActionForPathAndParams('MyStackNavigator');`
The value of initialAction is:
```
{
  type: "Navigation/NAVIGATE",
  routeName: "MyStackNavigator",
  action: {
    type: "Navigation/NAVIGATE",
    routeName: "MyScreen1"
  }
}
```
`const initialState = MyTabNavigator.router.getStateForAction(initialAction);`
The value of initialState is:
```
{
  index: 0,
  routes: [
    {
      index: 1,
      key: "MyStackNavigator",
      routeName: "MyStackNavigator",
      routes: [
        {
          key: "Init-id-1515587457094-0",
          routeName: "MyScreen1"
        },
        {
          key: "id-1515587457094-1",
          params: undefined,
          routeName: "MyScreen1"
        }
      ]
    }
  ]
}
```
I think the inner action (Navigate to MyScreen1) is adding the screen for the second time in stack. initialAction should be probably just:
```
{
  type: "Navigation/NAVIGATE",
  routeName: "MyStackNavigator"
}
```
because I'm asking MyTabNavigator's router which action do I need to go to MyStackNavigator, not to MyScreen1.
The inner action is added here: [TabRouter](https://github.com/react-navigation/react-navigation/blob/master/src/routers/TabRouter.js#L310) -> [StackRouter](https://github.com/react-navigation/react-navigation/blob/master/src/routers/StackRouter.js#L342)
It should probably not add the subaction when the remaining part of the path is empty. I've made a commit here which does that: https://github.com/mlazari/react-navigation/commit/29f0c1d17133706c38408ebf7b7fe7109072c9cd Maybe someone from contributors can review it?

Other solution for given code would be to just use NavigationActions.navigate instead of MyTabNavigator.router.getActionForPathAndParams:
`const initialAction = NavigationActions.navigate({routeName: 'MyStackNavigator'});`

Or just `const initialAction = {};` as someone already suggested.

**Comment by Donhv** [comment]
who can help me fix this issue?

**Comment by pulkitsharma99** [comment]
I can anytime

**Comment by udfalkso** [comment]
@mlazari is def. right.  Using a sort of "empty" action for your initial state can stop this issue from happening.  This seems like the cleanest way to do it.  

```
import { NavigationActions } from "react-navigation"

let initialState = MainTabs.router.getStateForAction(NavigationActions.init())
```

Should the redux docs be updated to reflect this?

**Comment by SKempin** [comment]
Just upgraded to `1.1.2` and am getting this with the Stack and Tabs navigators. Should this be fixed by now?

**Comment by danZheng1993** [comment]
I have upgraded the react native to 1.2.1 and the issue was fixed.
It works like magic now.
Fantastic work by the team.

**Comment by SKempin** [comment]
`1.2.1` has solved this issue for me too.

**Comment by brentvatne** [comment]
yay thanks

**Comment by brentvatne** [comment]
given that this is resolved i will lock the issue. if you run into any other bugs please create a new issue. thanks!
