### ISSUE TITLE
Docs: Contribution Guide / Submitting / New views -> Incomplete

### ISSUE THREAD

**Issue by ElliottJRo** [react-community/react-navigation#49]
> ### New views or unique features
> Often navigation needs are specific to certain apps. If your changes are unique to your app, you may want to fork the view or router that has changed. You can keep the source code in your app, or publish it on npm as a react-navigation compatible view or router.
This library is intended to include highly standard and generic navigation patterns. **But it**

It looks like the New views section is incomplete and just ends at the noted bolded section

**Comment by ericvicenti** [comment]
Whoops! This is meant to encourage people to publish their own view libraries that can use navigation state and integrate seamlessly. The same can be done with routers, so that custom routers can contain React Nav routers, or be contained by them.

I think that the most generic views should live in the core library, but everything else can be published as independent modules.

It would be awesome if you or anybody else could revise this section to reflect this.

**Comment by ElliottJRo** [comment]
I will need help with this revision as I am just getting into navigation states.

**Comment by ElliottJRo** [comment]
fixed ish in #280
