### ISSUE TITLE
custom function on header right button

### ISSUE THREAD

**Issue by tweeklabs-isaac** [react-community/react-navigation#495]
sample code

static navigationOptions = {

        title: "My App",
        header: ({state, setParams}) => {

            let right = (
                <Button
                    title="Click to Alert"
                    onPress={this.foo}
                />
            );

            return {right};
        },
    };

    foo() {
        alert('bar')
    }

I want to fire off function foo from my right header button. I don't get the alert when I click it and if i use `onPress={this.foo()}` i get an undefined error

**Comment by grabbou** [comment]
You will find your answer in #145. 

Besides that, your error is a standard Javascript error. `foo` method is simply not accessible via `this.foo()` and shouldn't be, as it's not even a class.

**Comment by skyaimt** [comment]
this.foo is not recognised since it will search for its own class methods which is react-navigation in this case. Therefore to overcome this issue , you need to take a global variable say 'take' to be defined outside the class and then to assign value 'this' to the global variable 'take' inside the render() function.
then call the foo() function via onPress={take.foo()}
this works for me..
go for it :+1:

**Comment by samkerm** [comment]
Thanks @skyaimt you solution worked for me.

**Comment by BSThisarasinghe** [comment]
@skyaimt Your answer worked for me. Thanks a lot

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/header-buttons.html
