### ISSUE TITLE
How to disable the left-to-right transition animation during initial app launch?

### ISSUE THREAD

**Issue by wenbinf** [react-community/react-navigation#50]
I use **TabNavigator** and here's the full code:

```js
class HomeScreen extends React.Component {
    render() {
        return <View style={{flexDirection:'row', backgroundColor: 'red', height: 300,
            justifyContent:'flex-end', paddingTop: 30}}>
            <Text>Hello, Navigation!</Text>
        </View>
    }
}

class SecondScreen extends React.Component {
    render() {
        return <View style={{flexDirection:'row', justifyContent:'flex-end', paddingTop: 30}}>
            <Text>Hello, Second!</Text>
        </View>
    }
}

const AppContainer = TabNavigator({
        HomePage: {screen: HomeScreen},
        SecondPage: {screen: SecondScreen}
    }
)
```

As you can see, when app initially launches, the text "flies" in ... How can I disable this effect?

![jan-27-2017 14-00-02](https://cloud.githubusercontent.com/assets/1719237/22389122/ee2f5ed2-e498-11e6-8208-fa6f68ce3bbe.gif)

Thanks in advance!

**Comment by satya164** [comment]
I think you need to set `flex: 1` on your view.

**Comment by wenbinf** [comment]
Thanks @satya164 , but now it becomes this:

![jan-27-2017 14-08-16](https://cloud.githubusercontent.com/assets/1719237/22389404/20c5c326-e49a-11e6-88d8-d648c710fcf4.gif)

I added "flex: 1"
```
class HomeScreen extends React.Component {
    render() {
        return <View style={{flex: 1, flexDirection:'row', backgroundColor: 'red', height: 300,
            justifyContent:'flex-end', paddingTop: 30}}>
            <Text>Hello, Navigation!</Text>
        </View>
    }
}
```

**Comment by satya164** [comment]
So seems it only happens when you've `flexDirection: row`. For example, the following works fine,

```js
class HomeScreen extends React.Component {
  render() {
    return (
      <View>
        <View
          style={{
            flexDirection: 'row',
            backgroundColor: 'red',
            height: 300,
            justifyContent: 'flex-end',
            paddingTop: 30,
          }}
        >
          <Text>Hello, Navigation!</Text>
        </View>
      </View>
    );
  }
}
```

**Comment by wenbinf** [comment]
hmm ... I ran your code snippet, but it still doesn't work.

The version that I'm using is  "react-navigation": "^1.0.0-beta.1".

Let me dig more ...

**Comment by satya164** [comment]
@wenbinf hmm. I just tested this on simulator and couldn't reproduce the issue anymore.

**Comment by wenbinf** [comment]
For the record, this was the environment that I tested

- node v7.2.1
- iOS Simulator: iPhone 6 + iOS 8.4 / iOS 10, iPhone 7 + iOS 10
- real iphone 6 + iOS 10
- "react-navigation": "^1.0.0-beta.1"
- "react-native": "0.40.0",

Just in case someone on the Internet encounters the same problem :)

**Comment by hilkeheremans** [comment]
This is still an issue on latest master as of this post. When testing, please also use `react-native-debugger` to make sure the embedded chrome debugger doesnt hide the issue.

To reproduce, use a `TabNavigator` as follows: 
```
export const TestTabAnim = TabNavigator({
        splash: {
            screen: () => (<View style={{ flex: 1, backgroundColor: 'red' }}><Text>Tab 1</Text></View>)
        },
        login: {
            screen: () => (<View style={{ flex: 1, backgroundColor: 'blue' }}><Text>Tab 1</Text></View>)
        },
        home: {
            screen: () => (<View style={{ flex: 1, backgroundColor: 'purple' }}><Text>Tab 1</Text></View>)
        }
    })
```

I have tracked down the root cause, and it lies within the `react-native-tab-view` dependency. More specifically, when an `AnimatedTabView` tries to mount initially, it has no knowledge of the actual dimensions it should render in, and thus has no idea of what to animate _to_. In order to circumvent this,  the `TabViewTransitioner` component in `react-native-tab-view` seems to use `onLayout` to immediately change the animation target to the actual width and height of the view (https://github.com/react-native-community/react-native-tab-view/blob/master/src/TabViewTransitioner.js#L110). This causes a `one frame delay in rendering`, which is also what you notice visually.

I tested this hypothesis by directly passing a hardcoded `initialLayout={{ height: <height>, width: <width> }}` prop to the `AnimatedTabView` from `TabView` in `react-native-navigation`. This resolves the issue. As you'd still need height and width before rendering, this isn't a very practical workaround.

@satya164 Seems like you are 'the man to talk to' re `react-native-tab-view` -- any further insights? Thanks!

**Comment by satya164** [comment]
> A not-so-practical workaround to avoid this animation issue would then be to somehow pass the tab navigator's width and height before mount

We don't need that. The one frame delay is only for things like indicator which absolutely need the width before rendering. Tab view knows how to handle the layout before measurement is done, so that there is no delay. There were some missing styles in the scrollview based pager that iOS uses, which prevented it from working properly. I just pushed an update with fixed styles.

**Comment by hilkeheremans** [comment]
Thanks!

**Comment by wenbinf** [comment]
@satya164 thanks for the fix! How can I pick up your latest change? npm update?
