### ISSUE TITLE
Selectable Text in TabNavigator on Android

### ISSUE THREAD

**Issue by allmaxgit** [react-community/react-navigation#560]
Selectable Text not working in TabNavigator on Android.
Even set `swipeEnabled: false`.

**Comment by satya164** [comment]
It definitely works for me without disabling swipe. Are you sure this occurs only when using TabNavigator? Do you have any code?

**Comment by allmaxgit** [comment]
Not work in: StackNavigator - TabNavigator - StackNavigator - TabNavigator - Screen - SelectableText
Not work in: StackNavigator - TabNavigator - StackNavigator - Screen - SelectableText
Not work in: StackNavigator - TabNavigator - Screen - SelectableText
Work in: StackNavigator - Screen - SelectableText

**Comment by satya164** [comment]
Please provide a repro. You can use https://sketch.expo.io

**Comment by matthamil** [comment]
Hi there! This issue is being closed because it has been inactive for a while. We're closing issues after a period of inactivity. Please do not take this personally :)
If you think this issue should remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:
* Does the issue still reproduce on the latest release? Post a comment with the version you tested.
* If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/react-community/react-navigation/blob/master/.github/ISSUE_TEMPLATE.md).
* Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.
If you would like to work on a patch to fix the issue, contributions are very welcome! Read through the [contributors guide](https://github.com/react-community/react-navigation/blob/master/docs/guides/Contributors.md), and feel free to hop into [#react-navigation](https://reactiflux.com) if you need help planning your contribution.
