### ISSUE TITLE
event emitted when navigating back in StackNavigator

### ISSUE THREAD

**Issue by JLLLinn** [react-community/react-navigation#575]
When navigating back into a previous screen, what event is being emitted on the previous screen so I can capture the back action ? I tried didmount, didfocus, didUpdate but none of these works.

Thanks in advance!

**Comment by ishsingh** [comment]
I have the same problem. Any solutions?

**Comment by smakazmidd** [comment]
I have a similar query. Want to know if there's any way for a screen to know that its about to get or lose focus ? 

A workaround could be to pass the current scene instance to the next one using params and then call a method on the instance in the next component's componentWillUnmount().

**Comment by satya164** [comment]
Check https://github.com/satya164/react-navigation-addons

**Comment by ishsingh** [comment]
@satya164 Thanks. The addons look great, will give them a try. Meanwhile, I got around this by simply emitting a custom event, and refreshing the previous screen in the custom event listener.

Is there a plan to move addons as part of the main repository at some point?

**Comment by grabbou** [comment]
Yes, see #54

**Comment by khkwan0** [comment]
Hello, I know I'm wayyyyy late to this thread, but I had a similar problem and found this thread (among others in my search).  Regardless, my solution was to take advantage of componentWillUnmount in the child screen.  Since goBack will also unmount the current 'screen', componentWillUnmount gets called.  I provided a method in the parent component and passed it into the child screen.  Then, on componentWillUnmount I call the method that was passed in, passing any parameters I need back to the parent screen.  It seemed to work and felt less hacky.  I hope this helps anyone else looking for this solution in the future.

**Comment by AleksandarSavic95** [comment]
Here is how to do it using **NavigationEvents**:
```
import { NavigationEvents } from 'react-navigation';
```
and then add this anywhere inside your `render` method:
```
<NavigationEvents onWillBlur={event => {
    // add your code here :)
    console.log('going back?', event.action.type === 'Navigation/BACK');
  }
} />```
