### ISSUE TITLE
Slow remove of icon on the top bar

### ISSUE THREAD

**Issue by EQuimper** [react-community/react-navigation#578]
Hey, this is an awesome library I loved it :).

I've added the StackNavigator with a TabNavigator to my app. I got some kind of weird stuff happening. I add an icon on the top right for send me to my create post screen. This one works perfectly etc. But if I change route with the tab and show a route who no supposed to have this icon on the right I got a slow icon remove action. I try to make it null and nothing change. I try also to add the other icon and this last one come on top of my old one. 

Do this is normal ? Do I need to change something in my component render ? 

This is a GIF I make with this error.

![](http://g.recordit.co/KSJFvV9sSa.gif)

This is my HomeScreen

```js
static navigationOptions = {
    header: ({ navigate }) => {
      const style = { backgroundColor: Colors.redColor };

      const right = (
        <View>
          <Button
            transparent
            onPress={() => navigate('AddMeetup')}
          >
            <Icon
              name="md-add-circle"
              style={{
                fontSize: 30,
                color: Colors.whiteColor
              }}
            />
          </Button>
        </View>
      );

      return { style, right };
    },
```

This is my ProfileScreen

```js
static navigationOptions = {
    header: {
      style: { backgroundColor: Colors.redColor }
    },
    tabBar: {
      icon: ({ tintColor }) => (
        <MaterialIcons
          name="account-circle"
          size={25}
          color={tintColor}
        />
      )
    }
  }
```

This is my HomeNavigator who is the tab navigator

```js
import { TabNavigator } from 'react-navigation';
import Colors from '../../constants/Colors';
import {
  HomeScreen,
  NotificationsScreen,
  ProfileScreen
} from '../screens';

export default TabNavigator({
  Home: {
    screen: HomeScreen
  },
  Notifications: {
    screen: NotificationsScreen
  },
  ProfileScreen: {
    screen: ProfileScreen
  }
}, {
  swipeEnabled: false,
  animationEnabled: true,
  tabBarPosition: 'bottom',
  tabBarOptions: {
    showLabel: false,
    showIcon: true,
    inactiveTintColor: Colors.blackBlueColor,
    activeTintColor: Colors.redColor,
    pressColor: Colors.redColor,
    indicatorStyle: { backgroundColor: Colors.redColor },
    style: {
      backgroundColor: Colors.whiteColor
    }
  }
});
```

My main Navigator

```js
import { StackNavigator } from 'react-navigation';
import { CreateMeetupScreen } from '../screens';
import HomeNavigator from './HomeNavigator';

export default StackNavigator({
  Home: { screen: HomeNavigator },
  AddMeetup: { screen: CreateMeetupScreen }
}, {
  mode: 'modal'
});
```

**Comment by matthamil** [comment]
Hi @EQuimper thank you for your question.

The reason why this is happening is because `animationEnabled: true` is set in your `TabNavigatorConfig`. When you change tabs, the animation starts, which animates the tab's `screen` from left to right (and vice versa). When the animation is "done," the header will swap to the next screen's header. I bet that if you set `animationEnabled: false`, your problem goes away. I think this is probably a bug with `react-native-tab-view` (a dependency of react-navigation https://github.com/react-native-community/react-native-tab-view).

This is not the intended behavior, so this is most likely a bug that should be investigated.

**Comment by michaelduminy** [comment]
I have this same issue where the title in the header only changes after a noticeable delay when switching tabs.

Interestingly this doesn't happen when navigating to a different tab from the containing DrawerNavigator despite the animation still happening. I suspect this is due to the nested nature of the navigators.

**Comment by markusguenther** [comment]
Yeah when you disable animationEnabled for the navigator thoses things do not happen. I have the same for a header that is only visible in one tab and the header is slide in very slowly when the animation is enabled.

It doesn`t look so smooth without the animation, but it is a fast workaround.

**Comment by grabbou** [comment]
I believe this is now gone in `master` since https://github.com/react-native-community/react-native-tab-view/releases/tag/v0.0.60 contains: 

> Tapping on tabs will now update the state first before starting the transition (earlier it updated the state after finishing the transition)

**Comment by grabbou** [comment]
I can confirm this is still happening.

**Comment by satya164** [comment]
> This is not the intended behaviors, so this is most likely a bug that should be investigated.

The behaviour changed in latest version, and tapping a tab first updates the state before starting the animation. But this was never a bug.

The reason it was this way is performance. When you update the state and things re-render, the animation can get laggy when it starts. This was especially noticeable because of the JS based animation used by default. Now that we use `ViewPagerAndroid`/`ScrollView`, the lag is less noticeable.

Performance reasons aside, a basic principle of the tab view is that when you are using animated tabs, you can have everything animated so that it feels natural. The library makes it easy to do that. Unfortunately, it's not possible with React Navigation's current set of APIs.

Now regardless when the state updates, showing/hiding things controlled by state feels abrupt when all other transitions are animated. Also it's not possible to update the state beforehand when swiping because we don't know what will be the next page until you lift your finger. And even if you lift the finger, you can still swipe again in quick succession. So it's impossible to actually know the next page until the animation completes.

It's simple to workaround for now, make the headers part of individual tab screens.

**Comment by agarciaguillo** [comment]
> It's simple to workaround for now, make the headers part of individual tab screens.

@satya164 How could it be solved in this case, to get eliminate the delay in the tapping tabs and in the finger transition? #1230

**Comment by satya164** [comment]
@agarciaguillo you can make the header part of individual tabs. i.e. stack inside tab rather than tab inside stack.

I think we eventually need to figure out a way to expose animations to the parent navigator. But it's a larger discussion.

**Comment by agarciaguillo** [comment]
@satya164 That way:

```javascript
const Tabs1 = StackNavigator({
	One: { screen: One, navigationOptions: { title: 'One', header: { title: 'First' } } },
	OneB: { screen: OneB, navigationOptions: { title: 'OneB' } }
});

const Tabs2 = StackNavigator({
	Two: { screen: Two, navigationOptions: { title: 'Two', header: { title: 'Second' } } },
	TwoB: { screen: TwoB, navigationOptions: { title: 'TwoB' } }
});

const Tabs3 = StackNavigator({
	Three: { screen: Three, navigationOptions: { title: 'Three', header: { title: 'Third' } } }
});

const Tabs4 = StackNavigator({
	Four: { screen: Four, navigationOptions: { title: 'Four', header: { title: 'Fourth' } } }
});

const RouterComponent = TabNavigator({
	Tabs1: { screen: Tabs1 },
	Tabs2: { screen: Tabs2 },
	Tabs3: { screen: Tabs3 },
	Tabs4: { screen: Tabs4 }
});
```
This happens:

![navigation2](https://cloud.githubusercontent.com/assets/16135348/25411101/16b10af0-2a1b-11e7-9deb-8cd360ac13e0.gif)


The Tab Bar is above off the header, and I want the header to be at the top. The reason of #1230 comes from #981

**Comment by satya164** [comment]
@agarciaguillo There's one way to achieve what you want, but it involves making your own header, you can do something like this:

```
tabBarComponent: (props) => (
   <View>
     <TabViewHeader {...props} />
     <TabBar {...props}
   </View>
)
```

The code for your header can be something like the following:

```
function TabViewHeader(props) {
  const {
    position,
    navigation,
  } = this.props;
  const { routes } = navigation.state;
  // Prepend '-1', so there are always at least 2 items in inputRange
  const inputRange = [-1, ...routes.map((x: *, i: number) => i)];
  return (
    <View style={styles.header}>
      {routes.map((route, index) => {
        const focused = index === navigation.state.index;
        const scene = { route, index, focused };
        const outputRange = inputRange.map(inputIndex =>
            inputIndex === index
              ? 1
              : 0,
        );
        const opacity = position.interpolate({
          inputRange,
          outputRange,
        });
        return (
          <Animated.Text style={[styles.title, { opacity }]}>
            {this.props.getLabel(scene)}
          </Animated.Text>
        );
      })}
    </View>
  );
}
```

This code is overly simplistic and I haven't tested it, but it should give you an idea.
