### ISSUE TITLE
Error navigating to a screen whose parent doesn't have a title

### ISSUE THREAD

**Issue by davideweaver** [react-community/react-navigation#616]
I have the following **StackNavigator**...

```
export default TopicsStack = StackNavigator({
  Items: { screen: ItemsScreen },
  ItemDetails: { screen: ItemDetailsScreen }
}
```

If ItemsScreen is defined like below (title is empty)...

```
export default class ItemsScreen extends Component {

  static navigationOptions = {
    title: ""
   }
  ...
}
```

When I navigate to **ItemDetails** I get the error:

```
RawText "" must be wrapped in an explicit <Text> component.
```

I'm guessing because my parent screen had an empty title. I can work around the problem by setting the parent title to " ".

**Comment by spencercarli** [comment]
[Confirmed reproduction](https://snack.expo.io/r1OzSC1db)

**Comment by leartgjoni** [comment]
@iMaddin white spaces are good only on ios, on android they add an extra padding under the tab icon

**Comment by kelset** [comment]
Is this bug still present in `beta.13`?
What happens if `title: null`?

**Comment by kelset** [comment]
Pinging OP @davideweaver since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @davideweaver 

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.
