### ISSUE TITLE
[Android] Keyboard isn't hidden when navigating to new screen

### ISSUE THREAD

**Issue by ng-hai** [react-community/react-navigation#655]
My app has two screens. The initial screen has one TextInput and one Button. When the Button pressed, it will dispatch a Redux action and navigate to the second display. If I edit TextInput's content, keep Keyboard open then press the Button, it navigates but does not hide the Keyboard. iOS not having this weird.

**Comment by sutani** [comment]
can i look your code @ng-hai ?

**Comment by ng-hai** [comment]
I have changed the Button into navigation header button, but kept the navigate method.

![image](https://cloud.githubusercontent.com/assets/19520278/24207509/a32278c6-0f53-11e7-998f-feca055abf9a.png)

**Comment by jdcc2** [comment]
+1

**Comment by MoOx** [comment]
I have a similar issue on android only: I have an autocomplete screen.
When I type some text (input at the top of my screen, below the header), a list is filled below. When I click on a result I just trigger a navigate() call that stack a screen. I noticed on Android that the keyboard is not only still open, but that if I type something on goes back (using header left button I setup), the autocomplete input have the thing I typed from the other screen.
That was because somewhere in my list of result of the autocomplete I am using `keyboardShouldPersistTaps="always"` (ScrollView). So I ended up using `Keyboard.dismiss()` in `componentDidMount()` of my last screen.

**Comment by helenoalves** [comment]
+1

**Comment by kelset** [comment]
Similar to #618 - it's related to how Android (natively) makes the keyboard behave. The easiest solution, anyway, would be the one suggested by @MoOx.

@ng-hai does it work for you? The issue is quite old and related to an old version of the library. If no answer I'll close in 7 days.

**Comment by jbownzino** [comment]
Thank you @MoOx - was having this same issue and your solution works well.

**Comment by egemon** [comment]
@ng-hai will there be any *solution* and not hack? So if I have 10 buttons with navigation to 10 different screens - I will have to add 3*10 lines to my code which will make exactly the same thing.
