### ISSUE TITLE
Two nested tab navigators give me a blank scene

### ISSUE THREAD

**Issue by ldipasquale** [react-community/react-navigation#662]
I have implemented two nested tab navigator, and when I run the app I see both navigators but a blank scene. If I scroll horizontal, I see the right scene.

I leave the code:

**App.js** (first tab-navigator)
```
const App = TabNavigator({
  Battles: {
    screen: Battles,
  },
  Tournaments: {
    screen: Tournaments,
  },
}, {
  tabBarPosition: 'bottom',
  tabBarComponent: TabBar,
  swipeEnabled: false,
  swipeEnabled: false,
  tabBarOptions: {
    showIcon: true,
    showLabel: false,
  },
});
```

**Battles.js** (second tab-navigator)
```
const Battles = TabNavigator({
  LastBattles: {
    screen: LastBattles,
  },
  PopularBattles: {
    screen: PopularBattles,
  },
  HistoricBattles: {
    screen: HistoricBattles,
  },
}, {
  tabBarOptions: {
    indicatorStyle: {
      backgroundColor: colors.white,
    },
    style: {
      backgroundColor: colors.orange,
    },
  },
});

Battles.navigationOptions = {
  tabBar: {
    label: 'Batallas',
    icon: (
      <Image source={require('../../assets/icons/battles.png')} />
    ),
  },
};
```

Here is a screenshot:
<img width="390" alt="captura de pantalla 2017-03-13 a las 12 01 30 a m" src="https://cloud.githubusercontent.com/assets/7157252/23840012/a3d2dfe8-0780-11e7-92ba-add4a9c7f144.png">

I've checked in the componentDidMount from Battles component and it's being executed.

Any ideas? Thank you!

**Comment by XboxYan** [comment]
@ldipasquale me too!

**Comment by ldipasquale** [comment]
@XboxYan Is it happening to you too?

**Comment by prengifo** [comment]
The same is happening to me!

**Comment by benjaminbaldoni** [comment]
Same issue here!

**Comment by prengifo** [comment]
Ok I fixed it! The workaround is to set `lazyLoad: false` in the TabNavigatorConfig of the parent. In your case @ldipasquale in App.js

**Comment by ldipasquale** [comment]
Cool @prengifo, but it doesn't make the app slower the `lasyLoad: false` setting?

**Comment by prengifo** [comment]
Sadly, yes. I also set `animationEnabled: false` to make it a little faster because lags without it. As I said it's a workaround, there should be another way to fix this 😞

**Comment by ldipasquale** [comment]
@satya164 any idea?

**Comment by satya164** [comment]
Might be because Android doesn't support nesting view pagers. We could switch to not using view pager behind the scenes if swipes and animations are not enabled.

No `lazyLoad` doesn't make your app's transition slower. It just loads all the screens upfront. It'll actually make tab transitions faster because it doesn't need to render anything when switching tabs.

Lagging issues shouldn't happen in production. It's bit slow in development.

Also can someone create a simple example on https://sketch.expo.io for testing?

**Comment by ldipasquale** [comment]
@prengifo:
I tried with `lazyLoad: false` and didn't work for me. Are you testing in iOS or Android?

@satya164:
But that is not the behavior of the `lazyLoad: true`?, or am I confusing?

Sure. Here is the link: https://sketch.expo.io/HkcBzidol

Let me thank you for the great work you do with this solution.

**Comment by prengifo** [comment]
@ldipasquale Android 7.0

**Comment by mostr** [comment]
Same here, upgraded to `^1.0.0-beta.7` and still seeing this. All is fine, logs show that components are getting rendered but nothing gets shown on screen. Only when tab any tab gets clicked corrects scene gets rendered.

**Comment by mostr** [comment]
Ok, had a deeper dive into the code and this is what I've found:

In `TabView.js` there is `TabViewPager` which is defined as follows:
```
let TabViewPager;
switch (Platform.OS) {
  case 'android':
    TabViewPager = TabViewPagerAndroid;
    break;
  case 'ios':
    TabViewPager = TabViewPagerScroll;
    break;
  default:
    TabViewPager = TabViewPagerPan;
}
```

Looks like when you change `android` branch to return `TabViewPagerScroll` (same as for iOS) it works fine. I know that this `TabViewPagerAndroid` uses `ViewPagerAndroid` from RN itself but wondering what are potential drawbacks in using same as for iOS? @satya164, any hints on this? 

Haven't checked yet what's wrong with `TabViewPagerAndroid` that it doesn't show initial scene though.

**Comment by satya164** [comment]
There are two reasons I'm not using `TabViewPagerScroll` on Android,

1. When you're swiping fast, it snaps to next page instead of an animation, which feels weird
2. ScrollView doesn't support specifying an initial scroll value on Android, which means if you specify a tab other than the first one, it will need to load the first tab, then scroll to the initial tab, which is not what you want

Unfortunately ViewPagerAndroid is buggy and ScrollView is not feature-complete on Android. Which makes it impossible to have a good pager on Android :(

Currently the only solution I can think of is, when you have animations disabled, we can swap out `ViewPagerAndroid` for a simpler pager which doesn't prevent you from nesting a scrollview inside.

**Comment by ldipasquale** [comment]
@satya164 sounds good for me!

**Comment by mostr** [comment]
@satya164 you mean replacing with one of these two remaining `TabViewPagerScroll` or `TabViewPagerPan`? Or introducing something completely new?

**Comment by ldipasquale** [comment]
Hi @satya164! Any update on this issue?

**Comment by michaelduminy** [comment]
To fix this I turned lazy loading on and animations off. 

It turns out that tapping the nested tab (the one that isn't showing content on initial load) makes the content appear. This might be doable programmatically.

**Comment by toninho** [comment]
@michaelduminy I've tried your approach, but it did not work for me.

**Comment by dnish** [comment]
In my case, it fixed the issue, but the navigations goes now slower. You have to set these settings within your parent navigator:

    swipeEnabled: false,
    lazyLoad: true,
    animationEnabled: false,

**Comment by michaelduminy** [comment]
Thanks @dnish, I should have specified my other options (sorry @toninho). I also disable swiping.

**Comment by ldipasquale** [comment]
Like @toninho, it dont't work for me. Any ideas @michaelduminy @dnish?

**Comment by allmaxgit** [comment]
Same issue.

**Comment by rawris** [comment]
I have the same issue I have react-native-material-bottom navigation and a react-navigation tabNavigator nested inside one of the tabs of react-native-material-bottom-navigation. none of the screens appear in react-navigation tabNavigator

**Comment by agentilela** [comment]
Same issue. Touching a scrollview inside the nested tabNavigator causes the content to render.

**Comment by kelset** [comment]
+1

**Comment by ericvicenti** [comment]
I cannot replicate this 'blank scene' issue. Can you try with the current code in master?

If you can replicate it, can you provide a PR that makes this bug visible in the navigation playground?

**Comment by onlydave** [comment]
https://github.com/onlydave/react-navigation/tree/nested

This is what I see after tapping "Nested Tabs Example and trying to swipe a little.
![Uploading Screen Shot 2017-04-25 at 19.55.43.png…]()

**Comment by satya164** [comment]
Just sent a PR https://github.com/react-community/react-navigation/pull/1234

As long as there's only one tab navigator with swipes and animations enabled, it will work fine.

**Comment by Noor0** [comment]
what if i need 2 tab navigators both with `swipeEnabled: false`?

**Comment by manuTro** [comment]
Hi! I need swipe and animation both enabled. What is the solution in this case?

**Comment by satya164** [comment]
There's no solution. You to disable swipe and animations on one of the navigators

**Comment by Palisand** [comment]
@satya164 I am having an issue where your fix only works if the **child** tab navigator's swipes and animations are disabled.

**Comment by yizhanzjz** [comment]
@dnish When I remove `lazyLoad: true,`,it's still working fine.

**Comment by andreyslyusar** [comment]
I report probably a duplicate of current issue #2160. I try to set
```
    swipeEnabled: false,
    animationEnabled: false,
```
but it does not change anything. As @onlydave mentioned changing TabViewPagerAndroid to TabViewPagerScroll in TabView.js fix an issue, but I do not know what kind of side effect it could have.

Any ideas of how we can fix this behaviour ?

**Comment by jamesalways** [comment]
Only works if you set  { swipeEnabled: false,  animationEnabled: false } in both. Please fix it! Thanks!

**Comment by sarahmarciano** [comment]
+1 same here please fix it ASAP, Thanks!

**Comment by jordanmkoncz** [comment]
I'm having a similar problem, although for me I'm not getting a blank scene, instead my tab bar just does not update to show the current tab when I switch to a different tab.

I have a tab bar that works perfectly fine on iOS, but on Android when I press on a tab to switch to it, the tab bar does not actually switch to the tab I pressed, it just does nothing. I know that the press itself is being registered (as a Navigation/NAVIGATE` action is dispatched in response) but the tab bar just doesn't update to show the new correct tab.

My navigation structure where this bug is occurring has a TabNavigator at the top level (lets call it `TabNavigatorParent`, with a StackNavigator as its child, and then a TabNavigator as the child of this StackNavigator (lets call this one `TabNavigatorChild`). `TabNavigatorParent` is using the `TabBarBottom` component, and it works perfectly fine on both iOS and Android. `TabNavigatorChild` is using the `TabBarTop` component, but even if I make it use `TabBarBottom` instead I still have the same problems.

The solution posted by @dnish of setting `swipeEnabled: false, animationEnabled: false` on `TabNavigatorChild` resolved the problem for me (setting `lazyLoad: true` was not necessary for me). This solution works regardless of what `swipeEnabled` and `animationEnabled` are set to in `TabNavigatorParent`.

Unfortunately this is not the ideal solution because I actually want `animationEnabled: true` on `TabNavigatorChild`, so hopefully a proper fix will be created.

Worth noting also that a completely different solution also resolved the problem for me, which is the `initialLayout` change described in https://github.com/react-native-community/react-native-tab-view/issues/312, specifically the change that you can see in this commit: https://github.com/Minishlink/react-navigation/commit/c326c9ba43e101d85b8e590ba9fba9ee0652d5c9. When I applied that change, my `TabNavigatorChild` worked correctly, even with `animationEnabled: true`.

**Comment by erwan-lcs** [comment]
Seems to be working fine now (iOS and Android) with just one `lazy `setting on the top TabNavigator:

```javascript
const MainTabNavigator = TabNavigator({
    welcome: { screen: WelcomeScreen },
    auth: { screen: AuthScreen },
    main: {
        screen: TabNavigator({
            map: { screen: MapScreen },
            deck: { screen: DeckScreen },
            review: {
                screen: StackNavigator({
                    review: { screen: ReviewScreen },
                    settings: { screen: SettingsScreen }
                })
            }
        })
    }
}, {
    lazy: true
});
```

**Comment by syukurzay** [comment]
export const  Tabs =
    TabNavigator({
        welcome: {
            screen : TabNavigator({
               News: {screen: Favorite},
               Populer: {screen: Populer}
            }),

        },
        auth: {
            screen: Match,

        },
    }, {

        tabBarPosition: 'bottom',
        lazy: true, // Each screen will not mount/load until user clicks on them
        animationEnabled: false,
        tabBarOptions: {
            activeTintColor:'white',
            activeBackgroundColor:'Darkgreen',
        },
    }
);

**Comment by Vijaysuryawanshi1993** [comment]
put
animationEnabled: false
swipeEnabled: false
lazyLoad: true
in your second tab

**Comment by pallavbakshi** [comment]
Is there any proper solution to this problem? I have tested the hacks and they work fine but they somewhat affect the performance. Has anyone found the right way?

**Comment by saravanakumargn** [comment]
Thanks @dnish. It's working if we add to parent tab.

```
swipeEnabled: false,
lazyLoad: true,
animationEnabled: false,
```

**Comment by biduone** [comment]
Thanks , My second tab is working by 
swipeEnabled: false,
animationEnabled: false


Version: 1.0.0-beta.21

**Comment by sharathkoppolu** [comment]
const AppNavigation = StackNavigator({
    TabTop: {
        screen: TabNavigator({
            TabBtm: {
                screen: TabNavigator({
                    TabT1: { screen: TabT1 },
                    TabT2: { screen: TabT2 },
                    TabT3: { screen: TabT3 }
                }, {
                    tabBarPosition: 'top',
                    swipeEnabled: true,
                    tabBarOptions: {
                      activeTintColor: '#e91e63',
                    },
                  })
            },
            Tab1: { screen: Tab1 },
            Tab2: { screen: Tab2 },
            Tab3: { screen: Tab3 },

            
        }, {
            tabBarPosition: 'bottom',
            swipeEnabled: false,
            tabBarOptions: {
              activeTintColor: '#e91e63',
            },
          })
    }
})

Swipe and tab click is working fine on ios but not working properly on Android. I think this is similar to what the discussion is about. can someone let me know where am I going wrong? did it work for anyone on android?

**Comment by houdangui** [comment]
I met same issue, disable the animation of parent tab navigator works for me!

**Comment by ntomallen** [comment]
Had the same issue - it seems like the only thing I had to do was to set both 
```
...
swipeEnabled: false,
animationEnabled: false,
...
```
in the child tab navigator. I still have animation and swiping for the parent. I'm not sure why I would want both to have swiping, since a swipe on the screen would have to swipe either the child or the parent or both...

**Comment by Donhv** [comment]
I want both parent and children swip 
who can help me?

**Comment by hasanal1995** [comment]
@dnish  thank you

**Comment by jovanxua** [comment]
@ntomallen Thank you. That worked!
...
swipeEnabled: false,
animationEnabled: false,
...

**Comment by abramsamir1** [comment]
re-setup react-navigation library again locally, it works for me.
**npm install --save react-navigation** at the cmd.

**Comment by vinayclecotech** [comment]
@abramsamir1 
Thanks for your suggestion .
re-setup react-navigation library again locally, it works for me.
**npm install --save react-navigation** its work
