### ISSUE TITLE
Is there a bulit in way to show a modal window that blocks the whole screen?

### ISSUE THREAD

**Issue by yaronlevi** [react-community/react-navigation#67]

**Comment by yaronlevi** [comment]
And also forgot to mention that React Navigation looks like an amazing works, and it is the missing piece we've been all waiting for (-:
(+ the website and docs are top notch)

**Comment by hilkeheremans** [comment]
The standard `Modal` in React Native works fine here.

**Comment by yaronlevi** [comment]
Ok, I also see that StackNavigatorConfig has a 'modal' mode. And it also states that android is currently not supported. Are there any plans on supporting it on android?

**Comment by hilkeheremans** [comment]
I have no idea on that, but you can simply use the standard React Native `Modal` in a screen as follows. Supported in both iOS and Android.

```

<Modal
    animationType="slide"
    visible={this.state.visible || somethingElse}
>
    <Text>Hello World</Text>
</Modal>
```

This should slide over other content in the component. I've done this inside a TabNavigation earlier today and it works just fine.

**Comment by ericvicenti** [comment]
I really wouldn't use RN's `<Modal>` component unless you are building a hybrid application and you need to grab the full screen. It works outside React Navigation's awareness of screen presentation, and is likely to result in strange bugs when working with this library.

@yaronlevi, What would this alternate modal style look like? We can either get one added to the library if it is a super standard component across several platforms- (please provide references!). Or we can add a way for you to customize the appearance of a standard modal stack.

**Comment by minhchu** [comment]
IMO there is an usecase using a screen modal would be better than RN's `<Modal>`. I have an app which has many screens. Each screen has many `<TextInput>` sending request to the API and getting responses. Everytime they get responses, I would like to show a popup in case the `<TextInput>` data is invalid and some error messages. Instead of rendering RN's `<Modal />` every screen, I'd love calling a modal screen.

this is an example about style: http://browniefed.com/blog/react-native-easy-overlay-modal-with-navigator/

**Comment by bd-arc** [comment]
@ericvicenti Are you aware of any particular reason why the same modal animation as the one used for iOS can't be exposed? Unless I'm mistaken, it seems that implementing a slide up/down animation on Android (triggered by setting `mode` to `modal`) would do the job.

As for the look and feel, [this demo](https://storage.googleapis.com/material-design/publish/material_v_10/assets/0B8v7jImPsDi-RWVHZjYybnlDeUE/components-buttons-fab-transition_fullscreen_02.webm) from Material design's official guidelines looks good to me :-)

**Comment by faceyspacey** [comment]
I think android support for the vertical modal animation makes a lot of sense for consistency between your app, regardless of what platform it's on. When you want to make something that feels more like a modal and breaks the horizontal flow of your stack navigator, you slide up, regardless of platform. 

Is there a technical reason behind why this isn't possible or is it about preserving what's typical on Android? I thought the underlying animation library abstracted this stuff so it's the same code on both platforms?? 

Also, who really follows all these style guides anyway? Most great apps are completely custom. For example, who makes apps for iOS that are white, gray and blue, besides Apple.

**Comment by faceyspacey** [comment]
I see that it likely is possible on Android:

https://github.com/react-community/react-navigation/blob/6b8cb793b426be36c1366f3e4157a9f208815dcd/src/views/TransitionConfigs.js#L63

So can't it just be at the user's discretion whether he uses `react-navigation` to create an iOS style modal on Android, rather than force everyone to have to go make a dialog just for Android.

**Comment by kelset** [comment]
Pinging OP @yaronlevi since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @yaronlevi,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.
