### ISSUE TITLE
zIndex of the DrawerNavigator

### ISSUE THREAD

**Issue by lwonsower** [react-community/react-navigation#673]
Is there a way to have an element, specifically a TouchableOpacity, to still be clickable when the drawer navigator is open? I'm trying to have a button that opens and closes my drawer navigator, but even though the drawer is not rendered on top of the button, it's not clickable when the drawer is open.
It seems like you cannot manipulate the zIndex of the drawer navigator. Any tips?

**Comment by jurassix** [comment]
I haven't had much luck with setting _zIndex_ or _elevation_. A simpler approach may be to just add a close to the Drawer itself.

Something like the following will work:

```js
DrawerNavigator(routes, {
  contentComponent: (props) => (
    <View>
      <TouchableOpacity onPress={() => props.navigation.navigate('DrawerClose')}>
        <Icon
          name="close"
          size={40}
          color="lightgrey"
        />
      </TouchableOpacity>
      <DrawerView.Items {...props} />
    </View>
  )
});
```

**Comment by tonyooi** [comment]
Hi @jurassix I am also facing similar issue. When there is a button on the screen, it just floats on top of the side drawer when side drawer is opened. Is there a way of setting the zIndex of the DrawerLayout so that the drawer is the top most component when it slides out. 

Thanks for your help.

**Comment by jurassix** [comment]
I believe you will need to create a custom version of the [DrawerNavigator](https://github.com/react-community/react-navigation/blob/master/src/navigators/DrawerNavigator.js) in order to inject _styles_ into it to affect the *zindex*.

You might have a cleaner solution to adjust the _zindex_ and _elevation_ on the *button* to be 0 or some low value.

A screen shot and a simple example and I could help more.

**Comment by tonyooi** [comment]
Hi @jurassix 

Screenshot as below:-
![screenshot_2017-04-06-10-47-22](https://cloud.githubusercontent.com/assets/13709079/24736382/578a1230-1aba-11e7-9804-acdd9e84a32d.jpg)
![screenshot_2017-04-06-10-47-30](https://cloud.githubusercontent.com/assets/13709079/24736383/58c2f5ae-1aba-11e7-9b55-8bc45aa217f2.jpg)

index.android.js
```
import React, { Component } from 'react';
import {
    AppRegistry,
    StyleSheet,
    Text,
    View,
    Button,
    StatusBar,
    TouchableOpacity,
    Icon
} from 'react-native';
import { DrawerNavigator } from "react-navigation";

class AboutMeScreen extends Component {
    static navigationOptions = {
        title : "About Me Screen",
        drawer : () => {
            label : "About Me"
        }
    }
    render(){
        let { navigator } = this.props.navigation;
        return (
            <View>
                <StatusBar />
                <Text>About Me Screen</Text>
            </View>
        );
    }
}

class HomeScreen extends Component {
    static navigationOptions = {
        title : "Home Screen",
        drawer : () => {
            label : "Home"
        }
    }
    render(){
        let { navigate } = this.props.navigation;
        return (
            <View>
                <Text>Home Screen</Text>
                <Button title="Go to About Me" onPress={ ()=> navigate("AboutMe") } style="{ { zIndex : 0 } }" />
            </View>
        );
    }
}

const routeOptions = {
    Home : { screen : HomeScreen },
    AboutMe : { screen : AboutMeScreen }
};

const drawerOptions = {
    drawerWidth : 280,
    drawerPosition : "left",
};

const sidenav = DrawerNavigator(routeOptions,drawerOptions);

AppRegistry.registerComponent('sidenav', () => sidenav);

```
Screenshot shows the button overlapping the side drawer when the side drawer is opened.
Thank you.

**Comment by jurassix** [comment]
@tonyooi I've built your component in iOS and the behavior is working fine, even without any styles added to the button.
![simulator screen shot apr 10 2017 9 25 16 pm](https://cloud.githubusercontent.com/assets/1869117/24888862/716c2d5a-1e34-11e7-87c0-9f8de3d79c42.png)

I do see an error with your code above. When you added styles to your button the syntax is incorrect.

Change:

> ```<Button title="Go to About Me" onPress={ ()=> navigate("AboutMe") } style="{ { zIndex : 0 } }" />```

To: (notice style is now an object)

```js
<Button title="Go to About Me" onPress={ ()=> navigate("AboutMe") } style={{ zIndex : 0 }} />
```

I'll check this out in Android and see if I can reproduce ur issue.

**Comment by jurassix** [comment]
@tonyooi I just verified that your code works on Android as well.

![screenshot_1491874966](https://cloud.githubusercontent.com/assets/1869117/24889211/bd51e87a-1e36-11e7-8af9-ebc40597dd92.png)


Here are my `package.json` dependencies. This could just be a version issue?

```js
  "dependencies": {
    "react": "~15.4.0",
    "react-native": "0.42.3",
    "react-navigation": "^1.0.0-beta.7"
  }
```

**Comment by tonyooi** [comment]
@jurassix Thank you so much.

My package.json file
```
{
  "name": "sidenav",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "15.4.2",
    "react-native": "0.42.3",
    "react-navigation": "^1.0.0-beta.7"
  },
  "devDependencies": {
    "babel-jest": "19.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "19.0.2",
    "react-test-renderer": "15.4.2"
  },
  "jest": {
    "preset": "react-native"
  }
}
```
Seeing that you got it working and looks like there isn't much difference in the packages, I tried again by reinstalling the node modules and now it works fine.

**Comment by matthamil** [comment]
Hi there! This issue is being closed because it has been inactive for a while. We're closing issues after a period of inactivity. Please do not take this personally :)
If you think this issue should remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:
* Does the issue still reproduce on the latest release? Post a comment with the version you tested.
* If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/react-community/react-navigation/blob/master/.github/ISSUE_TEMPLATE.md).
* Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.
If you would like to work on a patch to fix the issue, contributions are very welcome! Read through the [contributors guide](https://github.com/react-community/react-navigation/blob/master/docs/guides/Contributors.md), and feel free to hop into [#react-navigation](https://reactiflux.com) if you need help planning your contribution.
