### ISSUE TITLE
Question: Does it already run with React on Desktop/Browser Apps?

### ISSUE THREAD

**Issue by Steviey** [react-community/react-navigation#70]
Question: Does it already run with 'normal' React.js on desktop/browser apps, made with Meteor or Electron, based on Chromium, V8 etc.? Are there any info resources?

**Comment by ericvicenti** [comment]
When you say 'it', what do you refer to? In either case, the answer is 'sorta'.

If you're asking about the routers, yes they will work fine in an electron app, but there is no URL bar visible and no way to deep-link that I know of, so the path parsing features won't be needed.

Maybe you're curious about the navigation views like the tab bar or the stack and header? Those should ideally work out of the box with react-native-web, or would work on web if we migrated to `react-primitives` instead of using primitive components out of RN directly. This may not work super well yet, but it should be possible today with some hacks, and eventually will be hack free.

There are no resources for this yet, but I'd support you if you wanted to create some!

Closing for now because this is more of a question and we don't explicitly support electron apps yet.

**Comment by agungsb** [comment]
It's 2020 now and still no support for desktop 😞

**Comment by mkmakes** [comment]
The problem with electron desktop, is the packaged app is using the `file://` protocol that points to an internal filepath like `file:///Users/you/App.app/index.html`. This doesn't match anything and so will always default to your fallback not-found route.

I don't need the headers/stacks/etc on my electron application, so this comment won't speak on if this works 100%. But for simply taking paths and matching components, you can get electron routing working with `getStateFromPath`

For your typical app

```tsx
import { getStateFromPath as defaultGetStateFromPath, NavigationContainer } from '@react-navigation/native'

type GetStateFromPathOptions = Parameters<typeof defaultGetStateFromPath>[1]
const linking = {
  config: {
    screens: {
      Home: '',
      User: 'user/:userId',
      NotFound: {
        path: '*',
      },
    },
  },
  getStateFromPath(path: string, options: GetStateFromPathOptions) {
    /**
     * On initial load under file://, window.location.pathname is the filesystem path
     * e.g. "/Users/you/App.app/index.html" — which matches nothing and hits NotFound.
     * Stripping it makes React Navigation fall back to the root route.
     * Subsequent navigations use pushState with real paths so they pass through unchanged.
     */
    const cleanPath = path.includes('.html') ? '' : path
    return defaultGetStateFromPath(cleanPath, options)
  },
  prefixes: ['/'],
}

// ...
<NavigationContainer linking={linking}>
  //...
</NavigationContainer>
```

Hope this helps someone!
