### ISSUE TITLE
Screens dodge the keyboard on Android but not iOS

### ISSUE THREAD

**Issue by Talor-A** [react-community/react-navigation#721]
Hi, I have an app with a stacknavigator and I've got a footer-type component at the bottom of some of my screens, and on Android the footer moves up but on iOS it doesn't

**Comment by ericvicenti** [comment]
We can consider adding keyboard dodging capabilities to this library, but it is not something we currently manage

**Comment by Talor-A** [comment]
@ericvicenti sorry this isn't a feature request. it appears to be a bug that my footer fixed to the bottom of the screen moves with the keyboard on Android but not iOS. though maybe the problem is elsewhere if stackNavigator doesn't utilize a KeyboardAvoidingView.

**Comment by ericvicenti** [comment]
If you want to use a KeyboardAvoidingView for your screen, that would be a good idea. It is not something that react-navigation currently does for you, so that is why I think the feature request tag makes sense.

The difference between iOS and Android is due to the way your keyboard is configured in Android's manifest.xml.

That said, you may be right that there is inconsistency to solve. Can you post a the full code needed to reproduce this issue from a fresh create-react-native-app, and a screenshot of each platform?

**Comment by housseindjirdeh** [comment]
Experienced a similar issue with having a StackNavigator nested within a TabNavigator, and I only needed to set `keyboardVerticalOffset` to account for the height of the tab bar.

```
<KeyboardAvoidingView
  style={{flex: 1}} 
  behavior={'padding'} 
  keyboardVerticalOffset={65}>
    <FlatList .../>
    <TextInput ... />
</KeyboardAvoidingView>
```

Not sure if you're experiencing the same issue @Talor-A, but hope this helps in case you are.

**Comment by joonhocho** [comment]
@housseindjirdeh Thanks! That fixed my issue!

**Comment by martinezguillaume** [comment]
@housseindjirdeh Nice one ! Hope it'll be fixed soon

**Comment by DavidSongzw** [comment]
@Talor-A you can try this
`android:windowSoftInputMode="adjustPan"`

**Comment by kelset** [comment]
Pinging OP @Talor-A since this issue is quite old and related to an old version of the lib (and the solution provided by @housseindjirdeh seems to work). If no answer I'll close in 7 days.

**Comment by lukewlms** [comment]
I updated @housseindjirdeh's answer in my code to look good for iPhone X as well:

```
export const isIPhoneX = Dimensions.get("window").height === 812;

...

      keyboardVerticalOffset:
        // iPhone X needs a different offset for tab bar
        // Based loosely on: https://github.com/react-navigation/react-navigation/issues/2589#issuecomment-352111666
        isIPhoneX ? 85 : 65,
    };
```

**Comment by Ashoat** [comment]
In my case, I have a TabNavigator that nests a StackNavigator. If I wrap the whole app, the tab bar get pushed up when the keyboard is up, which isn't exactly what I want. Instead, I want to wrap just the StackNavigator, but since it's nested I need to make sure that both props and statics are forwarded. Here's a code snippet of how it works:

```js

const Chat = createStackNavigator(...);

const KeyboardAvoidingChat = props => (
  <KeyboardAvoidingView style={{ flex: 1 }}>
    <Chat {...props} />
  </KeyboardAvoidingView>
);
hoistNonReactStatics(KeyboardAvoidingChat, Chat);
```

**Comment by anshumanburman** [comment]
below solution worked for me on both ios and android. 
<KeyboardAvoidingView
            behavior={Platform.OS == "ios" ? "padding" : undefined}
            style={{ flex: 1 }}
          >
            <RootNavigator />
          </KeyboardAvoidingView>

**Comment by exequielc** [comment]
> @Talor-A you can try this `android:windowSoftInputMode="adjustPan"`

How I do that in Xcode config for iOS system?
