### ISSUE TITLE
See through header components on navigate

### ISSUE THREAD

**Issue by ferologics** [react-community/react-navigation#729]
When you pop / push with StackNavigator the left component is see through. Watch closely the back button.

![ezgif com-crop](https://cloud.githubusercontent.com/assets/5576161/24065383/c2f1e688-0b6a-11e7-8ddd-e26abaa688b3.gif)

Setting background/underlay color for the back button component should change the behavior.

**Comment by spencercarli** [comment]
I believe @skevy is [working on this](https://twitter.com/skevy/status/884932473070735361)

**Comment by ferologics** [comment]
Close the issue once it's done, not when someone is allegedly working on it, then we can reference the PR @spencercarli. Until then it should be open.

**Comment by kelset** [comment]
Pinging OP @ferologics since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @ferologics ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.
