### ISSUE TITLE
Issue with using reset action on pushed screen

### ISSUE THREAD

**Issue by manfredxu99** [react-community/react-navigation#738]
I'm using react-navigation for an iOS app. Using a StackNavigator with the configuration:

```
const Router = StackNavigator({
  Landing: { screen: LandingScreen },
  Login: { screen: LoginScreen },
  SignUp: { screen: SignUpScreen },
  SignUpInfo: { screen: SignUpInfoScreen },
  Main: { screen: MainScreen }
}, {
  initialRouteName: 'Landing',
})
```

The initial screen is `Landing`, then I navigate to`Login`, i.e. `NavigationActions.navigate({routeName: 'Main'})`

From the login screen I want to navigate to the main screen and reset the navigation stack. This is what I tried:

```
return dispatch(NavigationActions.reset({
      index: 0,
      actions: [
        NavigationActions.navigate({routeName: 'Main'})
      ]
}))
```

This does reset the stack, but I'm getting the appearance of the `Login` popping back to `Landing` before it occurs. How can I prevent this?
[Video of the problem](http://recordit.co/CktKHMtyR7)

**Comment by Minishlink** [comment]
+1

It'd be great to be able to disable animations when resetting the stack. If you have many routes to pop, it becomes really ugly.

**Comment by willyao94** [comment]
+1

**Comment by bgdavidx** [comment]
+1

**Comment by ncboodah** [comment]
+1

**Comment by philolo1** [comment]
+1

**Comment by michalpetrov** [comment]
+1

**Comment by ayberkanilatsiz** [comment]
+1

**Comment by etruta** [comment]
+1

**Comment by laclance** [comment]
+1

**Comment by diegorodriguesvieira** [comment]
+1

**Comment by CiralaDevelopment** [comment]
This can be solved with a custom navigator. My solution is based on the assumption that you will only ever reset and use one navigate in the reset call.

Render function of navigator:
```
const lastScreenInStack = transitionProps.scenes[transitionProps.scenes.length - 1];

const activeScenes = transitionProps.scenes.filter(
    (scene: NavigationScene) => 
        !scene.isStale || scene.index === lastScreenInStack.index,
);

const scenes = transitionProps.scenes.map((scene: NavigationScene) => {
    if (
        scene.isStale && 
        scene.index !== lastScreenInStack.index
    ) {
        return null;
    }

    const params = {
        navigation: this.props.navigation,
        router: this.props.router,
        transitionProps,
        scene,
    };

    if (activeScenes.length === 2 && activeScenes[1].isStale) {
        return resetAnimation(params, scene.isStale);
    }

    return yourNormalAnimation(params, scene);
});
```

What I'm doing here is filter out all stale scenes (scenes removed by reset) except for the last one in the stack (which would be the last scene visited before reseting). I'm then left with our new active scene and the last visited scene that is now stale. If I only have two scenes and the latter is stale then I assume a reset has been dispatched and render the reset animation instead which looks like the following:
```
const resetAnimation = (params: Params, isStale: boolean) => {
    const { transitionProps, scene, router, navigation } = params;
    const { progress } = transitionProps;

    const opacity = progress.interpolate({
        inputRange: [0, 1],
        outputRange: isStale ? [1, 0] : [0, 1], // fade out if stale, fade in if active
    });

    const Scene = router.getComponentForRouteName(scene.route.routeName);

    return (
        <Animated.View style={{
            opacity,
            position: 'absolute',
            top: 0,
            left: 0,
            height: '100%',
            width: '100%',
        }} key={scene.key}>
            <Scene navigation={navigation}  />
        </Animated.View>
    );
};
```
Note that I'm animating based on progress instead of position (recommended) since the index of the stale scene is most often not a sibling of the new active scene at index 0. 

**To use this functionality it either needs to be implemented in the stack navigator or in a custom navigator**
I don't have time to create a PR to add it to StackNavigator but I hope this provides a general idea of how it could be solved by some one who has the time to do it. Would gladly help if some one picks it up!

**Comment by ChiWuSage** [comment]
+1

**Comment by RonnieRen** [comment]
+1

**Comment by iamawebgeek** [comment]
+1

**Comment by kelset** [comment]
Closing this in favor of #1493 since it's the one with the most comments and proposed solution (just trying to reduce redundancy)
