### ISSUE TITLE
How can I go to top level component in any where?

### ISSUE THREAD

**Issue by JimmyDaddy** [react-community/react-navigation#773]
top level component is dynamic。
I mean go to top level component through index or something else, NOT routeName
like navigator.popToTop

**Comment by annelorraineuy** [comment]
I'd like to know how to do this too.

**Comment by annelorraineuy** [comment]
@JimmyDaddy perhaps you can try this, but then you have to take note and store the routeName of your dynamic top level component somewhere (maybe you're redux store in an app state?) - https://reactnavigation.org/docs/navigators/navigation-actions#Back

**Comment by JimmyDaddy** [comment]
@annelorraineuy thanks for your solution, I have thought  about this, I think this solution is not elegant or something, so this is my secondary choice, I think `react-navigation` should provide an API for this.

**Comment by quadsurf** [comment]
needing this kind of feature is not an edge case... the most common use case for needing this "popToTop" feature, is when a user logs out of the app... in fact, "popToTop" is not even a good solution for this if you need your root component/index re-rendered... NavigationActions.reset is the only thing that comes close, but unfortunately since the routeName is scoped to the current sub-stack and not the global/parent stack, 'reset' cannot solve this common use case either

**Comment by JimmyDaddy** [comment]
I solved this problem by handling redux by myself.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
