### ISSUE TITLE
(0 , _reactNative.TabNavigator) is not a function

### ISSUE THREAD

**Issue by PhpGuyZim** [react-community/react-navigation#812]
![bug](https://cloud.githubusercontent.com/assets/6696297/24301821/45aef554-10b9-11e7-8828-98c627006dac.jpg)

While working through the example in docs, the first step/page (https://reactnavigation.org/docs/intro/) was perfect. Everything worked as advertised (I did have to import button and View which the example didn't)...but page 2 (https://reactnavigation.org/docs/intro/nesting) has got me stumped.

Why is TabNavigator giving that error? Do I need to import something I missed?
My code:

```
import React from 'react';
import {
	AppRegistry,
	Text,
	View,
	Button,
	TabNavigator
} from 'react-native';
import { StackNavigator } from 'react-navigation';

import Splash from './app/components/Splash';
import HomeScene from './app/components/HomeScene';
import SettingsScene from './app/components/SettingsScene'; 

const myapp = StackNavigator({
	Home: { screen: HomeScene },
	Settings: { screen: SettingsScene },
});     

const MainScreenNavigator = TabNavigator({
	home: { screen: HomeScene },
	settings: { screen: SettingsScene },
});

AppRegistry.registerComponent('myapp', () =>myapp);
```

**Comment by browniefed** [comment]
`import { TabNavigator} from "reacts navigation" `  not from react-native

**Comment by PhpGuyZim** [comment]
Right on the money! Life saver! Thank you.

**Comment by chetanparakh** [comment]
<img width="447" alt="screen shot 2018-03-17 at 10 34 13 pm" src="https://user-images.githubusercontent.com/18354984/37562017-f3199368-2a33-11e8-8c1e-6dcb73422b4e.png">
<img width="657" alt="screen shot 2018-03-17 at 10 35 15 pm" src="https://user-images.githubusercontent.com/18354984/37562018-f76b0168-2a33-11e8-9c2d-cd88a9371ec2.png">
<img width="1034" alt="screen shot 2018-03-17 at 10 35 29 pm" src="https://user-images.githubusercontent.com/18354984/37562021-fb476df8-2a33-11e8-9492-4465d7bd3b72.png">

Getting similar error but with _reactNavigation.TabNavigator instead of _reactNative.TabNavigator. Any idea why?

**Comment by mar8388** [comment]
I have the same

**Comment by rmn528** [comment]
same here

**Comment by brentvatne** [comment]
please post a new issue with a repro on https://snack.expo.io or in a new project

https://snack.expo.io/HkXt9dWqf - this shows it works as expected
