### ISSUE TITLE
Possibility to get drawer position/width value while sliding

### ISSUE THREAD

**Issue by sonaye** [react-community/react-navigation#898]
I would like to change an animation state (hamburger menu) based on the sliding value, is this possible? no info in the docs on that nor was I able to find a workaround in the source code.

**Comment by ericvicenti** [comment]
This is not currently supported, but there may be a reasonable way to add it on iOS, which uses the animated API for this. On Android it may be trickier because we use the native drawer.

If you can add this feature in a nice way, then it might make sense to add the feature. If you have an idea on how to do it, want to create a RFC issue to start discussion?

**Comment by sonaye** [comment]
Hmm, let me poke around in the source code first and see where we can go from there.

**Comment by Noitidart** [comment]
I am also wanting to do this. I want to animate/rotate an icon in my header based on slide position of the drawer. @sonaye were you able to find a solution? I am targetting Android.

**Comment by sonaye** [comment]
@Noitidart I didn't further investigate this to be honest.

**Comment by Noitidart** [comment]
Thanks for your reply. I ended up doing my own drawer implemntation with [react-native-interactable](https://github.com/wix/react-native-interactable).
