### ISSUE TITLE
Publish 1.0.0-beta.8 to use with RN 0.43

### ISSUE THREAD

**Issue by olebedev** [react-community/react-navigation#906]

**Comment by h31639347** [comment]
Delete this row 
“import ReactComponentWithPureRenderMixin from 'react/lib/ReactComponentWithPureRenderMixin';
” from \node_modules\react-navigation\src\views\Header.js

**Comment by TyrealGray** [comment]
@h31639347 That does not solve the issue. You can not expect all the team members do it manual.

**Comment by grabbou** [comment]
New release will be shipping shortly (either today or tomorrow). There will be a breaking change - expect blog post coming.

**Comment by dedykuw** [comment]
Nights I I org

**Comment by nonameolsson** [comment]
Sounds great! I have had a hard time to keep up with all the changes on current master branch. Today my app broke when I upgraded to `react-native 0.43.3`. This has kept me busy all day long. It was my fault because I had used Android Studio and upgraded gradle configs, which I shouldn't have done.

After fixing those errors I found out that there had been a lot of changes to `master`, but I did get help from @jurajkrivda in #1047. That's when I saw the breaking changes in the updates.
 
Here are also some issues that helped me perform the upgrade. Just in case someone else gets the same problem.
https://github.com/oblador/react-native-vector-icons/issues/428
#1012 
#974 
#923

**Comment by vexsnare** [comment]
When can we expect  1.0.0-beta.8 ?

**Comment by grabbou** [comment]
Not before F8 conference. I would say around the beginning of next week -
depends if we make all the changes on time.

**Comment by nonameolsson** [comment]
@grabbou Thanks for your answer!

**Comment by satya164** [comment]
It's already on NPM.

**Comment by jesperlndk** [comment]
Hey @grabbou , any update on this (release of 1.0.0-beta.8)?

**Comment by grabbou** [comment]
We are closing remaining issues and working on rolling out an update ASAP.
You can try master in the meantime if you are not afraid of breakage.
