### ISSUE TITLE
Using StackNavigator without CardStack (custom StackRouter?)

### ISSUE THREAD

**Issue by p-cherukuri** [react-community/react-navigation#914]
I'm using react-native-maps to render a map with markers. I'd like to be able to click a marker, and have the map state change to zoom in and show a bunch of markers within that top level marker's location. In this new state, there's also a button available to go back to the top level view. I got this to work initially by just using this.setState() and if-else statements, but I realize mutating the state directly isn't the best way to implement it.

To solve this, I'm trying to implement a StackNavigator or custom StackRouter with two screens - the initial screen being the map with its top level markers, and the second screen being the zoomed in view with markers at that location that's been clicked on (all top level view markers disappear in this view). However, I don't want the CardStack style of navigation between these screens to occur - I just want the map to stay in place, and change its region/markers based on the state.

How does one implement a custom Navigator that functions as a StackNavigator without the CardStack transition? Do I need an explicit top level Navigator to solve this or just a StackRouter? Or should I just be using Redux to switch between these states? Quite confused even after reading the documentation..

```
import MapView from 'react-native-maps'
import {
  StackRouter,
  createNavigator,
  createNavigationContainer,
  addNavigationHelpers,
  NavigationActions,
} from 'react-navigation'

// StackRouter

const MapRouter = StackRouter({
  MarkerMap: {screen: Markers,},
  ZoomedMarkerMap: {screen: ZoomedMarkers,},
}, {
  initialRouteName: 'MarkerMap',
});

// custom Navigator ?

export default class MapNav extends Component {
  static router = MapRouter;

  render() {
    
  }
}

// Top level markers screen

class Markers extends Component {

  static navigationOptions = {
    header: {
      visible: false,
    }
  }

  constructor(props) {
    super(props);
    this.state = {
      navigation: this.props.navigation
    };
  }

  render() {
    return (
      <View>
        <MapView
          ref={ref => { this.map = ref; }}
          onLayout = {() => this.fitAllMarkers()}
        >
            <MapView.Marker
              ref={ref => {marker = ref;} }
              key={marker.id}
              coordinate={marker.latlng}
              title={marker.title}
              description={marker.description}
              onPress={ () => this.state.navigation.navigate("ZoomedMarkerMap") }
             />
        </MapView>
      </View>
    );
  }
}

// Zoomed in markers screen

class ZoomedMarkers extends Component {

  static navigationOptions = {
    header: {
      visible: false,
    }
  }

  constructor(props) {
    super(props);
    this.state = {
      navigation: this.props.navigation
    };
  }

  render() {
    return (
      <View>
        <MapView
          ref={ref => { this.map = ref; }}
          onLayout = {() => this.fitAllMarkers()}
        >
          {zoomMarkers.map(marker => (
            <MapView.Marker
              ref={ref => {marker = ref;} }
              key={marker.id}
              coordinate={marker.latlng}
              title={marker.title}
              description={marker.description}
             />
          ))}
        </MapView>
        <View>
          <Button
            onPress={ () => this.state.navigation.navigate("MarkerMap") }
            title="Back to MarkerMap"
          />
        </View>
      </View>
    );
  }
}
```

**Comment by ericvicenti** [comment]
If you want to add navigation logic to your screen, you can put a `static router = StackRouter({});` on it, and then you will get a `navigation.state` and `navigation.dispatch` to use within your component.

**Comment by kalraneeraj24550** [comment]
Do you have an example where I can use these custom transitions inside a Custom navigator created using the createNavigationContainer(
createNavigator(AppStackRouter)(StackView)
);

This is based off of CustomTabs example in react-navigation examples. Here I am confused as to how do I pass my transitionConfig inside createNavigator.

here is how I defined my StackRouter( which seems to take the stackConfig which in turn seems to take a StackConfig param as per here .

export const AppStackRouter = StackRouter(defaultMap, {
initialRouteName: 'StartScreenView',
transitionConfig: TransitionConfiguration,
});

But still the console.log (), I wrote inside the screenInterpolator of the transitionConfig is not hit :(. Any thoughts on what I am doing wrong?

UPDATE 2:
Tried a different approach by passing the transition config to teh createNavigator 3rd argument
createNavigationContainer(
createNavigator(AppStackRouter, {}, {transitionConfig: TransitionConfiguration})(StackView)
);

still the console.log inside my screenInterpolator did not get hit . I am officially out of ideas now in trying to get animations to work inside a Custom navigator. I would expect the default stack animations would exist even if we create a custom stack navigator, but turns out it is not the case
