### ISSUE TITLE
Using react-navigation with Redux, WITHOUT getStateForAction

### ISSUE THREAD

**Issue by santiagopoli** [react-community/react-navigation#918]
Hi,

I know that **getStateForAction** is there for a reason. It resolves the problems regarding navigation state management. What I don't like, though, is the fact that I need to use that function via a Component (the Navigator). For me its very weird that, to create my store, I have to first initialize a Navigator and then my reducer needs to hold a reference to it (which is a React component, so my reducer/store should know nothing about it), so it can call the getStateForAction function.

I know it's pretty cool by i'm kind of a purist, so I don't like it. When using NavigationExperimental I was able to inject the navigation state via props (from the store).

Is there a way to achieve this behavior with react-navigation? Are there any plans to make this case more easier to implement? Maybe a Global/Static **getStateForAction** should do the trick

Thanks (and sorry haha)!

**Comment by ericvicenti** [comment]
> What I don't like, though, is the fact that I need to use that function via a Component (the Navigator)

Depending on how you use React Nav, this statement is not quite correct. If you use the navigator factories, then yes, the `getStateForAction` is on the component, but you don't have to do that. Instead, you could create the router directly, and then use that for your reducer and store. Then your component would also refer to the router in order to figure out what component and options to show for each route.

Also, if you don't want to use the router's `getStateForAction`, you can feel free to implement the navigation reducer yourself.

I'm also a purist, and I think the structure can actually be pretty decent, as long as the router is decoupled. The navigator is just there for people's convenience, and it sounds like you don't need it.

I'm going to close this issue because it doesn't have much actionable to do on it. But the discussion is great, and if you have a specific idea on improving things, feel free to open a RFC issue.

Lastly, I'll admit that the docs for the router-centric approach is highly lacking. If you have an interest in improving them, that would be greatly appreciated!

**Comment by RubenSandwich** [comment]
@santiagopoli 

I was in the same boat as you. I would prefer all data to live in my reducers and for the reducer data to be the source of truth. To achieve this I store React Navigation routers state in my Reducers and pass that routers state to the Navigators. This allows me to keep the reducer as the source of truth in my app.

Navigation Reducer:
https://github.com/CMP-Studio/BeaconDeploymentTool/blob/master/src/reducers/navigation.js

Initing a Navigator:
https://github.com/CMP-Studio/BeaconDeploymentTool/blob/master/src/components/rootScreen.js

If this is helpful to you. I suggest upping this issue I created to allow navigators routers to be passed in which would allow my solution to be less 'hacky':
https://github.com/react-community/react-navigation/issues/797
