### ISSUE TITLE
Delay BackAndroid on certain scenes

### ISSUE THREAD

**Issue by Doko-Demo-Doa** [react-community/react-navigation#980]
As title said. I want to implement the delay for BackAndroid. For example, calling an API before going back to previous scene. Any ideas?

**Comment by dominicrj23** [comment]
As per react-native docs 

>  The event subscriptions are called in reverse order (i.e. last registered subscription first), and if one subscription returns true then subscriptions registered earlier will not be called.

Since you can not return a promise from the listener function, you would have to handle 'back to the previous scene' action yourself.

```
   BackAndroid.addEventListener('hardwareBackPress', function() {
     api.call().then(()=> dispatch(NavigationAction.goBack()));
    });
```

This may cause significant delay in going back to the previous scene, which isn't going to be a good user experience. 
If you are not dependent on your Api call to fetch some data for rendering scene, I would rather advice to use this instead:

```
   BackAndroid.addEventListener('hardwareBackPress', function() {
     api.call();
     return false;
  });
```

**Comment by ericvicenti** [comment]
The current API does not allow you to do this easily, unless you use controlled navigators like we do in the redux example. (To control a navigator, you can provide it with the navigation prop).

But ultimately I think we should add a feature to the `containerOptions` that allows you to have a hook `onNavigate`, and allows behavior overriding.

**Comment by Doko-Demo-Doa** [comment]
Thanks @ericvicenti , that's what I'm looking for.
Auto-handling BackAndroid sure is cool, but it does have drawbacks in many cases.
