### ISSUE TITLE
Android not receiving screenProps from nested StackNavigator from TabNavigator

### ISSUE THREAD

**Issue by juhaelee** [react-community/react-navigation#994]
I have a tab bar uses screenProps like this:

```
<TabBar screenProps={{ rootNavigation: this.props.navigation }} />
```
The tab bar is a tab navigator that is instantiated like so:
```
TabNavigator({
   tabOne: { screen: AStackNavigator },
   tabTwo: { screen: AnotherStackNavigator },
})
```

In ios the screensProps are passed to the screens in `AStackNavigator`, but in android, `rootNavigation` is undefined.

I believe that the intended way is the iOS way where nested navigators receive screenProps from the top most parent. Is this a bug or intentional?

Currently on master and using `react-native 0.43.1`

**Comment by grabbou** [comment]
@satya164 do you think that's something with the native android pager?

**Comment by kelset** [comment]
Pinging OP @juhaelee  since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @juhaelee, 

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.
